---
title: "Homework 7 Answers"
subtitle: "Assignment due 11/22/24"
author: "Nicky Wakim"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    number-sections: true
    number-depth: 3
    theme: lumen
    embed-resources: true
    html-math-method: mathjax
---

::: callout-warning
To see my math equations properly, you need to download the html file, then open it! One Drive does not show the math correctly!!
:::

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```

```{=html}
<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
```

# Book exercises


## 5.16 Paired or not, Part II {.unnumbered}

## 5.22 DDT exposure {.unnumbered}

## 5.26 Egg volume {.unnumbered}

Maybe skip this one

## 5.34 Placebos without deception {.unnumbered}

## 4.22 Testing for food safety {.unnumbered}

# Non-book exercises

## Power and Sample size: Auto exhaust and lead exposure revisited

### Power

In exercise 5.12 in Homework 6, we tested whether police officers appear to have been exposed to a higher concentration of lead than 35. Calculate the power for the hypothesis test and include an interpretation of the power in the context of the research question. Was it sufficiently powered? 



### Sample size

For the same test, what sample size would be needed for 80% power? Would it be reasonable to conduct the study with these sample sizes? Why or why not? (Hint: think about the assumptions of our distributions when using a t-test)


### Effect size

Suppose the study has resources to include 30 people. What minimum effect size would they be able to detect with 85% power assuming the same sample mean and standard deviation. Use $\alpha$ = 0.05. 


## R1: Swim times

* In these exercises you will use R to work through the swim times example from Section 5.2 in the textbook. 
* The data are in the `oibiostats` package and called `swim`.


### Mean & SD of differences 

Calculate the mean and standard deviation for the differences in swim times, and compare them to the ones in the book. Which order were the differences calculated, wet suit - swim suit or the opposite? Were all the differences positive? 


### Dot plot of differences

Create a histogram of the differences in swim times and comment on the distribution shape. 


### Hypothesis test

Run the appropriate statistical test in R as both a one-sample t-test and a paired t-test to verify the test statistic, p-value, and CI in the text. Use inline R code to pull these values from the test output when writing up your comparison of these values to the book's values. 

## R2: 2-sample independent t-test
