---
title: "About"
---

## Meike Niederhausen

* [Assistant Professor of Biostatistics](https://ohsu-psu-sph.org/our-school/faculty-directory/name/meike-niederhausen/) in the [OHSU-PSU School of Public Health](https://ohsu-psu-sph.org/)
* Faculty Biostatistician for OHSU's [Biostatistics & Design Program](https://www.ohsu.edu/research-cores/biostatistics-design-program)
* Affiliate Investigator for the HSR&D Center to Improve Veteran Involvement in Care ([CIVIC](https://www.portlandcoin.research.va.gov/index.asp)) at the Portland VA

## Course info

This webpage was created for BSTA 511/611 in the [OHSU-PSU School of Public Health](https://ohsu-psu-sph.org/). BSTA 511 is taken primarily by students in the Biostatistics MS/MPH and Epidemiology MPH programs. BSTA 611 is taken by PhD students in various programs across OHSU.

## Acknowledgements

* Thank you to [Nicky Wakim](https://github.com/nwakim/) for creating her amazing webpage for [BSTA 550](https://nwakim.github.io/F2023_BSTA_550/), and sharing her code on [GitHub](https://github.com/nwakim/F2023_BSTA_550). Having her template made creating this website a much smoother process.
* Thank you also to [Andrew Bray](https://andrewpbray.github.io/) for presenting the [From R Markdown to Quarto](https://andrew.quarto.pub/oregon-asa/) ASA Travelling Workshop to the Oregon Chapter of the ASA in June 2023. This workshop was a great starting point in making the switch from RMarkdown to Quarto and also create Quarto webpages. 

