---
title: "Homework"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
---

## Homeworks

| Homework      | Due date (\@11pm) | Assignment                                                                                             | Answers                                                                                  | Solutions (`.qmd`)                                                              | Solutions (`.html`)\*                                                 |
|---------------|-------------------|--------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------|-----------------------------------------------------------------------|
| 0             | 10/3              | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_00.qmd)]{style="color:#f8f5f0;"} | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 1             | 10/10             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_01.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 2             | 10/17             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_02.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 3             | 10/25             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_03.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_03.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 4             | 10/31             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_04.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_04.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 5             | 11/7              | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_05.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_05.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 6             | 11/16             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_06.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_06.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 7             | 11/21             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_07.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_07.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 8             | 11/26             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_08.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_08.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 9             | 12/5              | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_09.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_09.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
| 10 (optional) | 12/12             | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_10.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ph key-fill size=29px >}}](/hw_answers/HW_10.qmd)]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |

\*Please note that you need to download the `.html` file to see the LaTeX math properly.

## Structure

There are three distinct parts to our homework:

| Homework part             | Due date             | What is required?                                                                                                                                                                                                                                                              | Grading                                                                                                                                                                                                                                                                                                         |
|---------------------------|----------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Individual *assignment*   | Date specified above | You will complete the homework assignment, and turn in an individual copy of your work. This will be graded for completion.                                                                                                                                                    | For completion                                                                                                                                                                                                                                                                                                  |
| Group *solutions*         |                      | With groups of 4, you will make a homework key for 4 questions (that Nicky chooses). Each group member will be in charge of turning in one question's solutions. This will be graded for correctness. The group will receive the same grade, which is summed across questions. | For correctness                                                                                                                                                                                                                                                                                                 |
| Individual *presentation* |                      | For homeworks \_\_ and \_\_\_, you will also need to make a video or meet with me. You will use less than 10 minutes to explain your homework question solutions. This will be graded for correctness.                                                                         | Graded out of 4 points. 0 indicating no understanding of the solutions. 1 indicating some basic understanding, but missing major steps. 3 indicating that most of the problem is considered, but not necessarily all or all correctly. 4 indicating that all needed parts were considered and correctly solved. |

If you are having any group dynamic issues, please please please come see me earlier rather than later! You do not need to wait for group evals. We will come up with options for moving forward!
