---
title: "Schedule"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

| Week | Date                                | Les-son | Topic                                                                                 | TB sections  |                                                           Key Info                                                            |                                                                  Slides QMD                                                                  |                                                        Slides PDF                                                        |                                                             Slides Notes                                                             |                          Record-ing                           |                                                         Muddy Points                                                          |
|-------|-------|-------|-------|-------|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 1    | 9/30                                | 0       | Welcome                                                                               |              |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                    [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                     |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | 1       | Data collection                                                                       | 1.3          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |          [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Data_collection/01_Data_collection.qmd)]{style="color:#f8f5f0;"}          |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | *R01*   | *Download R and RStudio*                                                              |              | [[{{< iconify akar-icons info-fill size=30px >}}](/lessons/01_Intro_to_R/01_Intro_to_R_key_info.qmd)]{style="color:#f8f5f0;"} |              [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/01_Intro_to_R/01_Intro_to_R.qmd)]{style="color:#f8f5f0;"}               | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/01_Intro_to_R/01_Intro_to_R.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](/lessons/01_Intro_to_R/01_Intro_to_R_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](/lessons/01_Intro_to_R/01_Intro_to_R_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|      | 10/2                                | 2       | Intro to Data, Summarizing numerical data                                             | 1.1-1.2, 1.4 |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Intro_data_num_summaries/02_Intro_data_num_summaries.qmd)]{style="color:#f8f5f0;"} |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      | [**10/3**]{style="color:#3070BF;"}  |         | [**HW 0 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 2    | 10/7                                | 3       | Defining Probability                                                                  | 2.1          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |              [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_Probability/03_Probability.qmd)]{style="color:#f8f5f0;"}              |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R02     | R Basics                                                                              |              |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                    [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                     |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     |         | Getting help when coding (functions, AI, etc)                                         |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | 10/9                                | 4       | Conditional Probability                                                               | 2.2          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_Bayes_thm/04_Bayes_thm.qmd)]{style="color:#f8f5f0;"}                |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R03     | Reproducibility, File Organization, and Projects                                      |              |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                    [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                     |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      | [**10/10**]{style="color:#3070BF;"} |         | [**HW 1 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 3    | 10/14                               | 5       | Random variables, Binomial distribution                                               | 3.1-3.2      |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |             [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_RVs_Binomial/05_RVs_Binomial.qmd)]{style="color:#f8f5f0;"}             |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R04     | Intro to Quarto, packages, and importing data                                         |              |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                    [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                     |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      | 10/16                               | 6       | Normal and Poisson distributions                                                      | 3.3-3.4      |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |           [[{{< iconify ri slideshow-fill size=30px >}}](lessons/06_Normal_Poisson/06_Normal_Poisson.qmd)]{style="color:#f8f5f0;"}           |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R05     | `ggplot` part 1                                                                       |              |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                                    [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"}                                     |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      | [**10/17**]{style="color:#3070BF;"} |         | [**HW 2 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**10/20**]{style="color:#3070BF;"} |         | [**HW 1 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**10/21**]{style="color:#3070BF;"} |         | [**Group Eval 1 due 11pm**]{style="color:#3070BF;"}                                   |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 4    | 10/21                               | 7       | Data visualization, exploratory data analysis (EDA), and summarizing categorical data | 1.5-1.7      |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |    [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_Data_visualization_01/07_Data_visualization_01.qmd)]{style="color:#f8f5f0;"}    |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R06     | `ggplot` part 2                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | 10/23                               | 8       | Data visualization, exploratory data analysis (EDA), and summarizing categorical data | 1.5-1.7      |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |    [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_Data_visualization_02/08_Data_visualization_02.qmd)]{style="color:#f8f5f0;"}    |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R07     | LaTeX in Quarto                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**10/24**]{style="color:#3070BF;"} |         | [**HW 3 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**10/27**]{style="color:#3070BF;"} |         | [**HW 2 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 5    | 10/28                               | 9       | Variability in estimates                                                              | 4.1          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |              [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_Variability/09_Variability.qmd)]{style="color:#f8f5f0;"}              |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R08     | Revisiting projects and the `here` package                                            |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | 10/30                               | 10      | Confidence Intervals                                                                  | 4.2          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |     [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_Confidence_intervals/10_Confidence_intervals.qmd)]{style="color:#f8f5f0;"}     |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R09     | Subsetting data with `tidyverse`                                                      |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**10/31**]{style="color:#3070BF;"} |         | [**HW 4 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/3**]{style="color:#3070BF;"}  |         | [**HW 3 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 6    | 11/4                                | 11      | Hypothesis Testing 1: Single-sample with *t*-distribution                             | 4.3, 5.1     |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |           [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Hyp_testing_01/11_Hyp_testing_01.qmd)]{style="color:#f8f5f0;"}           |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R10     | Transforming data with `tidyverse`                                                    |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | 11/6                                | 12      | Hypothesis Testing 2: Two-sample paired data                                          | 5.2          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |           [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Hyp_testing_02/12_Hyp_testing_02.qmd)]{style="color:#f8f5f0;"}           |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R11     | Summarizing data with `tidyverse`                                                     |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/7**]{style="color:#3070BF;"}  |         | [**HW 5 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/10**]{style="color:#3070BF;"} |         | [**HW 4 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/?**]{style="color:#3070BF;"}  |         | [**HW 3 presentation due \@ 11 pm**]{style="color:#3070BF;"}                          |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 7    | 11/11                               | 13      | Hypothesis Testing 3: Two-sample independent data                                     | 5.3          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |           [[{{< iconify ri slideshow-fill size=30px >}}](lessons/13_Hyp_testing_03/13_Hyp_testing_03.qmd)]{style="color:#f8f5f0;"}           |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R12     | More Quarto!                                                                          |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/12** ]{style="color:#3070BF;"}                          |         | [**Group Eval 2 due 11pm**]{style="color:#3070BF;"}                                   |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | 11/13                               | 14      | Power and sample size calculations (from Hyp Test 3)                                  | 5.4          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |        [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_Power_sample_size/14_Power_sample_size.qmd)]{style="color:#f8f5f0;"}        |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R13     | Making Table 1                                                                        |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/14**]{style="color:#3070BF;"} |         | [**HW 6 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/17**]{style="color:#3070BF;"} |         | [**HW 5 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 8    | 11/18                               | 15      | Inference for a single proportion or difference in proportions                        | 8.1-8.2      |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |           [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_Prop_inference/15_Prop_inference.qmd)]{style="color:#f8f5f0;"}           |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R14     | Joining data                                                                          |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | 11/20                               | 16      | Chi-squared tests, Fishers exact test                                                 | 8.3-8.4      |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |            [[{{< iconify ri slideshow-fill size=30px >}}](lessons/16_Chi_sq_Fisher/16_Chi_sq_Fisher.qmd)]{style="color:#f8f5f0;"}            |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      |                                     | R15     | Special topics                                                                        |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/21**]{style="color:#3070BF;"} |         | [**HW 7 due \@ 11 pm**]{style="color:#3070BF;"}                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/24**]{style="color:#3070BF;"} |         | [**HW 6 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 9    | 11/25                               | 17      | Comparing Means with ANOVA                                                            | 5.5          |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                    [[{{< iconify ri slideshow-fill size=30px >}}](lessons/17_ANOVA/17_ANOVA.qmd)]{style="color:#f8f5f0;"}                    |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      | 11/28                               |         | No class                                                                              |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**11/27**]{style="color:#3070BF;"} |         | [**HW 8 due 11 pm**]{style="color:#3070BF;"}                                          |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**12/1**]{style="color:#3070BF;"}  |         | [**HW 7 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 10   | 12/2                                | 18      | Simple Linear Regression                                                              | 6.1-6.4      |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |                   [[{{< iconify ri slideshow-fill size=30px >}}](lessons/18_SLR_01/18_SLR_01.qmd)]{style="color:#f8f5f0;"}                   |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      | 12/4                                | 19      | Non-parametric tests (sign, signed-rank, rank-sum, Kruskal-Wallis)                    | Other TB     |                           [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"}                            |           [[{{< iconify ri slideshow-fill size=30px >}}](lessons/19_Non_parametric/19_Non_parametric.qmd)]{style="color:#f8f5f0;"}           |                       [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"}                       |                          [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"}                          | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} |                             [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"}                              |
|      | [**12/5**]{style="color:#3070BF;"}  |         | [**HW 9 due 11 pm**]{style="color:#3070BF;"}                                          |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**12/8**]{style="color:#3070BF;"}  |         | [**HW 8 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [12/?]{style="color:#3070BF;"}      |         | [HW 6 presentations due 11pm]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      |                                     |         |                                                                                       |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
| 11   | 12/9                                |         | Catch up day                                                                          |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**12/12**]{style="color:#3070BF;"} |         | [**Optional HW 10 due 11 pm**]{style="color:#3070BF;"}                                |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |
|      | [**12/13**]{style="color:#3070BF;"} |         | [**HW 9 solutions due 11pm**]{style="color:#3070BF;"}                                 |              |                                                                                                                               |                                                                                                                                              |                                                                                                                          |                                                                                                                                      |                                                               |                                                                                                                               |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 46,6, 6, 6, 6, 6,6,6\]"}
