---
title: "Homework 1"
subtitle: "Lessons 1-2"
author: "Your name here - update this!!!!"
date: "Due 10/10/24"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    theme: lumen
    self-contained: true
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```


**Due 10/10/24**

Download the .qmd file for this assignment from [Github](https://github.com/nwakim/F24_EPI_525/blob/main/homework/HW_01.qmd).


## Directions

* Please upload your homework to Sakai. __Upload both your .qmd code file and the rendered .html file__.
* For each question, make sure to include all code and resulting output in the html file to support your answers. 
* Use the assignment .qmd file as a template for your own assignment.

:::{.callout-tip}
It is a good idea to try rendering your document from time to time as you go along!  Note that rendering automatically saves your Qmd file and rendering frequently helps you catch your errors more quickly.
:::


# Non-book exercises

## Upload a photo using Sakai submission

To help me learn your names and faces, please upload a photo of yourself on Sakai. You will find the Upload Photo "assignment" in the Submissions section of Sakai. These photos will only be seen by me and the TA.

## Background survey

Please fill out the background survey at [https://forms.gle/QsjRN1UxzmcBAP819](https://forms.gle/QsjRN1UxzmcBAP819).  
No work to be shown here. 

## Slack post

Introduce yourself to the class by posting a message in the #random channel on the BSTA 511/611 Slack group.  
No work to be shown here.  
Slack invite link: [https://join.slack.com/t/slack-zlc9838/shared_invite/zt-23wilgaki-yTTT9K~lePsEgW3~Ik07gg](https://join.slack.com/t/slack-zlc9838/shared_invite/zt-23wilgaki-yTTT9K~lePsEgW3~Ik07gg)


# Book exercises

* Exercises are in the last section of the chapter. 
* Exercises are numbered as chapter#.exercise#. For example, exercise 1.2 is Chapter 1 #2, which is on pg. 75. 

## 1.2 Sinusitis and antibiotics, Part I.

* Show the work of your calculations **using R code within a code chunk**. Make sure that both your code and output are visible in the rendered html file.
* Write your answers in complete sentences as if communicating the results to a collaborator.
* If you are having difficulty with exercise 1.2, take a look at exercise 1.1, whose answers are at the back of the book.



## 1.4 Buteyko method, study components




## 1.8 Smoking habits of UK residents



## 1.12 Herbal remedies


## 1.20 City council survey



## 1.31 Income at the coffee shop


## 1.32 Midrange
