---
title: "Homework 2"
subtitle: "Due 10/17/24"
author: "Your name here - update this!!!!"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    number-sections: true
    number-depth: 3
    theme: lumen
    self-contained: true
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```


Download the .qmd file for this assignment from [Github](https://github.com/nwakim/F24_EPI_525/blob/main/homework/HW_02.qmd).


## Directions {.unnumbered}

:::{.callout-important}
* The non-R exercises (see sections `Book exercises` and `Non-book exercise`) may be completed not using Quarto. I especially recommend writing out by hand the chapter 2 probability questions, whether on paper or a tablet.
* If you complete part of the assignment not using Quarto, you will be uploading 3 files on Sakai for HW 2: qmd & html files for your R work, and a pdf with your written work. 
* If you are completing the homework on paper, you can use a scanning app, such as Adobe Scan, to create a pdf of your assignment.
:::

* Please upload your homework to Sakai. __Upload both your .qmd code file and the rendered .html file__.
* For each question, make sure to include all code and resulting output in the html file to support your answers. 

:::{.callout-tip}
It is a good idea to try rendering your document from time to time as you go along!  Note that rendering automatically saves your Qmd file and rendering frequently helps you catch your errors more quickly.
:::



# Book exercises {.unnumbered}

## 1.24 Income and education in US counties {.unnumbered}


## 1.28 Mix-and-match {.unnumbered}



## 1.36 Associations {.unnumbered}


## 1.38 Smoking and stenosis {.unnumbered}
*See Section1.6.2 for more on how the relative risk is calculated.*

## 2.6 Poverty and language {.unnumbered}

*Part (b) asks you to create a Venn Diagram. If you are submitting this question in R, you do not need to turn this part in. If you want an R challenge though, you can use the `VennDiagram` or other package to create one. See [https://www.geeksforgeeks.org/how-to-create-a-venn-diagram-in-r/](https://www.geeksforgeeks.org/how-to-create-a-venn-diagram-in-r/) for some examples.* 

## 2.8 School absences {.unnumbered}

*Part (b) asks you to create a Venn Diagram. If you are submitting this question in R, you do not need to turn this part in. If you want an R challenge though, you can use the `VennDiagram` or other package to create one. See [https://www.geeksforgeeks.org/how-to-create-a-venn-diagram-in-r/](https://www.geeksforgeeks.org/how-to-create-a-venn-diagram-in-r/) for some examples.*  

## 2.10 Health coverage, frequencies {.unnumbered}


## 2.14 Health coverage, relative frequencies {.unnumbered}

## 2.18 Predisposition for thrombosis {.unnumbered}


## 2.24 Breast cancer and age {.unnumbered}

# Non-book exercise

Suppose a patient has abdominal pain and their clinician suspects that they either have disease 1, disease 2, or no disease, where the probability of having abdominal pain if they have disease 1 is 0.80, the probability of having abdominal pain if they have disease 2 is 0.90, and the probability of having abdominal pain if they have no disease is 0.01. Based on the patient’s medical history, the probability of having disease 1 is 0.009, having disease 2 is 0.001, and having no disease is 0.99. What is the probability the patient has disease 2 given that they have abdominal pain? 

