---
title: "Homework 5"
subtitle: "Lessons 9-10"
author: "Your name here - update this!!!!"
date: "Due 11/7/24"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    number-sections: true
    number-depth: 3
    theme: lumen
    self-contained: true
    html-math-method: mathjax
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```


**Due 11/7/24**

Download the .qmd file for this assignment from [Github](https://github.com/nwakim/F24_EPI_525/blob/main/homework/HW_05.qmd).


## Directions {.unnumbered}

* Please upload your homework to Sakai. __Upload both your .qmd code file and the rendered .html file__.
* For each question, make sure to include all code and resulting output in the html file to support your answers. 


### R & LaTeX code for probability distributions {.unnumbered}

* See the .qmd files with the code from class notes for LaTeX and R code.
* The LaTeX code will make it easier to show your work in computations.

:::{.callout-tip}
It is a good idea to try rendering your document from time to time as you go along!  Note that rendering automatically saves your Qmd file and rendering frequently helps you catch your errors more quickly.
:::


# Book exercises {.unnumbered}

## 4.2 Heights of adults {.unnumbered}


## 4.4 Mental health, Part I {.unnumbered}



## 4.6 Thanksgiving spending, Part I {.unnumbered}



## 4.8 Age at first marriage, Part I {.unnumbered}


# Non-book

## Clinican time with patients

*Suppose a clinician schedules 20 minutes to spend with each of their patients. However, they sometimes run over or end earlier. Based on past data, the mean "extra" time they spend with a patient is 3 minutes with a standard deviation of 2 minutes. Suppose they see 13 patients today and the extra times they spend with  patients are independent from patient to patient.*

### Expected total time

**Find the expected total time they will spend with all of their patients today.**


### SD of total time

**Find the standard deviation of the total time they will spend with all of their patients today.**

## The Ethan Allen

On October 5, 2005, a tour boat named the Ethan Allen capsized on Lake George in New York with 47 passengers aboard. In the inquiries that followed, it was suggested that the tour operators should have realized that the combined weight of so many passengers was likely to exceed the weight capacity of the boat. Could they have predicted this?  

* The maximum weight capacity of passengers that the Ethan Allen could accommodate was estimated to be 7500 pounds. 
* Data from the Centers for Disease Control and Prevention indicate that weights of American adults in 2005 had a mean of 167 pounds and a standard deviation of 35 pounds.


If the tour boat company consistently accepted 47 passengers, what we want to know is the probability that the combined weight of the 47 passengers would exceed this capacity.


### Maximum average weight

__With 47 passengers on board, what is the maximum average weight that the Ethan Allen could accommodate?__



### Probability an individual weighs more than the maximum average weight 

__Assuming that the weights of American adults in 2005 can be modeled with a normal distribution, find the probability that an individual weighs more than the maximum average weight the Ethan Allen can accommodate.__



### Probability a random sample of 47 American adults has an average weight greater than the maximum average weight

__Calculate the probability that a random sample of 47 American adults has an average weight greater than the maximum average weight the Ethan Allen can accommodate.__  



### What theorem did you use in the previous part, and why were you able to apply it to this problem?



### Could the tour operators have predicted realized that the combined weight of so many passengers was likely to exceed the weight capacity of the Ethan Allen?  


# R exercises 

## Load all the packages you need below here. 


## R1: Youth weights

In this exercise you will use the YRBSS dataset again that we used in class on Days 8-9, to simulate the distribution of mean weights from repeated samples. 


### Use the `set.seed()` command to set a randomization seed. Use whatever number you want for the seed.


### CI 

__Suppose you took a random sample of size 50 from the YRBSS data, that has mean weight 130 pounds. Calculate and interpret a 90% confidence interval using the standard deviation of weights from the YRBSS "population."__


### Another CI 

__Calculate and interpret a 90% confidence interval assuming the standard deviation of weights from the random sample is 40.__ 




## R2: Swim times

* In these exercises you will use R to work through the swim times example from Section 5.2 in the textbook. 
* The data are in the `oibiostats` package and called `swim`.


### Mean & SD of differences 

__Calculate the mean and standard deviation for the differences in swim times, and compare them to the ones in the book. Which order were the differences calculated, wet suit - swim suit or the opposite? Were all the differences positive?__ 


### Dot plot of differences

__Create a dot plot of the differences in swim times and comment on the distribution shape.__ 


### Hypothesis test

__Run the appropriate statistical test in R as both a one-sample t-test and a paired t-test to verify the test statistic, p-value, and CI in the text. Use inline R code to pull these values from the test output when writing up your comparison of these values to the book's values.__ 



