---
title: "Homework 8"
author: "Your name here - update this!!!!"
date: "Due 11/26/24"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    number-sections: true
    number-depth: 3
    theme: lumen
    self-contained: true
    html-math-method: mathjax
---

::: callout-important
This page is under construction. This homework may change! (11/5/24)
:::

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```


**Due Monday 11/26/24**

Download the .qmd file for this assignment from [Github](https://github.com/nwakim/F24_EPI_525/blob/main/homework/HW_08.qmd).


## Directions {.unnumbered}

* Please upload your homework to Sakai. __Upload both your .qmd code file and the rendered .html file__.
* For each question, make sure to include all code and resulting output in the html file to support your answers. 


### R & LaTeX code {.unnumbered}

* See the .qmd files with the code from class notes for LaTeX and R code.
* The LaTeX code will make it easier to show your work in computations.

:::{.callout-tip}
It is a good idea to try rendering your document from time to time as you go along!  Note that rendering automatically saves your Qmd file and rendering frequently helps you catch your errors more quickly.
:::


# Book exercises {.unnumbered}

## 8.2 Young Americans, Part I {.unnumbered}



## 8.8 Legalization of marijuana, Part I {.unnumbered}

[Additional instructions:]{style="color:green"}

* [(b): Calculate the CI both using the formula and using the appropriate R statistical test.]{style="color:green"} 
* [Add parts (e) & (f) as instructed below.]{style="color:green"}

### (a) {.unnumbered}



### (b) {.unnumbered}



### (c) {.unnumbered}



### (d) {.unnumbered}



### (e) {.unnumbered}

[__Test whether the proportion of US residents who think marijuana should be made legal is different than 0.586. Do the test using both the formulas and running it in R (without a continuity correction).__]{style="color:green"}


### (f) {.unnumbered}

[__Are the results from CI and hypothesis test consistent? Why or why not?__]{style="color:green"}


## 8.10 Legalize Marijuana, Part II {.unnumbered} 


 

## 8.14 2010 Healthcare Law {.unnumbered}



## 8.24 Prenatal vitamins and Autism {.unnumbered}

[Additional instructions:]{style="color:green"}

* [(b): Do the hypothesis test both using the formula and using the appropriate R statistical test.]{style="color:green"}
* [Add part (d) as instructed below.]{style="color:green"}

### (a) {.unnumbered}


### (b) {.unnumbered}


### (c) {.unnumbered}


### (d) {.unnumbered}

[__Calculate and interpret the 95% confidence interval for the difference in proportions using the formula. Is it consistent with CI from the R output of the hypothesis test? __]{style="color:green"}




## 8.26 An apple a day keeps the doctor away {.unnumbered}




## 8.28 True or false, Part II {.unnumbered}




## 8.32 Diabetes and unemployment {.unnumbered}


### (a) {.unnumbered}

### (b) {.unnumbered}

### (c) {.unnumbered}

[__In addition to answering the question in (c), run the 2 proportions test in R and calculated the "z" test statistic and p-value using the normal distribution based on the $\chi^2$ output in R's test.__]{style="color:green"}


### (d) extra part {.unnumbered}

[__Run the test as a $\chi^2$ as well, and compare your results to those in (c).__]{style="color:green"}



## 8.34 Coffee and Depression {.unnumbered}

* [__Do not create a dataset and run the test in R. Use just the information given in the problem.__]{style="color:green"}
* [__For (e), calculate the p-value "directly" (not using $\chi^2$ test command in R). Also comment on whether you think the sample size condition would be met without computing the expected cell counts.__]{style="color:green"}


## 8.38 (a) & (extra) Salt intake and CVD {.unnumbered}

Do not do parts (b)-(c) in the book

### (a) {.unnumbered}

* [__You can use the expected cell counts from R's chi-squared test (you do not need to compute them using the formula).__]{style="color:green"} 
* [__Comment on whether the sample size condition is met or not for these data.__]{style="color:green"}



### (extra) {.unnumbered}

[__Run a Fisher's Exact test. Include the hypotheses and a conclusion in the context of the problem.__]{style="color:green"}

# PSS

## Power and Sample size: Auto exhaust and lead exposure revisited

### Power

In exercise 5.12 in Homework 6, we tested whether police officers appear to have been exposed to a higher concentration of lead than 35. Calculate the power for the hypothesis test and include an interpretation of the power in the context of the research question. Was it sufficiently powered? 



### Sample size

For the same test, what sample size would be needed for 80% power? Would it be reasonable to conduct the study with these sample sizes? Why or why not? (Hint: think about the assumptions of our distributions when using a t-test)


### Effect size

Suppose the study has resources to include 30 people. What minimum effect size would they be able to detect with 85% power assuming the same sample mean and standard deviation. Use $\alpha$ = 0.05. 






## PSS3: Legalize Marijuana, Part III. 

### Power

__<font color="green">In exercise 8.8 (e), we tested whether the proportion of US residents who think marijuana should be made legal is different than 0.586. Calculate the power for the hypothesis test and include an interpretation of the power in the context of the research question. Was it sufficiently powered?</font>__ 




### Sample size

__<font color="green">For the same test, what sample size would be needed for 80% power? How about 90% power?</font>__ 




### Effect size
__<font color="green">If we increase the sample size, and keep the power and significance level the same, does the effect size increase or decrease? Why? </font>__ 



