---
title: "Homework 0"
author: "Your name here - update this!!!!"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    toc: true
    toc_float:
      collapsed: false
    theme: lumen
    self-contained: true
    html-math-method: mathjax
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```


**Due 10/3/24**

**This homework does not need to be turned in on Sakai.**

### Purpose

This homework is meant to introduce yourself to me and your peers. In the first class, we will all briefly introduce ourselves, but we don't have enough time in-depth introductions. Thus, I'd like you to share some information with the class over Slack.

### Grading

Grading will be done as a check/no check for turning in your work.

## Questions

### Question 1

Please upload a picture of yourself [to Slack](https://join.slack.com/t/epi525f24/shared_invite/zt-2q9fpa8h3-Yc5U91Ps0MjnemADzTM5Vw). Please follow the below steps to add a picture of yourself in Slack:

1.  Go to the top right corner in Slack and click your profile picture.
2.  Click "Profile."
3.  In the picture of the clip art person, click "Upload Photo" in top right corner.
4.  Upload a picture file of yourself.

### Question 2

Provide a pronunciation of your name: Please follow the below steps to add an audio and written pronunciation of your name in Slack:

1.  Go to the top right corner in Slack and click your profile picture.
2.  Click "Profile."
3.  To the right of your name, click "Edit."
4.  Under "Name Recording," click "Record Audio Clip."
5.  Please say your name once at a normal pace then once slowly. Please listen to my audio for an example.
6.  You may also edit the written pronunciation of your name. This is optional! I realize that doing this is may require a lot of time researching phonetics.

### Question 3

Please complete the [following whenisgood poll](http://whenisgood.net/gqz22ff) so that we can schedule office hours. Please use a unique identifier (does not have to be your name), so that I can make sure each student can attend at least one office hour.

### Question 4

Completion of this question is optional. If you are comfortable sharing your pronouns, please edit your name in Slack to include them. For example, I have changed my name to be "Nicky Wakim (she/her)". If you prefer to not share your pronouns, then I will refer to you using they/them pronouns.

### Question 5

Please post an introduction in the `#random` channel on Slack. You ***do not need*** to include all of the below items, but your introduction ***may*** include information like:

-   Preferred name
-   Pronouns
-   Are you new to Portland?
-   Career interests
-   Hobbies
-   Family, children, and/or fur babies
-   Favorite/recent adventures, restaurants, TV shows, books, podcasts, games, etc.
-   Willingness to join a study group
-   Motivation for taking the course
-   Anticipated Fall trip/activity
-   Any resolutions/vibes/outlooks that you are thinking about as we start the new academic year/quarter

Please feel free to get creative with what you share! You don't need to adhere to this list!

### Question 6

Homework assignments and solutions will be due on a weekly basis. Solutions will be due approximately a week after the assignment was due. There will also be two homework videos/meetings in the quarter. Please look at your calendar, other classes, etc. [Use this form](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURTZOMjlPOTNHRDZPUzNYNDZIN1JRM0ZYTS4u) to rank the days of the week that each of these homeworks parts will be due. Feel free to add any comments. 


### Question 7

Completion of this question is only necessary if you have accommodations. If you have any learning accommodations, please email me about your needs. I should receive a direct email from the Office of Student Access, but it is important that we discuss how accommodations will translate to our class. If you plan to seek accomodations, but do not have the formal document yet, please let me know!

I highly suggest that you make an appointment with a learning specialist through [Student Academic Support Services](https://sakai.ohsu.edu/portal/site/Student_Support)! If you often need more time on a test, struggle to focus in class, or noticed a difference between your learning style and typical styles offered in school, **talk to academic support services and see if you qualify for accommodations!** Most professors should be working towards an inclusive classroom, but this is the best way to insure you get the learning environment you need!
