---
title: "Week 8"
description: "Chi-squared tests and Exam 2"
date: "11/13/2023"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Day 13 

* Chi-squared tests of association and homogeneity
* Fisher's exact test
* Sections 8.3-8.4


### Slides

_Note: the title slide of the recording mistakenly shows Day 17 instead of Day 13. I fixed this in the posted slides._ 

* [html](../slides/Day13_bsta511.qmd)
* [pdf](https://drive.google.com/file/d/1KN51RBvBPJwIoEjIsDPGDwPSNhScmLbP/view?usp=sharing)
* Slides with [notes](https://drive.google.com/file/d/1KICeogpenpwWQ01oePQ7jD_ZQiB4Zxzu/view?usp=sharing)
* [webpage](../slides_md/Day13_bsta511_md.qmd)
* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day13_bsta511_code.qmd), [html](../slides_code/Day13_bsta511_code.qmd)


### Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F23/tree/main/data)

* No datasets for this class


### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

Questions from [HW 7](../homework/HW_7_F23_bsta511.qmd)

* Book #8.28, 8.34, 8.38 (modified; see assignment), 8.32


## Exam 2 (Wednesday)

* Material will cover __Days 7-6__, 
    * which is approximately __Chapters 3.3-3.4, 4, 5.1-5.4__ from the textbook, plus extra material for power & sample size calculations in slides.
* The exam will be in-class and handwritten. Bring a calculator.
* [You will be provided with a normal Z table and a t-table. Make sure you know how to use them for calculating CI's and estimating p-values.]{style="color:green"}
* You may bring one page of notes on an 8.5" x 11" sheet of paper. 
    * You may use both sides. 
    * You may type your notes.
    * You may __not__ use screenshots of the notes or textbook
    * You will be turning in the page of notes with the exam, so please add your name to the sheet. 


### Past exams

* The linked to file includes questions from [past BSTA 511 exams](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F23/Exam_samples/Exam_2_samples_Ch3.3_4_5.1-5.4.pdf) I wrote, which cover the same material as  Exam 2 this quarter. (Requires Sakai login)
* [Answers](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F23/Exam_samples/Exam_2_samples_Ch3.3_4_5.1-5.4_answers.pdf) to past BSTA 511 exams


## Homework

* [HW 7](../homework/HW_7_F23_bsta511.qmd) due on Sat, 11/18
    * Covers Days 12-13
    * For book exercises, make sure to include all steps in a hypothesis test (where applicable) as outlined in the class notes. 
    * Do not forget to include a discussion on whether you think the test (or CI) assumptions have been satisfied. Are there assumptions you need to make in order for them to be satisfied? Whether you believe they are satisfied or not, continue to run the hypothesis test (or CI) as instructed.



## Recordings

* __Pre-recorded__ lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).
    * These can be accessed in Sakai by navigating to the BSTA 511/611 page and clicking on the `Echo Cloud` option in the left-side menu. 
    * This will redirect you to an echo video page with a list of pre-recorded videos.
* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F23/tool/1f70eae0-e36a-4052-9247-69c6917e6b73/). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page.  
