---
title: "Week 6"
description: "Confidence intervals and hypothesis tests for one mean"
date: "10/30/2023"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Day09 

* Confidence intervals for one mean (single-sample)
* Student's t-distribution

### Slides

* [html](../slides/Day09_bsta511.qmd)
* [pdf](https://drive.google.com/file/d/1JTvblZDbEDiS3loc1BeM7QJaxz7dgpQl/view?usp=sharing)
* Slides with [notes](https://drive.google.com/file/d/1JVa-L-Er4vKVEy0q_NbDvR8kYqzL14ww/view?usp=sharing)
* [webpage](../slides_md/Day09_bsta511_md.qmd)
* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day09_bsta511_code.qmd), [html](../slides_code/Day09_bsta511_code.qmd)


### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

* Slide 15: What percent CI was being simulated in this figure?
* Slide 22: Calculate CI
* From HW 5
    * R exercise R1: YRBSS CI for weights
    * Book exercises 4.4, 4.6, 5.6, 5.10


## Day10    

### Part 1

* Hypothesis testing for one mean (single-sample)
* CIs vs. hypothesis tests
* R projects, `here::here()`, and loading data into R from a file
* Running a `t.test` in R 

### Part 2

* Inference for two-sample paired data

### Slides

::: columns
::: {.column width="50%"}

Part 1

* [html](../slides/Day10_part1_bsta511.qmd)
* [pdf](https://drive.google.com/file/d/1JZRggNRHAWanOV_48OY4hFGBnCeQx_7O/view?usp=sharing)
* Slides with [notes](https://drive.google.com/file/d/1JhV-qVNFXV6Lcfy1RUUTSju1EhsyTW3O/view?usp=sharing)
* [webpage](../slides_md/Day10_part1_bsta511_md.qmd)
* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day10_part1_bsta511_code.qmd), [html](../slides_code/Day10_part1_bsta511_code.qmd)
* [Projects in RStudio](../resources/Projects_in_R.html)

:::
::: {.column width="50%"}
Part 2 (Class discussion)

* [html](../slides/Day10_part2_bsta511.qmd)
* [pdf](https://drive.google.com/file/d/1JmKMPfbxTX10qjc7HaRNNKijvX71UesA/view?usp=sharing)
* No slides with notes
* [webpage](../slides_md/Day10_part2_bsta511_md.qmd)
* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day10_part2_bsta511_code.qmd), [html](../slides_code/Day10_part2_bsta511_code.qmd)
:::
:::


### Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F23/tree/main/data)

* [BodyTemperatures.csv](/data/BodyTemperatures.csv)
* [chol213.csv](/data/chol213.csv)

### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

* Part 2 of Day 10
* See specific questions in orange on (most) slides.

## Homework

* [HW 5](../homework/HW_5_F23_bsta511.qmd) due on Sat, 11/4
    * Covers Days 9-10



## Recordings

* __Pre-recorded__ lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).
    * These can be accessed in Sakai by navigating to the BSTA 511/611 page and clicking on the `Echo Cloud` option in the left-side menu. 
    * This will redirect you to an echo video page with a list of pre-recorded videos.
* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F23/tool/1f70eae0-e36a-4052-9247-69c6917e6b73/). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page.  
