---
title: "Week 11"
description: "Exam 3"
date: "12/4/2023"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---

## Monday

* No new material
* Review day
    * I will answer any questions you have
    * I will not be preparing a review
* See link below to past exam questions on material

## Exam 3 (Wednesday)

* Material will cover __Days 12-17__, 
    * which is approximately __Chapters 8, 5.5, 6__ from the textbook, plus extra material for non-parametric tests in slides.
* The exam will be in-class and handwritten. Bring a calculator.
* [You will be provided with a normal Z table,  t-table, and Chi-squared table. Make sure you know how to use them for calculating CI's and estimating p-values.]{style="color:green"}
* You may bring one page of notes on an 8.5" x 11" sheet of paper. 
    * You may use both sides. 
    * You may type your notes.
    * You may __not__ use screenshots of the notes or textbook
    * You will be turning in the page of notes with the exam, so please add your name to the sheet. 


### Samples of past exam questions

* The linked to file includes questions from [past exams]https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F23/Exam_samples/Exam_3_samples_Ch8_5.5_6_nonpar.pdf), which cover the same material as  Exam 3 this quarter. (Requires Sakai login)


<!-- * [Answers]() to past BSTA 511 exams -->



## Exam 3 retakes

* Retake for Exam 3 will be on Fri, Dec 8th, 11 am - 1 pm in RPV 1203.
* I will email you on Thursday 12/7 what your grade on Exam 3 is as well as your overall class grade without a retake. 


## Recordings

* __Pre-recorded__ lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).
    * These can be accessed in Sakai by navigating to the BSTA 511/611 page and clicking on the `Echo Cloud` option in the left-side menu. 
    * This will redirect you to an echo video page with a list of pre-recorded videos.
* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F23/tool/1f70eae0-e36a-4052-9247-69c6917e6b73/). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page.  
