---
title: "Week 7"
description: "Inference for difference in means, one proportion, and difference in proportions, and power"
date: "11/6/2023"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Day11 

* Inference for difference in means from two independent sample (2-sample t-test)
* Power and sample size calculations

:::{.callout-note}
Day 11 is the last day of new material for Exam 2, which will cover the material from Days 7-11.
:::


### Slides

* [html](../slides/Day11_bsta511.qmd) 
    * final version & all videos posted
* [pdf](https://drive.google.com/file/d/1JxY80AIWcVMPf9TTsNwGK9msGzLVaSvy/view?usp=sharing)
* Slides with [notes](https://drive.google.com/file/d/1cOxfjLuZ5NwU-_zxzQHnJxz0ZCryuCSC/view?usp=sharing)
    * No extra notes for part 3
* [webpage](../slides_md/Day11_bsta511_md.qmd)
* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day11_bsta511_code.qmd), [html](../slides_code/Day11_bsta511_code.qmd)


### Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F23/tree/main/data)

* [CaffeineTaps.csv](/data/CaffeineTaps.csv)


### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

_Questions are all from HW 6_

* Book 5.26 a-b (HW includes part (c) as well)
* R1: DDS expenditures by ethnicity
* PSS1: Book 4.22 - Power & sample size T/F questions
* PSS2: Power & sample size calculations


## Day12    

* Inference for proportions
    * CIs vs. hypothesis tests
    * One proportion from one sample
    * Difference in proportions from two independent samples

### Slides

* [html](../slides/Day12_bsta511.qmd) 
* [pdf](https://drive.google.com/file/d/1JzVBZQMGhakUXcncpbVNKjrUu0bHG6vS/view?usp=sharing)
* Slides with [notes](https://drive.google.com/file/d/1K1Fiil_kxFZczRvTM9I8R5A7VjNzO5C9/view?usp=sharing)
* [webpage](../slides_md/Day12_bsta511_md.qmd)
* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day12_bsta511_code.qmd), [html](../slides_code/Day12_bsta511_code.qmd) 



### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

_Questions are all from [HW 7](../homework/HW_7_F23_bsta511.qmd)_

* Book 8.2, 8.14, 8.24 (plus extra (d))
* PSS1: Legalize Marijuana, Part III


## Homework

* [HW 6](../homework/HW_6_F23_bsta511.qmd) due on Sat, 11/11
    * Covers Day 11
    * *Updated 11/6/23: moved Day 12 questions to HW 7*
    * For book exercises, make sure to include all steps in a hypothesis test (where applicable) as outlined in the class notes. 
    * Do not forget to include a discussion on whether you think the test (or CI) assumptions have been satisfied. Are there assumptions you need to make in order for them to be satisfied? Whether you believe they are satisfied or not, continue to run the hypothesis test (or CI) as instructed.



## Recordings

* __Pre-recorded__ lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).
    * These can be accessed in Sakai by navigating to the BSTA 511/611 page and clicking on the `Echo Cloud` option in the left-side menu. 
    * This will redirect you to an echo video page with a list of pre-recorded videos.
* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F23/tool/1f70eae0-e36a-4052-9247-69c6917e6b73/). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page.  
