---
title: "Week 5"
description: "Variability in estimates and Exam 1"
date: "10/23/2023"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Day08 

* Variability in estimates: Section 4.1


### Slides

* [html](../slides/Day08_bsta511.qmd)
* [pdf](https://drive.google.com/file/d/1JH2gdJ9IIyiYCGkziz4kJGWdVc-xCot1/view?usp=sharing)
* Slides with [notes](https://drive.google.com/file/d/1JIc_UBW-B32FGhSJPU8aqnaoB6GcYfZO/view?usp=sharing)
* [webpage](../slides_md/Day08_bsta511_md.qmd)
* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day08_bsta511_code.qmd), [html](../slides_code/Day08_bsta511_code.qmd)


### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

* Slide 21: match figures to distribution (Sampling high schoolers' weights)
* Problems from Homework 4:
    * R1: Youth weights (YRBSS)
    * Book exercise: 4.2
    * Non-book exercise: Ethan Allen


## Exam 1 (Wednesday)

* Material will cover __Days 1-6__, 
    * which is approximately __Chapters 1, 2, 3.1-3.2__ from the textbook.
* The exam will be in-class and handwritten. Bring a calculator.
* You may bring one page of notes on an 8.5" x 11" sheet of paper. 
    * You may use both sides. 
    * You may type your notes.
    * You may __not__ use screenshots of the notes or textbook
    * You will be turning in the page of notes with the exam, so please add your name to the sheet. 


### Past exams

* The linked to file includes questions from [past BSTA 511 exams](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F23/Exam_samples/Exam_1_samples_Ch1-Ch3.pdf) I wrote, which cover the same material as  Exam 1 this quarter. (Requires Sakai login)
* [Answers](https://sakai.ohsu.edu/access/content/group/BSTA-511-1-AA-F23/Exam_samples/Exam_1_samples_Ch1-Ch3.2%20answers.pdf) to past BSTA 511 exams

## Homework

* [HW 4](../homework/HW_4_F23_bsta511.qmd) due on Sat, 10/28
    * Covers Days 7-8


## Recordings

* __Pre-recorded__ lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).
    * These can be accessed in Sakai by navigating to the BSTA 511/611 page and clicking on the `Echo Cloud` option in the left-side menu. 
    * This will redirect you to an echo video page with a list of pre-recorded videos.
* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F23/tool/1f70eae0-e36a-4052-9247-69c6917e6b73/). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page.  
