{
  "hash": "1bd28a4dc6ebd5ed96e5dd557ed20de0",
  "result": {
    "markdown": "---\ntitle: \"Lesson 2: Intro to data & numerical summaries\"\nsubtitle: \"TB sections 1.2, 1.4\"\nauthor: \"Meike Niederhausen and Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#3070BF\"\ndate: \"10/2/2024\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 2 Slides\n    html-math-method: mathjax\n    highlight-style: arrow\nexecute:\n  echo: true\n  freeze: auto\n---\n\n\n\n\n# Learning Objectives\n\n1.  Define observations and variables, and recognize them in a data frame.\n2.  Define four variable types in data.\n3.  Define and calculate measures of center (including mean and median).\n4.  Define and calculate measures of spread (including standard deviation and interquartile range).\n\n## Where are we?\n\n![](../img_slides/course_map.png){fig-align=\"center\"}\n\n# Learning Objectives\n\n::: lob\n1.  Define observations and variables, and recognize them in a data frame.\n:::\n\n2.  Define four variable types in data.\n3.  Define and calculate measures of center (including mean and median).\n4.  Define and calculate measures of spread (including standard deviation and interquartile range).\n\n## Intro to Data\n\n![[Artwork by \\@allison_horst](https://allisonhorst.com/r-packages-functions)](../img_slides/horst_data_cowboy.png){fig-align=\"center\"}\n\n## Example: the frog study[^1]\n\n[^1]: From *Introductory Statistics for the Life and Biomedical Sciences*\n\nIn evolutionary biology, parental investment refers to the amount of time, energy, or other resources devoted towards raising offspring.\n\n \n\nWe will be working with the `frog` dataset, which originates from a 2013 study[^2] about maternal investment in a frog species. Reproduction is a costly process for female frogs, necessitating a trade-off between individual egg size and total number of eggs produced.\n\n[^2]: Chen, W., et al. Maternal investment increases with altitude in a frog on the Tibetan Plateau. Journal of evolutionary biology 26.12 (2013): 2710-2715.\n\n    ## \n\n \n\nResearchers were interested in investigating how maternal investment varies with altitude. They collected measurements on egg clutches found at breeding ponds across 11 study sites; for 5 sites, the body size of individual female frogs was also recorded.\n\n \n\n \n\n## Poll Everywhere Question 1\n\n## Four rows from frog data frame\n\n\\captionsetup[table]{labelformat=empty}\n\n\n::: {.cell}\n\n:::\n\n\n|     | altitude | latitude | egg.size | clutch.size | clutch.volume | body.size |\n|-----|----------|----------|----------|-------------|---------------|-----------|\n| 1   | 3,462.00 | 34.82    | 1.95     | 181.97      | 177.83        | 3.63      |\n| 2   | 3,462.00 | 34.82    | 1.95     | 269.15      | 257.04        | 3.63      |\n| 3   | 3,462.00 | 34.82    | 1.95     | 158.49      | 151.36        | 3.72      |\n| 150 | 2,597.00 | 34.05    | 2.24     | 537.03      | 776.25        | NA        |\n\n## Four rows from frog data frame\n\n\\captionsetup[table]{labelformat=empty}\n\n\n::: {.cell}\n\n:::\n\n\n|     | altitude | latitude | egg.size | clutch.size | clutch.volume | body.size |\n|-----|----------|----------|----------|-------------|---------------|-----------|\n| 1   | 3,462.00 | 34.82    | 1.95     | 181.97      | 177.83        | 3.63      |\n| 2   | 3,462.00 | 34.82    | 1.95     | 269.15      | 257.04        | 3.63      |\n| 3   | 3,462.00 | 34.82    | 1.95     | 158.49      | 151.36        | 3.72      |\n| 150 | 2,597.00 | 34.05    | 2.24     | 537.03      | 776.25        | NA        |\n\n \n\n-   Each **row** is an [**observation**]{style=\"color:#BF396F;\"}\n-   Each **column** is a [**variable**]{style=\"color:#459B99;\"}\n-   All the [**observations**]{style=\"color:#BF396F;\"} and [**variables**]{style=\"color:#459B99;\"} together make a [**data frame**]{style=\"color:#8043F3;\"} (sometimes called data matrix)\n\n \n\n-   **Missing values:** `NA` means the measured value for body size in clutch #150 is missing\n\n## Frog study: variables and their descriptions\n\n-   [**Variables**]{style=\"color:#459B99;\"} are recorded characteristics for each [**observation**]{style=\"color:#BF396F;\"}\n\n| **Variable**    | **Description**                                      |\n|-----------------|------------------------------------------------------|\n| `altitude`      | Altitude of the study site in meters above sea level |\n| `latitude`      | Latitude of the study site measured in degrees       |\n| `egg.size`      | Average diameter of an individual egg to the 0.01 mm |\n| `clutch.size`   | Estimated number of eggs in clutch                   |\n| `clutch.volume` | Volume of egg clutch in mm³                          |\n| `body.size`     | Length of egg-laying frog in cm                      |\n\n# Learning Objectives\n\n1.  Define observations and variables, and recognize them in a data frame.\n\n::: lob\n2.  Define four variable types in data.\n:::\n\n3.  Define and calculate measures of center (including mean and median).\n4.  Define and calculate measures of spread (including standard deviation and interquartile range).\n\n## Types of variables (1/2)\n\n::: columns\n::: column\n::: orange\n::: orange-ttl\nNumerical variables\n:::\n\n::: orange-cont\n**Numerical variables** take on numerical values, such that numerical operations (sums, differences, etc.) are reasonable.\n\n-   Discrete: only take on integer values (e.g., \\# of family members)\n\n-   Continuous: can take on any value within a specified range (e.g., height)\n:::\n:::\n:::\n\n::: column\n::: pink\n::: pink-ttl\nCategorical variables\n:::\n\n::: pink-cont\n**Categorical variables** take on values that are names or labels; the possible values are called the variable's *levels*.\n\n-   Ordinal: exists some natural ordering of levels (e.g., level of education)\n-   Nominal: no natural ordering of levels (e.g., gender identity)\n:::\n:::\n:::\n:::\n\n## Types of variables (2/2)\n\n![](../img_slides/variableTypes.png)\n\n## Poll Everywhere Question 2\n\n## Poll Everywhere Question 3\n\n## Variable (column) types in `R`\n\n-   We have not done much with `R` yet, but I want this to serve as a reference for you!\n-   Variable types (as we speak them) are translated by `R` a little differently\n-   Below is the mapping of `R` types to variable types\n\n| R type            | variable type | description                                       |\n|------------------------|------------------------|------------------------|\n| integer           | discrete      | integer-valued numbers                            |\n| double or numeric | continuous    | numbers that are decimals                         |\n| factor            | categorical   | categorical variables stored with levels (groups) |\n| character         | categorical   | text, \"strings\"                                   |\n| logical           | categorical   | boolean (TRUE, FALSE)                             |\n\n## Exploring data initially\n\n-   Techniques for exploring and summarizing data **differ** for [**numerical**]{style=\"color:#E75B5C;\"} versus [**categorical**]{style=\"color:#EF85B3;\"} variables.\n\n \n\n-   Numerical and graphical summaries are useful for examining variables one at a time\n    -   Can also be used for exploring the relationships between variables\n    -   *Numerical* summaries are not just for [**numerical**]{style=\"color:#E75B5C;\"} variables (certain ones are used for [**categorical**]{style=\"color:#EF85B3;\"} variables)\n\n \n\n-   Let's start looking into ways to summarize and explore [**numerical**]{style=\"color:#E75B5C;\"} data!\n\n    -   We will come back to [**categorical**]{style=\"color:#EF85B3;\"} variables another day\n\n# Learning Objectives\n\n1.  Define observations and variables, and recognize them in a data frame.\n2.  Define four variable types in data.\n\n::: lob\n3.  Define and calculate measures of center (including mean and median).\n:::\n\n4.  Define and calculate measures of spread (including standard deviation and interquartile range).\n\n## \n\n::: blue\n::: blue-ttl\nWarning!\n:::\n\n::: blue-cont\nI decided to keep some `R` code in these slides. It's going to be a little confusing now, but I thought it would be a worthwhile reference as soon as we get through R basics\n:::\n:::\n\n## Measures of center: [mean]{style=\"color:#5BAFF8;\"}\n\n::: blue\n::: blue-ttl\nSample mean\n:::\n\n::: blue-cont\nthe average value of observations\n\n$$\\overline{x} = \\frac{x_1+x_2+\\cdots+x_n}{n} = \\sum_{i=1}^{n}\\frac{x_i}{n}$$\n\nwhere $x_1, x_2, \\ldots, x_n$ represent the $n$ observed values in a sample\n:::\n:::\n\n**Example**: What is the mean clutch volume in the `frog` dataset?\n\n$$\\overline{x} = \\sum_{i=1}^{431}\\frac{x_i}{431}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 882.474\n```\n:::\n:::\n\n\n**Answer:** the mean clutch volume is 882.5 $\\text{mm}^3$.\n\n## Measures of center: [median]{style=\"color:#EF85B3;\"}\n\n::: pink\n::: pink-ttl\nMedian\n:::\n\n::: pink-cont\n-   The middle value of the observations in a sample\n\n-   The median is the 50th percentile, meaning\n\n    -   50% of observations lie below the median\n    -   50% of observations lie above the median\n:::\n:::\n\n-   If the number of observations is\n    -   Odd: the median is the middle observed value\n    -   Even: the median is the average of the two middle observed values\n-   We can calculate the median clutch volume\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedian(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 831.7638\n```\n:::\n:::\n\n\n## Measures of center: [mean]{style=\"color:#5BAFF8;\"} vs. [median]{style=\"color:#EF85B3;\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Intro_data_num_summaries_files/figure-revealjs/unnamed-chunk-6-1.png){width=1344}\n:::\n:::\n\n\n-   Mean values will be pulled towards extreme values\n\n# Learning Objectives\n\n1.  Define observations and variables, and recognize them in a data frame.\n2.  Define four variable types in data.\n3.  Define and calculate measures of center (including mean and median).\n\n::: lob\n4.  Define and calculate measures of spread (including standard deviation and interquartile range).\n:::\n\n## Measures of spread: [standard deviation (SD)]{style=\"color:#E75B5C;\"} (1/3)\n\n::: orange\n::: orange-ttl\nStandard deviation (SD)\n:::\n\n::: orange-cont\n(Approximately) the average distance between a typical observation and the mean\n\n-   An observation's **deviation** is the distance between its value $x$ and the sample mean $\\overline{x}$: deviation = $x - \\overline{x}$\n:::\n:::\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Intro_data_num_summaries_files/figure-revealjs/unnamed-chunk-7-1.png){width=1344}\n:::\n:::\n\n\n## Measures of spread: [SD]{style=\"color:#E75B5C;\"} (2/3)\n\n-   The **sample variance** $s^2$ is the sum of squared deviations divided by the number of observations minus 1. $$s^2 = \\frac{(x_1 - \\overline{x})^2+(x_2 - \\overline{x})^2+\\cdots+(x_n - \\overline{x})^2}{n-1} = \\sum_{i=1}^{n}\\frac{(x_i - \\overline{x})^2}{n-1}$$ where $x_1, x_2, \\dots, x_n$ represent the $n$ observed values.\n\n \n\n-   The [**standard deviation**]{style=\"color:#E75B5C;\"} $s$ (or $sd$) is the square root of the variance. $$s = \\sqrt{\\frac{({x_1 - \\overline{x})}^{2}+({x_2 - \\overline{x})}^{2}+\\cdots+({x_n - \\overline{x})}^{2}}{n-1}} = \\sqrt{\\sum_{i=1}^{n}\\frac{(x_i - \\overline{x})^2}{n-1}}$$\n\n## Measures of spread: [SD]{style=\"color:#E75B5C;\"} (3/3)\n\nLet's calculate the sample standard deviation for the clutch volume:\n\n \n\n$s = \\sqrt{\\sum_{i=1}^{n}\\frac{(x_i - \\overline{x})^2}{n-1}} =$\n\n-   Doing this by hand would be really time consuming!\n-   `R` can easily do this for us!\n\n \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 882.474\n```\n:::\n\n```{.r .cell-code}\nsd(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 379.0527\n```\n:::\n:::\n\n\n \n\n**Answer:** The standard deviation of the clutch volume is 379.05 mm^3^\n\n## Empirical Rule: one way to think about the SD\n\n::: columns\n::: {.column width=\"45%\"}\nFor symmetric bell-shaped data, about\n\n-   68% of the data are within 1 SD of the mean\n-   95% of the data are within 2 SD's of the mean\n-   99.7% of the data are within 3 SD's of the mean\n\nThese percentages are based off of percentages of a true normal distribution.\n:::\n\n::: {.column width=\"55%\"}\n![<https://statistics-made-easy.com/empirical-rule/>](../img_slides/empirical-rule.png){fig-align=\"center\" width=\"1000\"}\n:::\n:::\n\n## Measures of spread: [interquartile range (IQR)]{style=\"color:#459B99;\"} (1/2)\n\nThe $p^{th}$ percentile is the observation such that $p\\%$ of the remaining observations fall below this observation.\n\n-   The *first quartile* $Q_1$ is the $25^{th}$ percentile.\n-   The *second quartile* $Q_2$, i.e., the median, is the $50^{th}$ percentile.\n-   The *third quartile* $Q_3$ is the $75^{th}$ percentile.\n\n::: green2\n::: green2-ttl\nInterquartile range (IQR)\n:::\n\n::: green2-cont\nThe distance between the third and first quartiles. $$IQR = Q_3 - Q_1$$\n\n-   IQR is the width of the *middle half* of the data\n:::\n:::\n\n## Measures of spread: [IQR]{style=\"color:#459B99;\"} (2/2)\n\n[**5 number summary**]{style=\"color:#8043F3\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  151.4   609.6   831.8   882.5  1096.5  2630.3 \n```\n:::\n:::\n\n\n$$IQR = Q_3 - Q_1 = 1096.5 - 609.6 = 486.9$$\n\n \n\n::: columns\n::: {.column width=\"38%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_Intro_data_num_summaries_files/figure-revealjs/unnamed-chunk-10-1.png){width=576}\n:::\n:::\n\n:::\n\n::: {.column width=\"62%\"}\nWhat is the IQR of the sepal widths?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(frog$clutch.volume, c(.25, .75))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      25%       75% \n 609.5773 1096.4782 \n```\n:::\n\n```{.r .cell-code}\ndiff(quantile(frog$clutch.volume, c(.25, .75)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     75% \n486.9009 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nIQR(frog$clutch.volume)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 486.9009\n```\n:::\n:::\n\n:::\n:::\n\n## Robust estimates\n\nSummary statistics are called [**robust estimates**]{style=\"color:#C83532\"} if extreme observations have little effect on their values\n\n| Estimate           | Robust? |\n|--------------------|---------|\n| Sample mean        | ❌      |\n| Median             | ✅      |\n| Standard deviation | ❌      |\n| IQR                | ✅      |\n\n-   For samples with many extreme values, the median and IQR might provide a more accurate sense of the center and spread\n\n## Poll Everywhere Question 4\n",
    "supporting": [
      "02_Intro_data_num_summaries_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}