{
  "hash": "528905daf0009edf3fbab9631a51cf2a",
  "result": {
    "markdown": "---\ntitle: \"Lesson 19: Nonparametric tests\"\nsubtitle: \"Pagona TB, Chapter 13\"\nauthor: \"Meike Niederhausen and Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#3070BF\"\ndate: \"12/5/2024\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 19 Slides\n    html-math-method: mathjax\n    highlight-style: arrow\nexecute:\n  echo: true\n  freeze: auto\n---\n\n\n\n\n# Learning Objectives\n\n## MoRitz's tip: write \"nice\" R code {visibility=\"hidden\"}\n\nCheck out the tidyverse style guide: https://style.tidyverse.org/index.html\n\nEspecially, Chapter 4: [Pipes](https://style.tidyverse.org/pipes.html#pipes) and Chapter 5: [ggplot2](https://style.tidyverse.org/ggplot2.html#ggplot2)\n\n# Goals for today (Supplemental material)\n\n-   Why us a nonparametric approach?\n\n-   What the following tests are & when to use them\n\n-   **Sign test**\n\n    -   for paired data or single samples\n\n-   **(Wilcoxon) sign-rank test**\n\n    -   for paired data or single samples\n    -   accounts for sizes of differences\n\n-   **Wilcoxon Rank-sum test**\n\n    -   for two independent samples\n    -   a.k.a **Mann-Whitney U test**\n\n-   **Kruskal-Wallis test**\n\n    -   nonparametric ANOVA test\n\n-   How to use R for each test & interpret the results\n\n## Additional resource\n\n-   Chapter 13: Nonparametric tests of Pagano's *Principles of Biostatistics*, 2022 edition\n-   Can download chapter from OHSU library eBook at <https://ebookcentral.proquest.com/lib/ohsu/detail.action?docID=6950388&pq-origsite=primo>\n\n# Nonparametric tests\n\n## Background: parametric vs nonparametric\n\n-   Parametric vs. nonparametric\n    -   Basically saying: assuming a distribution for our data vs. not assuming a distribution for our data\n-   In all of our inference so far, we have assumed the population (that the data come from) has a specific distribution\n    -   Normal distribution, T-distribution, Chi-squared distribution, F-distribution\n-   Each of those distribution can be **parameterized** from certain population parameters\n    -   For example: Normal distribution is completely described (parameterized) by two parameters: $\\mu$ and $\\sigma$\n-   Our inference and analysis was all based in the assumed distribution\n    -   But remember: we have specific assumptions that we need to check in order to use those distributions!\n-   **Nonparametric** procedures\n    -   Make fewer assumptions about the structure of the underlying population from which the samples were collected\n    -   Work well when distributional assumptions are in doubt.\n\n## The good and the bad about nonparametric tests\n\n::::: columns\n::: column\n**Good**\n\n-   Fewer assumptions\n-   Tests are based on ranks\n    -   Therefore outliers have no greater influence than non-outliers.\n    -   Since tests are based on ranks we can apply these procedures to ordinal data\n        -   (where means and standard deviations are not meaningful).\n:::\n\n::: column\n**Drawbacks**\n\n-   Less powerful than parametric tests (due to loss of information when data are converted to ranks)\n-   While the test is easy, it may require substantial (computer) work to develop a confidence interval \\[by \"inverting\" the test\\].\n-   Theory was developed for continuous data (where ties are not possible); if population or data contain many ties, then a correction to the procedures must be implemented.\n-   Some procedures have \"large\" and \"small\" sample versions; the small sample versions require special tables or a computer.\n:::\n:::::\n\n## Parametric and nonparametric tests\n\n| Type of data | Parametric test | Nonparametric test |\n|--------------------------|-----------------------|-----------------------|\n| Single sample, numeric | Single mean hypothesis test or t-test (Lesson 11) | Wilcoxon signed-rank test |\n| Paired sample, numeric | Mean difference (paired) hypothesis test or t-test (Lesson 12) | Sign test or Wilcoxon signed-rank test |\n| Two independent sample, numeric | Difference in means hypothesis test or two sample t-test (Lesson 13) | Wilcoxon rank-sum test or Mann-Whitney U test |\n| Single sample, binary | Single proportion hypothesis test (Lesson 15) |  |\n| Two independent sample, binary | Difference in proportions hypothesis test (Lesson 15) |  |\n| Two or more independent samples, binary | Chi-squared test (Lesson 16) | Fisher's Exact test |\n| Two or more independent samples, numeric | ANOVA test or F-test (Lesson 17) | Kruskal-Wallis test |\n\n## We still follow the general hypothesis test process\n\n1.  Check the [**assumptions**]{style=\"color:#70AD47\"}\n\n    - We will not meet the parametric assumptions!\n    - There are some assumptions for the nonparametric tests\n\n2.  Set the [**level of significance**]{style=\"color:#70AD47\"} $\\alpha$\n\n3.  Specify the [**null**]{style=\"color:#70AD47\"} ( $H_0$ ) and [**alternative**]{style=\"color:#70AD47\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#70AD47\"}\n\n    -   In symbols\n    -   In words\n    -   Alternative: one- or two-sided?\n\n4.  Calculate the [**test statistic**]{style=\"color:#70AD47\"} and [**p-value**]{style=\"color:#70AD47\"} for Fisher Exact test in R\n\n    -   We will not discuss the test statistic's equation\n\n5.  Write a [**conclusion**]{style=\"color:#70AD47\"} to the hypothesis test\n\n    -   Do we reject or fail to reject $H_0$?\n    -   Write a conclusion in the context of the problem\n\n# (Wilcoxon) Signed-rank test\n\nFor paired data or single samples;\\\naccounts for sizes of differences\n\n## (Wilcoxon) Signed-rank test\n\n-   The (Wilcoxon) signed-rank test is used for\n    -   Paired samples (i.e., a single set of differences)\n    -   One-sample comparison against a specified value\n-   If we want to see if data are symmetric (centered) around a certain value\n    - For paired data, we may want to see if the data are symmetric around 0 to determine a difference \n    - For one sample, we may have an idea of a median value that our data may follow\n-   Think back to the parametric parallel of these! \n    - If we apply the body temperature example to this: We would check if the data were symmetric around 98.6\n- Data do NOT need to be approximately normal\n\n## Example: Intraocular pressure of glaucoma patients\n\n::::: columns\n::: column\n-   Intraocular pressure of glaucoma patients is often reduced by treatment with adrenaline.\n-   A **new synthetic drug** is being considered, but it is more expensive than the **current adrenaline alternative**.\n-   7 glaucoma patients were treated with both drugs:\n    -   one eye with adrenaline and\n    -   the other with the synthetic drug\n-   **Reduction in pressure** was recorded in each eye after following treatment (larger numbers indicate greater reduction)\n:::\n\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"eajzderdhx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#eajzderdhx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#eajzderdhx thead, #eajzderdhx tbody, #eajzderdhx tfoot, #eajzderdhx tr, #eajzderdhx td, #eajzderdhx th {\n  border-style: none;\n}\n\n#eajzderdhx p {\n  margin: 0;\n  padding: 0;\n}\n\n#eajzderdhx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#eajzderdhx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#eajzderdhx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#eajzderdhx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#eajzderdhx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#eajzderdhx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#eajzderdhx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#eajzderdhx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#eajzderdhx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#eajzderdhx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#eajzderdhx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#eajzderdhx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#eajzderdhx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#eajzderdhx .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#eajzderdhx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eajzderdhx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#eajzderdhx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#eajzderdhx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#eajzderdhx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eajzderdhx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#eajzderdhx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eajzderdhx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#eajzderdhx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eajzderdhx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eajzderdhx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eajzderdhx .gt_left {\n  text-align: left;\n}\n\n#eajzderdhx .gt_center {\n  text-align: center;\n}\n\n#eajzderdhx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#eajzderdhx .gt_font_normal {\n  font-weight: normal;\n}\n\n#eajzderdhx .gt_font_bold {\n  font-weight: bold;\n}\n\n#eajzderdhx .gt_font_italic {\n  font-style: italic;\n}\n\n#eajzderdhx .gt_super {\n  font-size: 65%;\n}\n\n#eajzderdhx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#eajzderdhx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#eajzderdhx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#eajzderdhx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#eajzderdhx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#eajzderdhx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#eajzderdhx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#eajzderdhx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#eajzderdhx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Patient\">Patient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Adren\">Adren</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Synth\">Synth</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"d\">d</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sign\">Sign</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.2</td>\n<td headers=\"d\" class=\"gt_row gt_right\">-0.3</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">-</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.6</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.1</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.3</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">1.9</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">5</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.0</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">6</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.8</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.6</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.6</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n-   **d** is the difference in reduction of pressure: **Synth - Adren**\n-   **Sign** is `+` if the difference is positive and `-` if the difference is negative\n:::\n:::::\n\n\n\n## (Wilcoxon) Signed-rank test: Hypotheses\n\n::::::::::: columns\n:::::: column\n::::: blue\n::: blue-ttl\nGeneral wording for hypotheses\n:::\n\n::: blue-cont\n$H_0:$ population is **symmetric around some value** $\\tilde{\\mu}_0$\\\n$H_a:$ population is **not symmetric around some value** $\\tilde{\\mu}_0$\n:::\n:::::\n::::::\n\n:::::: column\n::::: pink\n::: pink-ttl\nHypotheses test for example\n:::\n\n::: pink-cont\n$H_0:$ the population difference in reduction of intraocular pressure in treatment with adrenaline vs. new synthetic drug is **symmetric around** $\\tilde{\\mu}_0 =0$\\\n$H_a:$ the population difference in reduction of intraocular pressure in treatment with adrenaline vs. new synthetic drug is **not symmetric around** $\\tilde{\\mu}_0 =0$\n:::\n:::::\n::::::\n:::::::::::\n\n-   Even if the population has a mean/median equal to $\\tilde{\\mu}_0$, the test may reject the null if the population isn't symmetric, thus only use if the data (differences) are symmetric.\n-   If the population is symmetric\n    -   then the mean and median coincide,\n    -   thus often the null hypothesis is phrased in terms of the median (or median difference) being 0\n    \n## Example: Visualize the differences\n\nVisualize the differences in reduction of pressure $d$ : **Synth - Adren**\n\n::::: columns\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(IOP_table, aes(x = d)) +\n  geom_dotplot() +\n  theme(text = element_text(size = 30))\n```\n\n::: {.cell-output-display}\n![](19_Non_parametric_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n:::\n\n::: column\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(IOP_table, aes(x = d)) +\n  geom_density() +\n  theme(text = element_text(size = 30))\n```\n\n::: {.cell-output-display}\n![](19_Non_parametric_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n:::\n:::::\n\n## Example: Calculate signed ranks\n\n-   Rank the **absolute values** of the differences from smallest to largest\n-   For ties, take the average of the highest and lowest tied ranks\n    -   I.e. if ranks 3-7 are tied, then assign (3+7)/2 = 5 as the rank\n-   Then calculate the **signed ranks** as +/- the rank depending on whether the sign is +/-\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"moppombspv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#moppombspv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#moppombspv thead, #moppombspv tbody, #moppombspv tfoot, #moppombspv tr, #moppombspv td, #moppombspv th {\n  border-style: none;\n}\n\n#moppombspv p {\n  margin: 0;\n  padding: 0;\n}\n\n#moppombspv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#moppombspv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#moppombspv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#moppombspv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#moppombspv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#moppombspv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#moppombspv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#moppombspv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#moppombspv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#moppombspv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#moppombspv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#moppombspv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#moppombspv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#moppombspv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#moppombspv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#moppombspv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#moppombspv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#moppombspv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#moppombspv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#moppombspv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#moppombspv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#moppombspv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#moppombspv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#moppombspv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#moppombspv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#moppombspv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#moppombspv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#moppombspv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#moppombspv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#moppombspv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#moppombspv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#moppombspv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#moppombspv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#moppombspv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#moppombspv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#moppombspv .gt_left {\n  text-align: left;\n}\n\n#moppombspv .gt_center {\n  text-align: center;\n}\n\n#moppombspv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#moppombspv .gt_font_normal {\n  font-weight: normal;\n}\n\n#moppombspv .gt_font_bold {\n  font-weight: bold;\n}\n\n#moppombspv .gt_font_italic {\n  font-style: italic;\n}\n\n#moppombspv .gt_super {\n  font-size: 65%;\n}\n\n#moppombspv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#moppombspv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#moppombspv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#moppombspv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#moppombspv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#moppombspv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#moppombspv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#moppombspv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#moppombspv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Patient\">Patient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Adren\">Adren</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Synth\">Synth</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"d\">d</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sign\">Sign</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rank\">Rank</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Signed_rank\">Signed_rank</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.2</td>\n<td headers=\"d\" class=\"gt_row gt_right\">-0.3</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">-</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">1.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">-1.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.6</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.1</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">4.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.3</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">1.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">1.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">1.9</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">4.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">5</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.0</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">6</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.8</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">3.0</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.6</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.6</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">6.0</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">6.0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## (Wilcoxon) Signed-rank test: Test statistic\n\n- If the null is true:\n    -   The population is symmetric around some point ( $\\tilde{\\mu}_0 = 0$ , typically), and\n    -   The **overall size of the positive ranks should be about the same as the overall size of negative ranks**.\n\n\n-   Note: \n    -   The sum of the ranks (not signed) $1,2,\\dotsc, n$ is always $n(n+1)/2$,\n    -   which can be broken down as the\n        -   sum of the positive ranks ( $T^+$ )\n        -   plus the sum of the negative ranks ( $T^-$ )\n\n- Thus, any of the following can be used as a test statistic and will lead to the same conclusion:\n    -   $T^+$\n    -   $T^-$\n    -   $T^+ - T^-$\n    -   $\\min(T^+,T^−) = T_0$ (our focus)\n\n## Example: calculate sums of signed ranks\n\n::: columns\n::: {.column width=\"50%\"}\n\n-   Sum of the positive ranks\n    -   $T^+$ = 1.5 + 3 + 4.5 + 4.5 + 6 = 19.5\n\n \n\n-   Sum of the negative ranks\n    -   $T^-$ = -1.5\n\n     \n\n-   The sum of the ranks $1,2,\\dotsc, n$ is always $n(n+1)/2$:\n    -   $n(n+1)/2 = 6(7)/2 = 21$\n    -   $T^+ + |T^-| = 19.5 + |-1.5| = 21$\n    \n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"levlcqebae\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#levlcqebae table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#levlcqebae thead, #levlcqebae tbody, #levlcqebae tfoot, #levlcqebae tr, #levlcqebae td, #levlcqebae th {\n  border-style: none;\n}\n\n#levlcqebae p {\n  margin: 0;\n  padding: 0;\n}\n\n#levlcqebae .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#levlcqebae .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#levlcqebae .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#levlcqebae .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#levlcqebae .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#levlcqebae .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#levlcqebae .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#levlcqebae .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#levlcqebae .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#levlcqebae .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#levlcqebae .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#levlcqebae .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#levlcqebae .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#levlcqebae .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#levlcqebae .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#levlcqebae .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#levlcqebae .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#levlcqebae .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#levlcqebae .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#levlcqebae .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#levlcqebae .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#levlcqebae .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#levlcqebae .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#levlcqebae .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#levlcqebae .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#levlcqebae .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#levlcqebae .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#levlcqebae .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#levlcqebae .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#levlcqebae .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#levlcqebae .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#levlcqebae .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#levlcqebae .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#levlcqebae .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#levlcqebae .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#levlcqebae .gt_left {\n  text-align: left;\n}\n\n#levlcqebae .gt_center {\n  text-align: center;\n}\n\n#levlcqebae .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#levlcqebae .gt_font_normal {\n  font-weight: normal;\n}\n\n#levlcqebae .gt_font_bold {\n  font-weight: bold;\n}\n\n#levlcqebae .gt_font_italic {\n  font-style: italic;\n}\n\n#levlcqebae .gt_super {\n  font-size: 65%;\n}\n\n#levlcqebae .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#levlcqebae .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#levlcqebae .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#levlcqebae .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#levlcqebae .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#levlcqebae .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#levlcqebae .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#levlcqebae .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#levlcqebae div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Patient\">Patient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Adren\">Adren</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Synth\">Synth</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"d\">d</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sign\">Sign</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rank\">Rank</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Signed_rank\">Signed_rank</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.2</td>\n<td headers=\"d\" class=\"gt_row gt_right\">-0.3</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">-</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">1.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">-1.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.6</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.1</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">4.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">3.3</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.3</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">1.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">1.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">1.9</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">4.5</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">4.5</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">5</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.9</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.0</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">6</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.4</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.8</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.4</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">3.0</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">3.0</td></tr>\n    <tr><td headers=\"Patient\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Adren\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"Synth\" class=\"gt_row gt_right\">2.6</td>\n<td headers=\"d\" class=\"gt_row gt_right\">0.6</td>\n<td headers=\"Sign\" class=\"gt_row gt_right\">+</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">6.0</td>\n<td headers=\"Signed_rank\" class=\"gt_row gt_right\">6.0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n:::\n\n## (Wilcoxon) Signed-rank test: Exact p-value (fyi)\n\n-   **Exact p-value** is preferable\n    -   This is the default method in R's `wilcox.test()`\n        -   if the samples contain less than 50 finite values\n        -   and **there are no ties**\n            -   *R will automatically use normal approximation method if there are ties*\n-   *We will not be calculating the exact p-value \"by hand.\" We will be using R for this.*\n\n<hr>\n\n<br>\n\n$$p-value = 2 * P(\\min(T^+,T^−) \\leq t)$$\n\n-   $t$ is the smaller of the calculated sums of the positive and negative ranks\n-   To calculate the exact p-value, we need the probability of each possible sum of ranks\n\n## (Wilcoxon) Signed-rank test in R: Glaucoma example\n\n\"Attempt\" with exact p-value & running one sample test with differences\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exact p-value\nwilcox.test(x = IOP$d, \n\t\talternative = c(\"two.sided\"), mu = 0, \n\t\texact = TRUE, correct = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  IOP$d\nV = 19.5, p-value = 0.07314\nalternative hypothesis: true location is not equal to 0\n```\n:::\n:::\n\n\n\n## (Wilcoxon) Signed-rank test: Conclusion\n\nRecall the hypotheses to the (Wilcoxon) Signed-rank test:\n\n$H_0:$ the population difference in reduction of intraocular pressure in treatment with adrenaline vs. new synthetic drug is **symmetric around** $\\tilde{\\mu}_0 =0$\\\n$H_a:$ the population difference in reduction of intraocular pressure in treatment with adrenaline vs. new synthetic drug is **not symmetric around** $\\tilde{\\mu}_0 =0$\n\n-   Significance level: $\\alpha$ = 0.05\n-   p-value = 0.07314\n-   Do we reject or fail to reject $H_0$?\n\n \n\n\n**Conclusion**:\n\nThere is insufficient evidence the differences in reduction in intraocular pressure differs between the synthetic drug and adrenaline are symmetric about 0 (2-sided Wilcoxon signed rank test $p$-value = 0.07314)\n\n\n## (Wilcoxon) Signed-rank test with one sample\n\n-   One can use the (Wilcoxon) Signed-rank test when testing just one sample\n-   Note that we did this when in R: Ran the (Wilcoxon) Signed-rank test using just the differences\n-   For one sample, we can specify the null population median value:\n\n$H_0:$ The population median is $m$\\\n$H_a:$ The population median is NOT $m$\n\n \n\n**Not-so-real example:** Run (Wilcoxon) Signed-rank test for paired data with null $m = 0.7$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(x = IOP$d, mu = 0.7, alternative = \"two.sided\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  IOP$d\nV = 0, p-value = 0.02225\nalternative hypothesis: true location is not equal to 0.7\n```\n:::\n:::\n\n\n\n# Wilcoxon rank-sum test\n\nFor two independent samples\\\na.k.a Mann-Whitney U test\n\n## Wilcoxon rank-sum test\n\n-   The nonparametric alternative to the two-sample $t$-test\n\n    -   used to analyze two samples selected from separate (independent) populations\n\n-   **Also called the Mann-Whitney U test**\n\n-   Unlike the signed-rank test, there is no need to assume symmetry\n\n-   Necessary **condition** is that the two populations being compared\n\n    -   have the same shape (both right skewed, both left skewed, or both symmetric),\n    -   so any noted difference is due to a shift in the median\n\n-   Since they have the same shape, when summarizing the test, we can describe the results in terms of a difference in medians.\n\n**Hypotheses**:\n\n$H_0:$ the two populations have the same median\\\n$H_a:$ the two populations do NOT have the same median\n\n## Example\n\n::: columns\n::: column\nDr. Priya Chaudhary (OHSU) examined the evoked membrane current of dental sensory neurons (in rats) under control conditions and a mixture of capsaicin plus capsazepine (CPZ). [J. Dental Research} 80:1518--23, 2001.](https://journals.sagepub.com/doi/10.1177/00220345010800060801)\n\n \n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"wzftzswpub\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wzftzswpub table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wzftzswpub thead, #wzftzswpub tbody, #wzftzswpub tfoot, #wzftzswpub tr, #wzftzswpub td, #wzftzswpub th {\n  border-style: none;\n}\n\n#wzftzswpub p {\n  margin: 0;\n  padding: 0;\n}\n\n#wzftzswpub .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wzftzswpub .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wzftzswpub .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wzftzswpub .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wzftzswpub .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wzftzswpub .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wzftzswpub .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wzftzswpub .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wzftzswpub .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wzftzswpub .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wzftzswpub .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wzftzswpub .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wzftzswpub .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wzftzswpub .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wzftzswpub .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzftzswpub .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wzftzswpub .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wzftzswpub .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wzftzswpub .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzftzswpub .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wzftzswpub .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzftzswpub .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wzftzswpub .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzftzswpub .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wzftzswpub .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wzftzswpub .gt_left {\n  text-align: left;\n}\n\n#wzftzswpub .gt_center {\n  text-align: center;\n}\n\n#wzftzswpub .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wzftzswpub .gt_font_normal {\n  font-weight: normal;\n}\n\n#wzftzswpub .gt_font_bold {\n  font-weight: bold;\n}\n\n#wzftzswpub .gt_font_italic {\n  font-style: italic;\n}\n\n#wzftzswpub .gt_super {\n  font-size: 65%;\n}\n\n#wzftzswpub .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wzftzswpub .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wzftzswpub .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wzftzswpub .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wzftzswpub .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wzftzswpub .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wzftzswpub .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wzftzswpub .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wzftzswpub div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">median</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Memb_current</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6</td>\n<td headers=\"median\" class=\"gt_row gt_right\">112</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Memb_current</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6</td>\n<td headers=\"median\" class=\"gt_row gt_right\">822</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ymgnszatzz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ymgnszatzz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ymgnszatzz thead, #ymgnszatzz tbody, #ymgnszatzz tfoot, #ymgnszatzz tr, #ymgnszatzz td, #ymgnszatzz th {\n  border-style: none;\n}\n\n#ymgnszatzz p {\n  margin: 0;\n  padding: 0;\n}\n\n#ymgnszatzz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ymgnszatzz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ymgnszatzz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ymgnszatzz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ymgnszatzz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ymgnszatzz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ymgnszatzz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ymgnszatzz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ymgnszatzz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ymgnszatzz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ymgnszatzz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ymgnszatzz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ymgnszatzz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ymgnszatzz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ymgnszatzz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymgnszatzz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ymgnszatzz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ymgnszatzz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ymgnszatzz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymgnszatzz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ymgnszatzz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymgnszatzz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ymgnszatzz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymgnszatzz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ymgnszatzz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ymgnszatzz .gt_left {\n  text-align: left;\n}\n\n#ymgnszatzz .gt_center {\n  text-align: center;\n}\n\n#ymgnszatzz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ymgnszatzz .gt_font_normal {\n  font-weight: normal;\n}\n\n#ymgnszatzz .gt_font_bold {\n  font-weight: bold;\n}\n\n#ymgnszatzz .gt_font_italic {\n  font-style: italic;\n}\n\n#ymgnszatzz .gt_super {\n  font-size: 65%;\n}\n\n#ymgnszatzz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ymgnszatzz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ymgnszatzz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ymgnszatzz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ymgnszatzz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ymgnszatzz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ymgnszatzz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ymgnszatzz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ymgnszatzz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rat_ID\">Rat_ID</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Current\">Current</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">3024</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">2164</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">864</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">780</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">5</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">125</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">6</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">110</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">426</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">8</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">232</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">130</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">10</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">94</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">11</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">75</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">12</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">55</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n:::\n\n## Example: Visualize the data\n\n**Do the independent samples have the same distribution?**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](19_Non_parametric_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Wilcoxon rank-sum test: Calculating test statistic $W$\n\n::: columns\n::: {.column width=\"67%\"}\n1.  Combine the two samples together (keep track of which observations came from each sample).\n\n2.  Rank the full set of $N=n_1 + n_2$ observations.\n\n    -   If ties exist, assign average ranks to tied values (like signed-rank test)\n\n3.  Sum the ranks corresponding to those observations from the smaller sample.\n\n    -   This is a time-saving step; you could also have used the larger sample.\n    -   Call this sum $W$\n\n4.  If $n_1, n_2$ are both less than 10, then use an exact test (can only be done if no ties are present)\n\n    -   Otherwise use the large-sample normal approximation.\n\nIn our example, both groups have equal n; choose either for computing W.\n\n$$W_{CPZ}=1+2+3+6+7+8 = 27$$\n\n$$W_{control}=4+5+9+10+11+12 = 51$$\n\n::: \n\n::: {.column width=\"33%\"}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"pfzflpntqa\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pfzflpntqa table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pfzflpntqa thead, #pfzflpntqa tbody, #pfzflpntqa tfoot, #pfzflpntqa tr, #pfzflpntqa td, #pfzflpntqa th {\n  border-style: none;\n}\n\n#pfzflpntqa p {\n  margin: 0;\n  padding: 0;\n}\n\n#pfzflpntqa .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 37px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pfzflpntqa .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pfzflpntqa .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pfzflpntqa .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pfzflpntqa .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pfzflpntqa .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pfzflpntqa .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pfzflpntqa .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pfzflpntqa .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pfzflpntqa .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pfzflpntqa .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pfzflpntqa .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pfzflpntqa .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pfzflpntqa .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pfzflpntqa .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pfzflpntqa .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pfzflpntqa .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pfzflpntqa .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pfzflpntqa .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pfzflpntqa .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pfzflpntqa .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pfzflpntqa .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pfzflpntqa .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pfzflpntqa .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pfzflpntqa .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pfzflpntqa .gt_left {\n  text-align: left;\n}\n\n#pfzflpntqa .gt_center {\n  text-align: center;\n}\n\n#pfzflpntqa .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pfzflpntqa .gt_font_normal {\n  font-weight: normal;\n}\n\n#pfzflpntqa .gt_font_bold {\n  font-weight: bold;\n}\n\n#pfzflpntqa .gt_font_italic {\n  font-style: italic;\n}\n\n#pfzflpntqa .gt_super {\n  font-size: 65%;\n}\n\n#pfzflpntqa .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pfzflpntqa .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pfzflpntqa .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pfzflpntqa .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pfzflpntqa .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pfzflpntqa .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pfzflpntqa .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pfzflpntqa .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pfzflpntqa div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rat_ID\">Rat_ID</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Current\">Current</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rank\">Rank</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">12</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">55</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">11</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">75</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">10</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">94</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">6</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">110</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">5</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">125</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">5</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">130</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">6</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">8</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">232</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">7</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Capsaicin + CPZ</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">426</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">8</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">780</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">9</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">864</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">10</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">2164</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">11</td></tr>\n    <tr><td headers=\"Rat_ID\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Group\" class=\"gt_row gt_left\">Control</td>\n<td headers=\"Current\" class=\"gt_row gt_right\">3024</td>\n<td headers=\"Rank\" class=\"gt_row gt_right\">12</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n:::\n\n## Wilcoxon rank-sum test: Exact p-value approach\n\n-   **If** $n_1, n_2$ are both less than 10, then use an exact test,\n    -   otherwise use the large-sample normal approximation.\n    -   However, exact method can only be done if **no ties** are present\n-   p-value is the probability of getting a rank sum $W$ as extreme or more extreme than the observed one.\n    -   Multiply the 1-tail probability by 2 for the 2-tailed probability\n\n$$p-value = 2 \\cdot P(W_{CPZ} \\leq 27)$$\n\n-   To calculate $P(W_{CPZ} \\leq 27)$,\n    -   we need to enumerate all possible sets ranks for the sample size,\\\n    -   calculate the sum of ranks for each set of possible ranks,\n    -   and then the probability for each sum (assuming each set of ranks is equally likely).\n\n## Wilcoxon rank-sum test: using R\n\nExact p-value\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(Current ~ Group, \n            data = CPZdata2, \n            alternative = c(\"two.sided\"), mu = 0, \n            exact = TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum exact test\n\ndata:  Current by Group\nW = 6, p-value = 0.06494\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n\n## Wilcoxon rank-sum test: Conclusion\n\nRecall the hypotheses to the Wilcoxon rank-sum test:\n\n$H_0:$ the control and treated populations have the same median\\\n$H_a:$ the control and treated populations do NOT have the same median\n\n-   Significance level: $\\alpha$ = 0.05\n-   p-value = 0.06494\n-   Do we reject or fail to reject $H_0$?\n\n \n\n**Conclusion**:\n\nThere is suggestive but inconclusive evidence that the evoked membrane current of dental sensory neurons (in rats) differs between the control group and the group exposed to a mixture of capsaicin plus capsazepine (2-sided Wilcoxon rank-sum test $p$-value = 0.06494).\n\n# Fisher's Exact Test\n\nUse this if expected cell counts are too small\n\n## Fisher's Exact Test\n\n-   Only necessary when expected counts in one or more cells is less than 5\n-   Given row and column totals fixed, computes exact probability that we observe our data or more extreme data\n-   Consider a general 2 x 2 table:\n\n![](../img_slides/fisher_tab.png){fig-align=\"center\"}\n\n-   The exact probability of observing a table with cells (a, b, c, d) can be computed based on the hypergeometric distribution\n\n$$P(a, b, c, d) = \\dfrac{(a+b)!\\cdot(c+d)!\\cdot(a+c)!\\cdot(b+d)!}{n!\\cdot a!\\cdot b!\\cdot c!\\cdot d!}$$\n\n-   Numerator is fixed and denominator changes\n\n## Some notes on the Fisher's Exact Test\n\n-   This is always a two-sided test\n-   There is no test statistic nor CI\n-   There is no continuity correction since the hypergeometric distribution is discrete\n\n## Recall our example from Lesson 4 and 16\n\n::: lob\n**Question:** Is there an association between age group and hypertension?\n:::\n\n- Let's pretend that we actually had the following numbers\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Table: Contingency table showing hypertension status and age group.\n\n|Age Group | Hypertension| No Hypertension| Total|\n|:---------|------------:|---------------:|-----:|\n|18-39 yrs |            1|              11|    12|\n|40-59 yrs |            4|               9|    13|\n|60+ yrs   |            4|               2|     6|\n|Total     |            9|              22|    31|\n:::\n:::\n\n\n## Fisher's Exact test: Hypertension\n\n::::: columns\n::: column\n1.  Check expected cell counts threshold\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhyp_data2 %>% expected()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Hypertension No_Hypertension\n[1,]     3.483871        8.516129\n[2,]     3.774194        9.225806\n[3,]     1.741935        4.258065\n```\n:::\n:::\n\n\nWe're going to pretend they are less than 5.\n\n2.  $\\alpha = 0.05$\n\n3.  Hypothesis test:\n\n    -   $H_0$ : There is no association between age group and hypertension\n    -   $H_1$ : There is an association between age group and hypertension\n:::\n\n::: column\n4.  Calculate the test statistic and p-value for Chi-squared test in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfisher.test(x = hyp_data2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tFisher's Exact Test for Count Data\n\ndata:  hyp_data2\np-value = 0.04062\nalternative hypothesis: two.sided\n```\n:::\n:::\n\n\n5.  Conclusion to the hypothesis test\n\nWe reject the null hypothesis that age group and hypertension are not associated ($p=0.04062$). There is sufficient evidence that age group and hypertension are associated.\n:::\n:::::\n\n\n# Kruskal-Wallis test\n\nNonparametric ANOVA test\n\n## Kruskal-Wallis test: nonparametric ANOVA test\n\n-   Recall that an ANOVA tests means from more than 2 groups\n-   Conditions for ANOVA include\n    -   Sample sizes in each group group are large (each $n \\ge 30$),\n        -   OR the data are relatively normally distributed in each group\n    -   Variability is \"similar\" in all group groups\n-   If these conditions are in doubt, or if the response is ordinal, then the Kruskal-Wallis test is an alternative.\n\n\\begin{align}\nH_0 &: \\text{pop median}_1 = \\text{pop median}_2 = ... = \\text{pop median}_k\\\\\n\\text{vs. } H_A&: \\text{At least one pair } \\text{pop median}_i \\neq \\text{pop median}_j \\text{ for } i \\neq j\n\\end{align}\n\n-   K-W test is an extension of the (Wilcoxon) rank-sum test to more than 2 groups\n    -   With $k=2$ groups, the K-W test is the same as the rank-sum test\n\n## K-W test statistic: $H$ (fyi)\n\n$$H = \\frac{12}{{N(N + 1)}} \\sum_{i=1}^{k} \\frac{R_i^2}{n_i} - 3(N + 1)$$\n\n-   $k$ is the number of groups,\n-   $n_i$ is the number of observations in group $i$\n-   $N = n_1 + \\ldots + n_k$ is the total number of observations across all groups,\n-   $R_i$ is the sum of ranks for group $i$\n\nThe test statistic $H$ has a Chi-squared distribution with $k-1$ degrees of freedom:\n\n$$H \\sim \\chi^2_{k-1}$$\n\nRanks are calculated similarly to the (Wilcoxon) rank-sum test.\n\n## Ranks for the K-W test\n\n1.  Combine the $k$ samples together (keep track of which observations came from each sample).\n2.  Rank the full set of $N = n_1 + \\ldots + n_k$ observations.\n    -   If ties exist, assign average ranks to the tied values (as with the signed-rank test).\n3.  Then sum the ranks within each of the $k$ groups\n    -   Label the sums of the ranks for each group as $R_1, \\ldots + R_k$.\n\nIf $H_0$ is true, we expect the populations to have the same medians, and thus the ranks to be similar as well.\n\n## Example: Ozone levels by month\n\n-   `airquality` data included in base R - no need to load it\n-   Daily air quality measurements in New York, May to September 1973.\n-   Question: Do ozone levels differ by month?\n\n::: columns\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"ubekjhmgxf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ubekjhmgxf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ubekjhmgxf thead, #ubekjhmgxf tbody, #ubekjhmgxf tfoot, #ubekjhmgxf tr, #ubekjhmgxf td, #ubekjhmgxf th {\n  border-style: none;\n}\n\n#ubekjhmgxf p {\n  margin: 0;\n  padding: 0;\n}\n\n#ubekjhmgxf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 40px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ubekjhmgxf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ubekjhmgxf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ubekjhmgxf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ubekjhmgxf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ubekjhmgxf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ubekjhmgxf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ubekjhmgxf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ubekjhmgxf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ubekjhmgxf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ubekjhmgxf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ubekjhmgxf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ubekjhmgxf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ubekjhmgxf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ubekjhmgxf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubekjhmgxf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ubekjhmgxf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ubekjhmgxf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ubekjhmgxf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubekjhmgxf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ubekjhmgxf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubekjhmgxf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ubekjhmgxf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubekjhmgxf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ubekjhmgxf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ubekjhmgxf .gt_left {\n  text-align: left;\n}\n\n#ubekjhmgxf .gt_center {\n  text-align: center;\n}\n\n#ubekjhmgxf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ubekjhmgxf .gt_font_normal {\n  font-weight: normal;\n}\n\n#ubekjhmgxf .gt_font_bold {\n  font-weight: bold;\n}\n\n#ubekjhmgxf .gt_font_italic {\n  font-style: italic;\n}\n\n#ubekjhmgxf .gt_super {\n  font-size: 65%;\n}\n\n#ubekjhmgxf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ubekjhmgxf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ubekjhmgxf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ubekjhmgxf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ubekjhmgxf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ubekjhmgxf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ubekjhmgxf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ubekjhmgxf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ubekjhmgxf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Month\">Month</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Month\" class=\"gt_row gt_right\">5</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Ozone</td>\n<td headers=\"n\" class=\"gt_row gt_right\">26</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">23.615</td>\n<td headers=\"median\" class=\"gt_row gt_right\">18</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">22.224</td></tr>\n    <tr><td headers=\"Month\" class=\"gt_row gt_right\">6</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Ozone</td>\n<td headers=\"n\" class=\"gt_row gt_right\">9</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">29.444</td>\n<td headers=\"median\" class=\"gt_row gt_right\">23</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">18.208</td></tr>\n    <tr><td headers=\"Month\" class=\"gt_row gt_right\">7</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Ozone</td>\n<td headers=\"n\" class=\"gt_row gt_right\">26</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">59.115</td>\n<td headers=\"median\" class=\"gt_row gt_right\">60</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">31.636</td></tr>\n    <tr><td headers=\"Month\" class=\"gt_row gt_right\">8</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Ozone</td>\n<td headers=\"n\" class=\"gt_row gt_right\">26</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">59.962</td>\n<td headers=\"median\" class=\"gt_row gt_right\">52</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">39.681</td></tr>\n    <tr><td headers=\"Month\" class=\"gt_row gt_right\">9</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Ozone</td>\n<td headers=\"n\" class=\"gt_row gt_right\">29</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">31.448</td>\n<td headers=\"median\" class=\"gt_row gt_right\">23</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">24.142</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n:::\n\n::: column\n\n::: {.cell}\n::: {.cell-output-display}\n![](19_Non_parametric_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n- Does not look like each month has equal variance so we cannot use ANOVA\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax(Oz_mnth$sd) / min(Oz_mnth$sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.179317\n```\n:::\n:::\n\n\n## K-W test in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(Ozone ~ Month, data = airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  Ozone by Month\nKruskal-Wallis chi-squared = 29.267, df = 4, p-value = 6.901e-06\n```\n:::\n:::\n\n\n \n\nThere is sufficient evidence that the median ozone levels are different in at least two months from May - September, 1973 in New York City (p \\< 0.001; Kruskal-Wallis test).\n\n-   (fyi) Since the K-W test is significant, follow-up with pairwise (Wilcoxon) rank-sum tests using a multiple comparison procedure to identify which months have different medians.\n\n\n",
    "supporting": [
      "19_Non_parametric_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}