{
  "hash": "759a464fe06c6b9f777fccf735c7c3b8",
  "result": {
    "markdown": "---\ntitle: \"Day 12: Inference for a single proportion or difference of two (independent) proportions (Sections 8.1-8.2)\"\nauthor: \"Meike Niederhausen and Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#3070BF\"\ndate: \"09/25/2024\"\ncategories: [\"Week 6\"]\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    toc: true\n    toc-depth: 1\n    toc-title: Class Overview\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1600\n    height: 1100\n    footer: Lesson 8 Slides\n    html-math-method: mathjax\n    highlight-style: arrow\nexecute:\n  echo: true\n  freeze: auto\n---\n\n\n\n\n\n## MoRitz's tip of the day: [code folding]{style=\"color:darkorange\"}\n\n::: {style=\"font-size: 90%;\"}\n::: columns\n\n::: {.column width=\"45%\"}\n\n* With code folding we can hide or show the code in the html output by clicking on the `Code` buttons in the html file.\n* Note the `</> Code` button on the top right of the html output.\n\n![](/img_slides/code_folding_html_chunk_show_quarto_511.png){fig-align=\"center\" width=60%}\n![](/img_slides/code_folding_html_chunk_hide_quarto_511.png){fig-align=\"center\" width=60%}\n\n:::\n\n\n::: {.column width=\"55%\"}\n![](/img_slides/code_folding_yaml_quarto_511.png){fig-align=\"center\"}\n\n\n![](/img_slides/code_folding_html_header_quarto_511.png){fig-align=\"center\"}\n\n:::\n:::\n\n:::\n\n::: {style=\"font-size: 70%;\"}\nSee more information at <https://quarto.org/docs/output-formats/html-code.html#folding-code>\n\n:::\n\n\n## Where are we?\n\n::: {style=\"font-size: 90%;\"}\nCI's and hypothesis tests for different scenarios:\n\n$$\\text{point estimate} \\pm z^*(or~t^*)\\cdot SE,~~\\text{test stat} = \\frac{\\text{point estimate}-\\text{null value}}{SE}$$\n\nDay | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE\n--|--|--|--|--|--|--\n10 | 5.1 | Pop mean | $\\mu$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$\n10 | 5.2 | Pop mean of paired diff | $\\mu_d$ or $\\delta$ | Sample mean of paired diff | $\\bar{x}_{d}$  | **$\\frac{s_d}{\\sqrt{n}}$**\n11 | 5.3 | [Diff in pop <br> means]{style=\"color:black\"} | [$\\mu_1-\\mu_2$]{style=\"color:black\"} | [Diff in sample <br> means]{style=\"color:black\"} | [$\\bar{x}_1 - \\bar{x}_2$]{style=\"color:black\"}  | [**$\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}$ or pooled**]{style=\"color:black\"}\n12 | 8.1 | [Pop proportion]{style=\"color:green\"} | [$p$]{style=\"color:green\"} | [Sample prop]{style=\"color:green\"} | [$\\widehat{p}$]{style=\"color:green\"}  | [**???**]{style=\"color:red\"}\n12 | 8.2 | [Diff in pop <br> proportions]{style=\"color:green\"} | [$p_1-p_2$]{style=\"color:green\"} | [Diff in sample <br> proportions]{style=\"color:green\"} | [$\\widehat{p}_1-\\widehat{p}_2$]{style=\"color:green\"} | [**???**]{style=\"color:red\"}\n\n:::\n\n\n\n## Goals for today (Sections 8.1-8.2)\n\n* Statistical inference for a single proportion or the difference of two (independent) proportions\n    1. Sampling distribution for a proportion or difference in proportions\n    \n    1. What are $H_0$ and $H_a$?\n    \n    1. What are the SE's for $\\hat{p}$ and $\\hat{p}_1-\\hat{p}_2$?\n    \n    1. Hypothesis test\n    \n    1. Confidence Interval\n    \n    1. How are the SE's different for a hypothesis test & CI?\n    \n    1. How to run proportions tests in R\n    \n    1. Power & sample size for proportions tests (extra material)\n\n\n\n## Motivating example\n\n::: {style=\"font-size: 90%;\"}\n\n__One proportion__\n\n* A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year. \n    * What is the CI for the proportion?\n    * The study also reported that 36% of noncollege young males had participated in sports betting. Is the proportion for male college students different from 0.36?\n\n__Two proportions__\n\n* There were 214 men in the sample of noncollege young males (36% participated in sports betting in the previous year).\n* Compare the difference in proportions between the college and noncollege young males.\n    * CI & Hypothesis test\n\n:::\n\n::: {style=\"font-size: 75%;\"}\nBarnes GM, Welte JW, Hoffman JH, Tidwell MC. [Comparisons of gambling and alcohol use among college students and noncollege young people in the United States](https://www.tandfonline.com/doi/full/10.1080/07448480903540499?journalCode=vach20). J Am Coll Health. 2010 Mar-Apr;58(5):443-52. doi: 10.1080/07448480903540499. PMID: 20304756; PMCID: PMC4104810.\n\n:::\n\n\n## Steps in a Hypothesis Test\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[null]{style=\"color:darkorange\"}__ ( $H_0$ ) and __[alternative]{style=\"color:darkorange\"}__ ( $H_A$ ) __[hypotheses]{style=\"color:darkorange\"}__\n    1. In symbols\n    1. In words\n    1. Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n    1. Do we reject or fail to reject $H_0$?\n    1. Write a conclusion in the context of the problem\n\n\n## Step 2: Null & Alternative Hypotheses \n\n::: {style=\"font-size: 90%;\"}\nNull and alternative hypotheses in __words__ and in __symbols__.\n\n::: columns\n::: {.column width=\"49%\"}\n__One sample test__\n\n* $H_0$: The population proportion of young male college students that participated in sports betting in the previous year is 0.36.\n\n* $H_A$: The population proportion of young male college students that participated in sports betting in the previous year is not 0.36.\n\n\\begin{align}\nH_0:& p = 0.36\\\\\nH_A:& p \\neq 0.36\\\\\n\\end{align}\n\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"49%\"}\n__Two samples test__\n\n* $H_0$: The difference in population proportions of young male college and noncollege students that participated in sports betting in the previous year is 0.\n\n* $H_A$: The difference in population proportions of young male college and noncollege students that participated in sports betting in the previous year is not 0.\n\n\\begin{align}\nH_0:& p_{coll} - p_{noncoll} = 0\\\\\nH_A:& p_{coll} - p_{noncoll} \\neq 0\\\\\n\\end{align}\n\n:::\n:::\n\n:::\n\n\n## Sampling distribution of $\\hat{p}$ \n\n* $\\hat{p}=\\frac{X}{n}$ where $X$ is the number of \"successes\" and $n$ is the sample size.\n* $X \\sim Bin(n,p)$, where $p$ is the population proportion.\n* For $n$ \"big enough\", the normal distribution can be used to approximate a binomial distribution:\n\n$$Bin(n,p) \\rightarrow N\\Big(\\mu = np, \\sigma = \\sqrt{np(1-p)} \\Big)$$\n\n* Since $\\hat{p}=\\frac{X}{n}$ is a linear transformation of $X$, we have for large n: \n\n$$\\hat{p} \\sim N\\Big(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\Big)$$\n\n* [*How we apply this result to CI's and test statistics is different!!!*]{style=\"color:purple\"}\n\n\n\n## Step 3: Test statistic \n\n::: {style=\"font-size: 85%;\"}\n\nSampling distribution of $\\hat{p}$ if we assume $H_0: p=p_0$ is true:\n\n$$\\hat{p} \\sim N\\Big(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\Big) \n\\sim N\\Big(\n\\mu_{\\hat{p}}=p_0, \\sigma_{\\hat{p}}=\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}\n\\Big)$$\n\n\nTest statistic for a one sample proportion test:\n\n$$\n\\text{test stat} = \\frac{\\text{point estimate}-\\text{null value}}{SE}\n= z_{\\hat{p}} = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}}\n$$\n\n:::\n\n<hr>\n\n::: {style=\"font-size: 90%;\"}\n\n::: columns\n::: {.column width=\"50%\"}\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.   \n<br>\nWhat is the test statistic when testing $H_0: p=0.36$ vs. \n$H_A: p \\neq 0.36$? \n:::\n\n::: {.column width=\"50%\"}\n\n\n\n\n\n\n\n\\begin{align}\nz_{\\hat{p}} &= \\frac{94/269 - 0.36}{\\sqrt{\\frac{0.36\\cdot(1-0.36)}{269}}} \\\\\n& -0.3607455\n\\end{align}\n\n:::\n:::\n\n:::\n\n\n## Step \"3b\": Conditions satisfied?\n\n__Conditions__:\n\n1. Independent observations?\n    * The observations were collected independently.\n\n1. The number of __expected successes and expected failures is at least 10__.\n    * $n_1 p_0 \\ge 10, \\ \\ n_1(1-p_0)\\ge 10$\n\n<hr>\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.  \n<br>\nTesting $H_0: p=0.36$ vs. $H_A: p \\neq 0.36$.  \n<br>\nAre the conditions satisfied?\n\n\n\n\n\n\n\n\n\n\n## Step 4: p-value\n\nThe __[p-value]{style=\"color:darkorange\"}__ is the __probability__ of obtaining a test statistic _just as extreme or more extreme_ than the observed test statistic assuming the null hypothesis $H_0$ is true. \n\n::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\nCalculate the _p_-value:\n\n\n\n\n\n\n\n\\begin{align}\n2 &\\cdot P(\\hat{p}<0.35) \\\\\n&= 2 \\cdot P\\Big(Z_{\\hat{p}} < \\frac{94/269 - 0.36}{\\sqrt{\\frac{0.36\\cdot(1-0.36)}{269}}}\\Big)\\\\\n&=2 \\cdot P(Z_{\\hat{p}} < -0.3607455)\\\\\n&= 0.7182897\n\\end{align}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pnorm(-0.3607455)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7182897\n```\n:::\n:::\n\n\n\n:::\n:::\n\n\n## Step 5: Conclusion to hypothesis test\n\n\\begin{align}\nH_0:& p = 0.36\\\\\nH_A:& p \\neq 0.36\\\\\n\\end{align}\n\n* Recall the $p$-value = 0.7182897\n* Use $\\alpha$ = 0.05.\n* Do we reject or fail to reject $H_0$?\n\n__Conclusion statement__:\n\n* Stats class conclusion\n    * There is insufficient evidence that the (population) proportion of young male college students that participated in sports betting in the previous year is different than 0.36 ( $p$-value = 0.72).\n\n* More realistic manuscript conclusion: \n    * In a sample of 269 male college students, 35% had participated in sports betting in the previous year, which is not different from 36% ( $p$-value = 0.72).\n\n\n## 95% CI for population proportion\n\n::: {style=\"font-size: 80%;\"}\n\n::: columns\n::: {.column width=\"50%\"}\nWhat to use for SE in CI formula?\n:::\n::: {.column width=\"50%\"}\n$$\\hat{p} \\pm z^* \\cdot SE_{\\hat{p}}$$\n:::\n:::\n\n::: columns\n::: {.column width=\"50%\"}\nSampling distribution of $\\hat{p}$:\n:::\n::: {.column width=\"50%\"}\n$$\\hat{p} \\sim N\\Big(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\Big)$$\n\n:::\n:::\n\n::: columns\n::: {.column width=\"50%\"}\nProblem: We don't know what $p$ is - it's what we're estimating with the CI.  \nSolution: [approximate $p$ with $\\hat{p}$]{style=\"color:purple\"}:\n\n:::\n::: {.column width=\"50%\"}\n\n$$SE_{\\hat{p}} = \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n\n:::\n:::\n\n:::\n\n<hr>\n\n::: {style=\"font-size: 85%;\"}\n::: columns\n::: {.column width=\"50%\"}\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.   \nFind the 95% CI for the population proportion. \n\n:::\n\n::: {.column width=\"50%\"}\n\n\n\n\n\n\n\n\\begin{align}\n94/269 &\\pm 1.96 \\cdot SE_{\\hat{p}}\\\\\nSE_{\\hat{p}} &= \\sqrt{\\frac{(94/269)(1-94/269)}{269}}\\\\\n(0.293 &, 0.407)\n\\end{align}\n\n:::\n:::\n\n__Interpretation__:  \nWe are 95% confident that the (population) proportion of young male college students that participated in sports betting in the previous year is in (0.29, 0.41).\n\n:::\n\n## Conditions for one proportion: __test vs. CI__\n\n::: {style=\"font-size: 90%;\"}\n\n::: columns\n::: {.column width=\"48%\"}\n[__Hypothesis test conditions__]{style=\"color:green\"}\n\n1. _Independent observations_ \n    * The observations were collected independently.\n\n<br>\n\n2. The number of __expected__ successes and __expected__ failures is at least 10.\n\n$$n_1 p_0 \\ge 10, \\ \\ n_1(1-p_0)\\ge 10$$\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n[__Confidence interval conditions__]{style=\"color:purple\"}\n\n1. _Independent observations_ \n    * The observations were collected independently.\n\n<br>\n\n2. The number of successes and failures is at least 10:\n\n$$n_1\\hat{p}_1 \\ge 10, \\ \\ n_1(1-\\hat{p}_1)\\ge 10$$\n\n:::\n:::\n\n\n\n\n\n\n\n\n:::\n\n# Inference for difference of two independent proportions <br> $\\hat{p}_1-\\hat{p}_2$\n\n## Sampling distribution of $\\hat{p}_1-\\hat{p}_2$ \n\n::: {style=\"font-size: 90%;\"}\n\n* $\\hat{p}_1=\\frac{X_1}{n_1}$ and $\\hat{p}_2=\\frac{X_2}{n_2}$, \n    * $X_1$ & $X_2$ are the number of \"successes\"\n    * $n_1$ & $n_2$ are the sample sizes of the 1st & 2nd samples \n\n<br>\n\n* Each $\\hat{p}$ can be approximated by a normal distribution, for \"big enough\" $n$\n* Since the difference of independent normal random variables is also normal, it follows that for \"big enough\" $n_1$ and $n_2$ \n\n$$\\hat{p}_1 - \\hat{p}_2 \\sim N \\Big(\\mu_{\\hat{p}_1 - \\hat{p}_2} = p_1 - p_2, ~~\n\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} \n\\Big)$$\n\nwhere $p_1$ & $p_2$ are the population proportions, respectively.\n\n* [*How we apply this result to CI's and test statistics is different!!!*]{style=\"color:purple\"}\n\n:::\n\n## Step 3: Test statistic (1/2)\n\n::: {style=\"font-size: 90%;\"}\n\nSampling distribution of $\\hat{p}_1 - \\hat{p}_2$:\n$$\\hat{p}_1 - \\hat{p}_2 \\sim N \\Big(\\mu_{\\hat{p}_1 - \\hat{p}_2} = p_1 - p_2, ~~\n\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} \n\\Big)$$\n\nSince we assume $H_0: p_1 - p_2 = 0$ is true, we \"pool\" the proportions of the two samples to calculate the SE:\n\n$$\\text{pooled proportion} = \\hat{p}_{pool} = \\dfrac{\\text{total number of successes} }{ \\text{total number of cases}} = \\frac{x_1+x_2}{n_1+n_2}$$ \n\n\nTest statistic:\n\n$$\n\\text{test statistic} = z_{\\hat{p}_1 - \\hat{p}_2} = \\frac{\\hat{p}_1 - \\hat{p}_2 - 0}{\\sqrt{\\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_1} + \\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_2}}}\n$$\n\n:::\n\n\n## Step 3: Test statistic (2/2)\n\n::: {style=\"font-size: 85%;\"}\n\n$$\n\\text{test statistic} = z_{\\hat{p}_1 - \\hat{p}_2} = \\frac{\\hat{p}_1 - \\hat{p}_2 - 0}{\\sqrt{\\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_1} + \\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_2}}}\n$$\n\n$$\\text{pooled proportion} = \\hat{p}_{pool} = \\dfrac{\\text{total number of successes} }{ \\text{total number of cases}} = \\frac{x_1+x_2}{n_1+n_2}$$ \n\n:::\n\n<hr>\n\n::: {style=\"font-size: 90%;\"}\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had.  \nWhat is the test statistic when testing $H_0: p_{coll} - p_{noncoll} = 0$ vs. \n$H_A: p_{coll} - p_{noncoll} \\neq 0$? \n\n\n\n\n\n\n\n\\begin{align}\nz_{\\hat{p}_1 - \\hat{p}_2} &= \\frac{94/269 - 77/214-0}{\\sqrt{0.354\\cdot(1-0.354)(\\frac{1}{269}+\\frac{1}{214})}}\\\\\n&=-0.2367497\n\\end{align}\n\n:::\n\n\n## Step \"3b\": Conditions satisfied?\n\n::: {style=\"font-size: 90%;\"}\n\n__Conditions__:\n\n* _Independent observations & samples_\n    * The observations were collected independently. \n    * In particular, observations from the two groups weren't paired in any meaningful way.\n\n* The number of expected successes and expected failures is at least 10 _for each group_ - using the pooled proportion:\n    * $n_1\\hat{p}_{pool} \\ge 10, \\ \\ n_1(1-\\hat{p}_{pool}) \\ge 10$\n    * $n_2\\hat{p}_{pool} \\ge 10, \\ \\ n_2(1-\\hat{p}_{pool}) \\ge 10$\n\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had.   \nTesting $H_0: p_{coll} - p_{noncoll} = 0$ vs. \n$H_A: p_{coll} - p_{noncoll} \\neq 0$? .  \n<br>\nAre the conditions satisfied?\n\n\n\n\n\n\n\n\n:::\n\n\n## Step 4: p-value\n\n::: {style=\"font-size: 90%;\"}\n\nThe __[p-value]{style=\"color:darkorange\"}__ is the __probability__ of obtaining a test statistic _just as extreme or more extreme_ than the observed test statistic assuming the null hypothesis $H_0$ is true. \n\n::: columns\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\nCalculate the _p_-value:\n\n\n\n\n\n\n\n\n\\begin{align}\n2 &\\cdot P(\\hat{p}_1 - \\hat{p}_2<0.35-0.36) \\\\\n= 2 &\\cdot P\\Big(Z_{\\hat{p}_1 - \\hat{p}_2} < \\\\\n&\\frac{94/269 - 77/214-0}{\\sqrt{0.354\\cdot(1-0.354)(\\frac{1}{269}+\\frac{1}{214})}}\\Big)\\\\\n=2 &\\cdot P(Z_{\\hat{p}} < -0.2367497) \\\\\n= & 0.812851\n\\end{align}\n\n:::\n:::\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pnorm(-0.2367497)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.812851\n```\n:::\n:::\n\n\n\n\n\n\n## Step 5: Conclusion to hypothesis test\n\n::: {style=\"font-size: 90%;\"}\n\n\\begin{align}\nH_0:& p_{coll} - p_{noncoll} = 0\\\\\nH_A:& p_{coll} - p_{noncoll} \\neq 0\\\\\n\\end{align}\n\n* Recall the $p$-value = 0.812851\n* Use $\\alpha$ = 0.05.\n* Do we reject or fail to reject $H_0$?\n\n__Conclusion statement__:\n\n* Stats class conclusion\n    * There is insufficient evidence that the difference in (population) proportions of young male college and noncollege students that participated in sports betting in the previous year are different ( $p$-value = 0.81).\n\n* More realistic manuscript conclusion: \n    * 35% of young male college students (n=269) and 36% of noncollege young males (n=214) participated in sports betting in the previous year ( $p$-value = 0.81).\n\n:::\n\n\n\n## 95% CI for population difference in proportions\n\n::: {style=\"font-size: 80%;\"}\n\n::: columns\n::: {.column width=\"50%\"}\nWhat to use for SE in CI formula?\n:::\n::: {.column width=\"50%\"}\n$$\\hat{p}_1 - \\hat{p}_2 \\pm z^* \\cdot SE_{\\hat{p}_1 - \\hat{p}_2}$$\n:::\n:::\n\n::: columns\n::: {.column width=\"50%\"}\nSE in sampling distribution of $\\hat{p}_1 - \\hat{p}_2$\n:::\n::: {.column width=\"50%\"}\n$$\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} $$\n\n:::\n:::\n\n::: columns\n::: {.column width=\"50%\"}\nProblem: We don't know what $p$ is - it's what we're estimating with the CI.  \nSolution: [approximate $p_1$, $p_2$ with $\\hat{p}_1$, $\\hat{p}_2$]{style=\"color:purple\"}:\n\n:::\n::: {.column width=\"50%\"}\n\n$$SE_{\\hat{p}_1 - \\hat{p}_2} = \\sqrt{\n\\frac{\\hat{p}_1\\cdot(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2\\cdot(1-\\hat{p}_2)}{n_2}}$$\n\n:::\n:::\n\n:::\n\n<hr>\n\n::: columns\n::: {.column width=\"45%\"}\n\n::: {style=\"font-size: 80%;\"}\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had.\nFind the 95% CI for the difference in population proportions. \n:::\n\n:::\n\n::: {.column width=\"55%\"}\n\n\n\n\n\n\n\n\n::: {style=\"font-size: 70%;\"}\n\n$$\\frac{94}{269} - \\frac{77}{214} \\pm 1.96 \\cdot SE_{\\hat{p}_1 - \\hat{p}_2}$$\n\n\\begin{align}\n& SE_{\\hat{p}_1 - \\hat{p}_2}=\\\\\n& \\sqrt{\n\\frac{94/269 \\cdot (1-94/269)}{269} + \n\\frac{77/214 \\cdot (1-77/214)}{214}}\n\\end{align}\n\n:::\n\n:::\n:::\n\n::: {style=\"font-size: 80%;\"}\n__Interpretation__:  \nWe are 95% confident that the difference in (population) proportions of young male college and noncollege students that participated in sports betting in the previous year is in (-0.127, 0.106).\n\n:::\n\n\n## Conditions for difference in proportions: test vs. CI\n\n::: {style=\"font-size: 90%;\"}\n\n::: columns\n::: {.column width=\"48%\"}\n[__Hypothesis test conditions__]{style=\"color:green\"}\n\n1. _Independent observations & samples_\n    * The observations were collected independently. \n    * In particular, observations from the two groups weren't paired in any meaningful way.\n\n<br>\n\n2. The number of __expected__ successes and __expected__ failures is at least 10 _for each group_ - using the pooled proportion:\n    * $n_1\\hat{p}_{pool} \\ge 10, \\ \\ n_1(1-\\hat{p}_{pool}) \\ge 10$\n    * $n_2\\hat{p}_{pool} \\ge 10, \\ \\ n_2(1-\\hat{p}_{pool}) \\ge 10$\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"48%\"}\n\n[__Confidence interval conditions__]{style=\"color:purple\"}\n\n1. _Independent observations & samples_\n    * The observations were collected independently. \n    * In particular, observations from the two groups weren't paired in any meaningful way.\n\n<br>\n\n2. The number of successes and failures is at least 10 _for each group_.\n    * $n_1\\hat{p}_1 \\ge 10, \\ \\ n_1(1-\\hat{p}_1) \\ge 10$\n    * $n_2\\hat{p}_2 \\ge 10, \\ \\ n_2(1-\\hat{p}_2) \\ge 10$\n\n:::\n:::\n\n\n\n\n\n\n\n:::\n\n# R: 1- and 2-sample proportions tests\n\n`prop.test(x, n, p = NULL,`  \n&nbsp; &nbsp; &nbsp;     `alternative = c(\"two.sided\", \"less\", \"greater\"),`   \n&nbsp; &nbsp; &nbsp;     `conf.level = 0.95,`  \n&nbsp; &nbsp; &nbsp;     `correct = TRUE)`\n\n* 2 options for data input \n    1. Summary counts\n        * `x` = vector with counts of \"successes\" \n        * `n` = vector with sample size in each group\n    2. Dataset\n        * `x = table()` of dataset\n        * Need to create a dataset based on the summary stats if do not already have one\n* Continuity correction\n\n# R: 1-sample proportion test\n\n\"1-prop z-test\"\n\n## Summary stats input for 1-sample proportion test\n\n::: {style=\"font-size: 90%;\"}\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.   \nTest $H_0: p=0.36$ vs. $H_A: p \\neq 0.36$? \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.35*269 # number of \"successes\"; round this value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269,              # x = # successes & n = sample size\n          p = 0.36,                     # null value p0\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)              # no continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  94 out of 269, null probability 0.36\nX-squared = 0.13014, df = 1, p-value = 0.7183\nalternative hypothesis: true p is not equal to 0.36\n95 percent confidence interval:\n 0.2949476 0.4081767\nsample estimates:\n        p \n0.3494424 \n```\n:::\n:::\n\n\n\nCan `tidy()` test output:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269, p = 0.36, alternative = \"two.sided\", correct = FALSE) %>% \n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"wtvjhnieyb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wtvjhnieyb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wtvjhnieyb thead, #wtvjhnieyb tbody, #wtvjhnieyb tfoot, #wtvjhnieyb tr, #wtvjhnieyb td, #wtvjhnieyb th {\n  border-style: none;\n}\n\n#wtvjhnieyb p {\n  margin: 0;\n  padding: 0;\n}\n\n#wtvjhnieyb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wtvjhnieyb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wtvjhnieyb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wtvjhnieyb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wtvjhnieyb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wtvjhnieyb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wtvjhnieyb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wtvjhnieyb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wtvjhnieyb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wtvjhnieyb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wtvjhnieyb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wtvjhnieyb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wtvjhnieyb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wtvjhnieyb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wtvjhnieyb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wtvjhnieyb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wtvjhnieyb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wtvjhnieyb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wtvjhnieyb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wtvjhnieyb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wtvjhnieyb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wtvjhnieyb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wtvjhnieyb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wtvjhnieyb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wtvjhnieyb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wtvjhnieyb .gt_left {\n  text-align: left;\n}\n\n#wtvjhnieyb .gt_center {\n  text-align: center;\n}\n\n#wtvjhnieyb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wtvjhnieyb .gt_font_normal {\n  font-weight: normal;\n}\n\n#wtvjhnieyb .gt_font_bold {\n  font-weight: bold;\n}\n\n#wtvjhnieyb .gt_font_italic {\n  font-style: italic;\n}\n\n#wtvjhnieyb .gt_super {\n  font-size: 65%;\n}\n\n#wtvjhnieyb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wtvjhnieyb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wtvjhnieyb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wtvjhnieyb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wtvjhnieyb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wtvjhnieyb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wtvjhnieyb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wtvjhnieyb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wtvjhnieyb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.1301373</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7182897</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2949476</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4081767</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n:::\n\n## Dataset input for 1-sample proportion test (1/2)\n::: columns\n::: {.column width=\"50%\"}\nSince we don't have a dataset, we first need to create a dataset based on the results:\n\n>\"out of 269 male college students, 35% had participated in sports betting in the previous year\"\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.35*269 # number of \"successes\"; round this value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\nSportsBet1 <- tibble(\n  Coll = c(rep(\"Bet\", 94),\n           rep(\"NotBet\",269-94))\n  )\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(SportsBet1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 269\nColumns: 1\n$ Coll <chr> \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"B…\n```\n:::\n\n```{.r .cell-code}\nSportsBet1 %>% tabyl(Coll)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Coll   n   percent\n    Bet  94 0.3494424\n NotBet 175 0.6505576\n```\n:::\n:::\n\n\n\n<br>\n\nR code for proportions test requires input as a base R `table`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(SportsBet1$Coll)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Bet NotBet \n    94    175 \n```\n:::\n:::\n\n\n\n:::\n:::\n\n\n## Dataset input for 1-sample proportion test (2/2)\n\n::: {style=\"font-size: 90%;\"}\n* When using a dataset, `prop.test` requires the input `x` to be a table\n* Note that we do not also specify `n` since the table already includes all needed information.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet1$Coll),   # table() of data\n          p = 0.36,                     # null value p0\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)              # no continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(SportsBet1$Coll), null probability 0.36\nX-squared = 0.13014, df = 1, p-value = 0.7183\nalternative hypothesis: true p is not equal to 0.36\n95 percent confidence interval:\n 0.2949476 0.4081767\nsample estimates:\n        p \n0.3494424 \n```\n:::\n:::\n\n\n\nCompare output with summary stats method:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269,              # x = # successes & n = sample size\n          p = 0.36,                     # null value p0\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)  %>%         # no continuity correction\n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"sgngpwtrhy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sgngpwtrhy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sgngpwtrhy thead, #sgngpwtrhy tbody, #sgngpwtrhy tfoot, #sgngpwtrhy tr, #sgngpwtrhy td, #sgngpwtrhy th {\n  border-style: none;\n}\n\n#sgngpwtrhy p {\n  margin: 0;\n  padding: 0;\n}\n\n#sgngpwtrhy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sgngpwtrhy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sgngpwtrhy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sgngpwtrhy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sgngpwtrhy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sgngpwtrhy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sgngpwtrhy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sgngpwtrhy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sgngpwtrhy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sgngpwtrhy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sgngpwtrhy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sgngpwtrhy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sgngpwtrhy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sgngpwtrhy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sgngpwtrhy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgngpwtrhy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sgngpwtrhy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sgngpwtrhy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sgngpwtrhy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgngpwtrhy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sgngpwtrhy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgngpwtrhy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sgngpwtrhy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgngpwtrhy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sgngpwtrhy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgngpwtrhy .gt_left {\n  text-align: left;\n}\n\n#sgngpwtrhy .gt_center {\n  text-align: center;\n}\n\n#sgngpwtrhy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sgngpwtrhy .gt_font_normal {\n  font-weight: normal;\n}\n\n#sgngpwtrhy .gt_font_bold {\n  font-weight: bold;\n}\n\n#sgngpwtrhy .gt_font_italic {\n  font-style: italic;\n}\n\n#sgngpwtrhy .gt_super {\n  font-size: 65%;\n}\n\n#sgngpwtrhy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sgngpwtrhy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sgngpwtrhy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sgngpwtrhy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sgngpwtrhy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sgngpwtrhy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sgngpwtrhy .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#sgngpwtrhy .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#sgngpwtrhy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.1301373</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7182897</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2949476</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4081767</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n:::\n\n## Continuity correction: 1-prop z-test with vs. without CC\n\n::: {style=\"font-size: 90%;\"}\n* Recall that when we approximated the \n* binomial distribution with a normal distribution to calculate a probability, \n* that we included a continuity correction (CC) \n* to account for approximating a discrete distribution with a continuous distribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269, p = 0.36, alternative = \"two.sided\", \n          correct = FALSE) %>% \n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"blvlxrofiv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#blvlxrofiv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#blvlxrofiv thead, #blvlxrofiv tbody, #blvlxrofiv tfoot, #blvlxrofiv tr, #blvlxrofiv td, #blvlxrofiv th {\n  border-style: none;\n}\n\n#blvlxrofiv p {\n  margin: 0;\n  padding: 0;\n}\n\n#blvlxrofiv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#blvlxrofiv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#blvlxrofiv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#blvlxrofiv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#blvlxrofiv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#blvlxrofiv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#blvlxrofiv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#blvlxrofiv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#blvlxrofiv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#blvlxrofiv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#blvlxrofiv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#blvlxrofiv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#blvlxrofiv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#blvlxrofiv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#blvlxrofiv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#blvlxrofiv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#blvlxrofiv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#blvlxrofiv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#blvlxrofiv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#blvlxrofiv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#blvlxrofiv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#blvlxrofiv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#blvlxrofiv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#blvlxrofiv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#blvlxrofiv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#blvlxrofiv .gt_left {\n  text-align: left;\n}\n\n#blvlxrofiv .gt_center {\n  text-align: center;\n}\n\n#blvlxrofiv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#blvlxrofiv .gt_font_normal {\n  font-weight: normal;\n}\n\n#blvlxrofiv .gt_font_bold {\n  font-weight: bold;\n}\n\n#blvlxrofiv .gt_font_italic {\n  font-style: italic;\n}\n\n#blvlxrofiv .gt_super {\n  font-size: 65%;\n}\n\n#blvlxrofiv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#blvlxrofiv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#blvlxrofiv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#blvlxrofiv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#blvlxrofiv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#blvlxrofiv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#blvlxrofiv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#blvlxrofiv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#blvlxrofiv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.1301373</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7182897</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2949476</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4081767</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269, p = 0.36, alternative = \"two.sided\", \n          correct = TRUE) %>% \n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"zqowaidqof\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zqowaidqof table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zqowaidqof thead, #zqowaidqof tbody, #zqowaidqof tfoot, #zqowaidqof tr, #zqowaidqof td, #zqowaidqof th {\n  border-style: none;\n}\n\n#zqowaidqof p {\n  margin: 0;\n  padding: 0;\n}\n\n#zqowaidqof .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zqowaidqof .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zqowaidqof .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zqowaidqof .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zqowaidqof .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zqowaidqof .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zqowaidqof .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zqowaidqof .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zqowaidqof .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zqowaidqof .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zqowaidqof .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zqowaidqof .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zqowaidqof .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zqowaidqof .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zqowaidqof .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqowaidqof .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zqowaidqof .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zqowaidqof .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zqowaidqof .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqowaidqof .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zqowaidqof .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqowaidqof .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zqowaidqof .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqowaidqof .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zqowaidqof .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zqowaidqof .gt_left {\n  text-align: left;\n}\n\n#zqowaidqof .gt_center {\n  text-align: center;\n}\n\n#zqowaidqof .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zqowaidqof .gt_font_normal {\n  font-weight: normal;\n}\n\n#zqowaidqof .gt_font_bold {\n  font-weight: bold;\n}\n\n#zqowaidqof .gt_font_italic {\n  font-style: italic;\n}\n\n#zqowaidqof .gt_super {\n  font-size: 65%;\n}\n\n#zqowaidqof .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zqowaidqof .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zqowaidqof .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zqowaidqof .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zqowaidqof .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zqowaidqof .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zqowaidqof .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zqowaidqof .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zqowaidqof div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.08834805</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7662879</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2931841</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4100774</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test with continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\nDifferences are small when sample sizes are large.\n\n:::\n\n# R: 2-samples proportion test\n\n\"2-prop z-test\"\n\n\n## Summary stats input for 2-samples proportion test\n\n::: {style=\"font-size: 80%;\"}\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had. Test $H_0: p_{coll} - p_{noncoll} = 0$ vs. $H_A: p_{coll} - p_{noncoll} \\neq 0$.  \n:::\n\n::: {style=\"font-size: 85%;\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# round the number of successes:\n.35*269 # number of \"successes\" in college students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\n.36*214 # number of \"successes\" in noncollege students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77.04\n```\n:::\n\n```{.r .cell-code}\nNmbrBet <- c(94, 77)                    # vector for # of successes in each group\nTotalNmbr <- c(269, 214)                # vector for sample size in each group\n\nprop.test(x = NmbrBet,                  # x is # of successes in each group \n          n = TotalNmbr,                # n is sample size in each group\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)              # no continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  NmbrBet out of TotalNmbr\nX-squared = 0.05605, df = 1, p-value = 0.8129\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.09628540  0.07554399\nsample estimates:\n   prop 1    prop 2 \n0.3494424 0.3598131 \n```\n:::\n:::\n\n\n\n:::\n\n\n## Dataset input for 2-samples proportion test (1/2)\n\n::: columns\n::: {.column width=\"50%\"}\n::: {style=\"font-size: 85%;\"}\nSince we don't have a dataset, we first need to create a dataset based on the results:\n\n>\"out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had\"\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# round the number of successes:\n.35*269 # college students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\n.36*214 # noncollege students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77.04\n```\n:::\n\n```{.r .cell-code}\nSportsBet2 <- tibble(\n  Group = c(rep(\"College\", 269), \n         rep(\"NonCollege\", 214)),\n  Bet = c(rep(\"yes\", 94), \n          rep(\"no\", 269-94),\n          rep(\"yes\", 77), \n          rep(\"no\", 214-77))\n)\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(SportsBet2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 483\nColumns: 2\n$ Group <chr> \"College\", \"College\", \"College\", \"College\", \"College\", \"College\"…\n$ Bet   <chr> \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"…\n```\n:::\n\n```{.r .cell-code}\nSportsBet2 %>% tabyl(Group, Bet)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Group  no yes\n    College 175  94\n NonCollege 137  77\n```\n:::\n:::\n\n\n\n<br>\n\nR code for proportions test requires input as a base R `table`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(SportsBet2$Group, \n      SportsBet2$Bet)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            \n              no yes\n  College    175  94\n  NonCollege 137  77\n```\n:::\n:::\n\n\n\n:::\n:::\n\n\n## Dataset input for 2-samples proportion test (2/2)\n\n::: {style=\"font-size: 90%;\"}\n* When using a dataset, `prop.test` requires the input `x` to be a table\n* Note that we do not also specify `n` since the table already includes all needed information.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet2$Group, SportsBet2$Bet),\n       alternative = \"two.sided\",\n       correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  table(SportsBet2$Group, SportsBet2$Bet)\nX-squared = 0.05605, df = 1, p-value = 0.8129\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.07554399  0.09628540\nsample estimates:\n   prop 1    prop 2 \n0.6505576 0.6401869 \n```\n:::\n:::\n\n\n\nCompare output with summary stats method:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = NmbrBet,                  # x is # of successes in each group \n          n = TotalNmbr,                # n is sample size in each group\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE) %>%          # no continuity correction\n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"entnclqakw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#entnclqakw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#entnclqakw thead, #entnclqakw tbody, #entnclqakw tfoot, #entnclqakw tr, #entnclqakw td, #entnclqakw th {\n  border-style: none;\n}\n\n#entnclqakw p {\n  margin: 0;\n  padding: 0;\n}\n\n#entnclqakw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#entnclqakw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#entnclqakw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#entnclqakw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#entnclqakw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#entnclqakw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#entnclqakw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#entnclqakw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#entnclqakw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#entnclqakw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#entnclqakw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#entnclqakw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#entnclqakw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#entnclqakw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#entnclqakw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#entnclqakw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#entnclqakw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#entnclqakw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#entnclqakw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#entnclqakw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#entnclqakw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#entnclqakw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#entnclqakw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#entnclqakw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#entnclqakw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#entnclqakw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#entnclqakw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#entnclqakw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#entnclqakw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#entnclqakw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#entnclqakw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#entnclqakw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#entnclqakw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#entnclqakw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#entnclqakw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#entnclqakw .gt_left {\n  text-align: left;\n}\n\n#entnclqakw .gt_center {\n  text-align: center;\n}\n\n#entnclqakw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#entnclqakw .gt_font_normal {\n  font-weight: normal;\n}\n\n#entnclqakw .gt_font_bold {\n  font-weight: bold;\n}\n\n#entnclqakw .gt_font_italic {\n  font-style: italic;\n}\n\n#entnclqakw .gt_super {\n  font-size: 65%;\n}\n\n#entnclqakw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#entnclqakw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#entnclqakw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#entnclqakw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#entnclqakw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#entnclqakw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#entnclqakw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#entnclqakw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#entnclqakw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.3598131</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.05605044</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8128509</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.0962854</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.07554399</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n:::\n\n\n## Continuity correction: 2-prop z-test with vs. without CC\n\n::: {style=\"font-size: 90%;\"}\n* Recall that when we approximated the \n* binomial distribution with a normal distribution to calculate a probability, \n* that we included a continuity correction (CC) \n* to account for approximating a discrete distribution with a continuous distribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = NmbrBet, n = TotalNmbr, alternative = \"two.sided\", \n          correct = FALSE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"dyanebzsgi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dyanebzsgi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dyanebzsgi thead, #dyanebzsgi tbody, #dyanebzsgi tfoot, #dyanebzsgi tr, #dyanebzsgi td, #dyanebzsgi th {\n  border-style: none;\n}\n\n#dyanebzsgi p {\n  margin: 0;\n  padding: 0;\n}\n\n#dyanebzsgi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dyanebzsgi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dyanebzsgi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dyanebzsgi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dyanebzsgi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dyanebzsgi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dyanebzsgi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dyanebzsgi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dyanebzsgi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dyanebzsgi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dyanebzsgi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dyanebzsgi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dyanebzsgi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dyanebzsgi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dyanebzsgi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyanebzsgi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dyanebzsgi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dyanebzsgi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dyanebzsgi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyanebzsgi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dyanebzsgi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyanebzsgi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dyanebzsgi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyanebzsgi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dyanebzsgi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dyanebzsgi .gt_left {\n  text-align: left;\n}\n\n#dyanebzsgi .gt_center {\n  text-align: center;\n}\n\n#dyanebzsgi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dyanebzsgi .gt_font_normal {\n  font-weight: normal;\n}\n\n#dyanebzsgi .gt_font_bold {\n  font-weight: bold;\n}\n\n#dyanebzsgi .gt_font_italic {\n  font-style: italic;\n}\n\n#dyanebzsgi .gt_super {\n  font-size: 65%;\n}\n\n#dyanebzsgi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dyanebzsgi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dyanebzsgi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dyanebzsgi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dyanebzsgi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dyanebzsgi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dyanebzsgi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dyanebzsgi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dyanebzsgi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.3598131</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.05605044</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8128509</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.0962854</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.07554399</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = NmbrBet, n = TotalNmbr, alternative = \"two.sided\", \n          correct = TRUE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"dgrfdlwppq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dgrfdlwppq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dgrfdlwppq thead, #dgrfdlwppq tbody, #dgrfdlwppq tfoot, #dgrfdlwppq tr, #dgrfdlwppq td, #dgrfdlwppq th {\n  border-style: none;\n}\n\n#dgrfdlwppq p {\n  margin: 0;\n  padding: 0;\n}\n\n#dgrfdlwppq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dgrfdlwppq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dgrfdlwppq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dgrfdlwppq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dgrfdlwppq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dgrfdlwppq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dgrfdlwppq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dgrfdlwppq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dgrfdlwppq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dgrfdlwppq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dgrfdlwppq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dgrfdlwppq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dgrfdlwppq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dgrfdlwppq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dgrfdlwppq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgrfdlwppq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dgrfdlwppq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dgrfdlwppq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dgrfdlwppq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgrfdlwppq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dgrfdlwppq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgrfdlwppq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dgrfdlwppq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgrfdlwppq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dgrfdlwppq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dgrfdlwppq .gt_left {\n  text-align: left;\n}\n\n#dgrfdlwppq .gt_center {\n  text-align: center;\n}\n\n#dgrfdlwppq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dgrfdlwppq .gt_font_normal {\n  font-weight: normal;\n}\n\n#dgrfdlwppq .gt_font_bold {\n  font-weight: bold;\n}\n\n#dgrfdlwppq .gt_font_italic {\n  font-style: italic;\n}\n\n#dgrfdlwppq .gt_super {\n  font-size: 65%;\n}\n\n#dgrfdlwppq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dgrfdlwppq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dgrfdlwppq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dgrfdlwppq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dgrfdlwppq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dgrfdlwppq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dgrfdlwppq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dgrfdlwppq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dgrfdlwppq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.3598131</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.01987511</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8878864</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.1004806</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.07973918</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions with continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\nDifferences are small when sample sizes are large.\n\n:::\n\n\n# Power & sample size <br> for testing proportions\n\n\n## __Sample size__ calculation for testing one proportion\n\n::: {style=\"font-size: 90%;\"}\n* Recall in our sports betting example that the null $p_0=0.36$ and the observed proportion was $\\hat{p}=0.35$. \n    * The _p_-value from the hypothesis test was not significant.\n    * How big would the sample size $n$ need to be in order for the _p_-value to be significant?\n\n* [__Calculate $n$__]{style=\"color:green\"} \n    * given $\\alpha$, power ( $1-\\beta$ ), \"true\" alternative proportion $p$, and null $p_0$:\n\n::: columns\n::: {.column width=\"40%\"}\n\n$$n=p(1-p)\\left(\\frac{z_{1-\\alpha/2}+z_{1-\\beta}}{p-p_0}\\right)^2$$\n:::\n\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 0.35\np0 <- 0.36\nalpha <- 0.05\nbeta <- 0.20  #power=1-beta; want >=80% power\nn <- p*(1-p)*((qnorm(1-alpha/2) + qnorm(1-beta)) /\n                (p-p0))^2\nn\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17856.2\n```\n:::\n\n```{.r .cell-code}\nceiling(n) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17857\n```\n:::\n:::\n\n\n:::\n:::\n\n_We would need a sample size of at least 17,857!_\n\n:::\n\n## __Power__ calculation for testing one proportion\n\n::: {style=\"font-size: 90%;\"}\nConversely, we can calculate how much power we had in our example given the sample size of 269.\n\n* [__Calculate power__]{style=\"color:green\"}, \n    * given $\\alpha$, $n$, \"true\" alternative proportion $p$, and null $p_0$\n    \n$$1-\\beta=\n\t\t\t\\Phi\\left(z-z_{1-\\alpha/2}\\right)+\\Phi\\left(-z-z_{1-\\alpha/2}\\right)\n\t\t\t\\quad ,\\quad \\text{where } z=\\frac{p-p_0}{\\sqrt{\\frac{p(1-p)}{n}}}$$\n\n$\\Phi$ is the probability for a standard normal distribution \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 0.35; p0 <- 0.36; alpha <- 0.05; n <- 269\n(z <- (p-p0)/sqrt(p*(1-p)/n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.343863\n```\n:::\n\n```{.r .cell-code}\n(Power <- pnorm(z - qnorm(1-alpha/2)) +  pnorm(-z - qnorm(1-alpha/2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06365242\n```\n:::\n:::\n\n\n\nIf the population proportion is 0.35 instead of 0.36, we only have a 6.4% chance of correctly rejecting $H_0$ when the sample size is 269.\n\n:::\n\n## R package `pwr` for power analyses\n\n::: {style=\"font-size: 80%;\"}\n\n* Specify all parameters _except for_ the one being solved for.\n\n* One proportion\n\n`pwr.p.test(h = NULL, n = NULL, sig.level = 0.05, power = NULL,`\n&nbsp; &nbsp; &nbsp;    `alternative = c(\"two.sided\",\"less\",\"greater\"))`\n\n* Two proportions (same sample sizes)\n\n`pwr.2p.test(h = NULL, n = NULL, sig.level = 0.05, power = NULL,` \n&nbsp; &nbsp; &nbsp;    `alternative = c(\"two.sided\",\"less\",\"greater\"))`\n\n* Two proportions (different sample sizes)\n\n`pwr.2p2n.test(h = NULL, n1 = NULL, n2 = NULL, sig.level = 0.05, power = NULL,`\n&nbsp; &nbsp; &nbsp;    `alternative = c(\"two.sided\", \"less\",\"greater\"))`\n\n:::\n<hr>\n\n::: {style=\"font-size: 90%;\"}\n$h$ is the effect size, and calculated using an arcsine transformation: \n\n$$h = \\text{ES.h(p1, p2)} = 2\\arcsin(\\sqrt{p_1})-2\\arcsin(\\sqrt{p_2})$$\n\n:::\n::: {style=\"font-size: 80%;\"}\nSee PASS documentation for \n\n* [testing 1 proportion using effect size](https://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/Tests_for_One_Proportion_using_Effect_Size.pdf) vs. [other ways of powering a test of 1 proportion](https://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/Tests_for_One_Proportion.pdf)\n* [testing 2 proportions using effect size](https://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/Tests_for_Two_Proportions_using_Effect_Size.pdf) vs. [other ways of powering a test of 2 proportions](https://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/Tests_for_Two_Proportions.pdf).\n\n:::\n\n\n\n## `pwr`: __sample size__ for one proportion test\n\n::: {style=\"font-size: 80%;\"}\n`pwr.p.test(h = NULL, n = NULL, sig.level = 0.05, power = NULL,`\n&nbsp; &nbsp; &nbsp;    `alternative = c(\"two.sided\",\"less\",\"greater\"))`\n:::\n\n::: {style=\"font-size: 90%;\"}\n* $h$ is the effect size: `h = ES.h(p1, p2)`\n    * `p1` and `p2` are the two proportions being tested\n    * one of them is the null proportion $p_0$, and the other is the alternative proportion\n\nSpecify all parameters _except for_ the sample size:\n:::\n\n::: columns\n::: {.column width=\"45%\"}\n::: {style=\"font-size: 95%;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\n\np.n <- pwr.p.test(\n  h = ES.h(p1 = 0.36, p2 = 0.35),\n  sig.level = 0.05, \n  power = 0.80, \n  alternative = \"two.sided\")\np.n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     proportion power calculation for binomial distribution (arcsine transformation) \n\n              h = 0.02089854\n              n = 17971.09\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n:::\n:::\n\n\n:::\n:::\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(p.n)\n```\n\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-38-1.png){width=960}\n:::\n:::\n\n\n:::\n:::\n\n\n\n\n## `pwr`: __power__ for one proportion test\n\n::: {style=\"font-size: 80%;\"}\n`pwr.p.test(h = NULL, n = NULL, sig.level = 0.05, power = NULL,`\n&nbsp; &nbsp; &nbsp;    `alternative = c(\"two.sided\",\"less\",\"greater\"))`\n:::\n\n::: {style=\"font-size: 90%;\"}\n* $h$ is the effect size: `h = ES.h(p1, p2)`\n    * `p1` and `p2` are the two proportions being tested\n    * one of them is the null proportion $p_0$, and the other is the alternative proportion\n\nSpecify all parameters _except for_ the power:\n:::\n\n::: columns\n::: {.column width=\"45%\"}\n::: {style=\"font-size: 95%;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\n\np.power <- pwr.p.test(\n  h = ES.h(p1 = 0.36, p2 = 0.35),\n  sig.level = 0.05, \n  # power = 0.80, \n  n = 269,\n  alternative = \"two.sided\")\np.power\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     proportion power calculation for binomial distribution (arcsine transformation) \n\n              h = 0.02089854\n              n = 269\n      sig.level = 0.05\n          power = 0.06356445\n    alternative = two.sided\n```\n:::\n:::\n\n\n:::\n:::\n\n::: {.column width=\"55%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(p.power)\n```\n\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-40-1.png){width=960}\n:::\n:::\n\n\n:::\n:::\n\n## `pwr`: __sample size__ for two proportions test\n\n::: {style=\"font-size: 80%;\"}\n* Two proportions (same sample sizes)\n\n`pwr.2p.test(h = NULL, n = NULL, sig.level = 0.05, power = NULL,` \n&nbsp; &nbsp; &nbsp;    `alternative = c(\"two.sided\",\"less\",\"greater\"))`\n\n:::\n\n::: {style=\"font-size: 85%;\"}\n* $h$ is the effect size: `h = ES.h(p1, p2)`;  `p1` and `p2` are the two proportions being tested\n\nSpecify all parameters _except for_ the sample size:\n:::\n\n::: columns\n::: {.column width=\"45%\"}\n::: {style=\"font-size: 95%;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2.n <- pwr.2p.test(\n  h = ES.h(p1 = 0.36, p2 = 0.35),\n  sig.level = 0.05, \n  power = 0.80, \n  alternative = \"two.sided\")\np2.n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Difference of proportion power calculation for binomial distribution (arcsine transformation) \n\n              h = 0.02089854\n              n = 35942.19\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: same sample sizes\n```\n:::\n:::\n\n\n:::\n:::\n\n::: {.column width=\"55%\"}\n::: {style=\"font-size: 95%;\"}\nNote: $n$ in output is the __number per sample__!\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(p2.n)\n```\n\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-42-1.png){width=960}\n:::\n:::\n\n\n:::\n:::\n\n\n\n\n## `pwr`: __power__ for two proportions test\n\n::: {style=\"font-size: 80%;\"}\n* Two proportions (different sample sizes)\n\n`pwr.2p2n.test(h = NULL, n1 = NULL, n2 = NULL, sig.level = 0.05, power = NULL,`\n&nbsp; &nbsp; &nbsp;    `alternative = c(\"two.sided\", \"less\",\"greater\"))`\n:::\n\n::: {style=\"font-size: 85%;\"}\n* $h$ is the effect size: `h = ES.h(p1, p2)`;  `p1` and `p2` are the two proportions being tested\n\nSpecify all parameters _except for_ the power:\n:::\n\n::: columns\n::: {.column width=\"45%\"}\n::: {style=\"font-size: 95%;\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2.n2 <- pwr.2p2n.test(\n  h = ES.h(p1 = 0.36, p2 = 0.35),\n  n1 = 214,\n  n2 = 269,\n  sig.level = 0.05, \n  # power = 0.80, \n  alternative = \"two.sided\")\np2.n2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     difference of proportion power calculation for binomial distribution (arcsine transformation) \n\n              h = 0.02089854\n             n1 = 214\n             n2 = 269\n      sig.level = 0.05\n          power = 0.05598413\n    alternative = two.sided\n\nNOTE: different sample sizes\n```\n:::\n:::\n\n\n:::\n:::\n\n::: {.column width=\"55%\"}\n::: {style=\"font-size: 95%;\"}\nNote: $n$ in output is the __number per sample__!\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(p2.n2)\n```\n\n::: {.cell-output-display}\n![](12_Prop_inference_files/figure-html/unnamed-chunk-44-1.png){width=960}\n:::\n:::\n\n\n:::\n:::\n\n\n\n## Where are we?\n\n::: {style=\"font-size: 85%;\"}\nCI's and hypothesis tests for different scenarios:\n\n$$\\text{point estimate} \\pm z^*(or~t^*)\\cdot SE,~~\\text{test stat} = \\frac{\\text{point estimate}-\\text{null value}}{SE}$$\n\nDay | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE\n--|--|--|--|--|--|--\n10 | 5.1 | Pop mean | $\\mu$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$\n10 | 5.2 | Pop mean of paired diff | $\\mu_d$ or $\\delta$ | Sample mean of paired diff | $\\bar{x}_{d}$  | **$\\frac{s_d}{\\sqrt{n}}$**\n11 | 5.3 | [Diff in pop <br> means]{style=\"color:black\"} | [$\\mu_1-\\mu_2$]{style=\"color:black\"} | [Diff in sample <br> means]{style=\"color:black\"} | [$\\bar{x}_1 - \\bar{x}_2$]{style=\"color:black\"}  | [**$\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}$ or pooled**]{style=\"color:black\"}\n12 | 8.1 | [Pop proportion]{style=\"color:green\"} | [$p$]{style=\"color:green\"} | [Sample prop]{style=\"color:green\"} | [$\\widehat{p}$]{style=\"color:green\"}  | [$\\sqrt{\\frac{p(1-p)}{n}}$]{style=\"color:red\"}\n12 | 8.2 | [Diff in pop <br> proportions]{style=\"color:green\"} | [$p_1-p_2$]{style=\"color:green\"} | [Diff in sample <br> proportions]{style=\"color:green\"} | [$\\widehat{p}_1-\\widehat{p}_2$]{style=\"color:green\"} | [$\\sqrt{\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}}$]{style=\"color:red\"}\n\n:::\n\n",
    "supporting": [
      "12_Prop_inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}