{
  "hash": "1ba6d2d5ff28018b659d6449f3e545fc",
  "result": {
    "markdown": "---\ntitle: \"Lesson 15: Inference for a single proportion or difference of two (independent) proportions\"\nsubtitle: \"TB sections 8.1-8.2\"\nauthor: \"Meike Niederhausen and Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#3070BF\"\ndate: \"11/25/2024\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: Lesson 15 Slides\n    html-math-method: mathjax\n    highlight-style: arrow\nexecute:\n  echo: true\n  freeze: auto\n---\n\n\n\n\n# Learning Objectives\n\n1.  Understand how CLT applies to a binomial random variable\n\n2.  Construct and interpret confidence intervals for a single proportion.\n\n3.  Run a hypothesis test for a single proportion and interpret the results.\n\n\n::: {.cell}\n<style type=\"text/css\">\n.reveal code {\n  max-height: 100% !important;\n}\n</style>\n:::\n\n\n## Where are we?\n\n![](../img_slides/course_map.png){fig-align=\"center\"}\n\n## Moving to categorical outcomes\n\n-   Previously, we have discussed methods of inference for numerical data\n\n    -   Our outcomes were numerical values\n    -   We were doing inference of **means**\n    -   We found confidence intervals for means\n    -   We ran hypothesis tests for means\n\n-   The methods used can be extended to **categorical data**, such as binomial proportions or data in two-way tables\n\n-   Categorical data arise frequently in medical research because disease outcomes and patient characteristics are often recorded in natural categories such as types of treatment received, whether or not disease advanced to a later stage, or whether or not a patient responded initially to a treatment\n\n## From Lesson 5: Binomial random variable\n\n-   **One specific type of discrete random variable** is a binomial random variable\n\n::::: definition\n::: def-ttl\nBinomial random variable\n:::\n\n::: def-cont\n-   $X$ is a binomial random variable if it represents the number of successes in $n$ independent replications (or trials) of an experiment where\n\n    -   Each replicate has two possible outcomes: either **success** or **failure**\n    -   The probability of success is $p$\n    -   The probability of failure is $q=1-p$\n:::\n:::::\n\n-   A binomial random variable takes on values $0, 1, 2, \\dots, n$.\n\n-   If a r.v. $X$ is modeled by a Binomial distribution, then we write in shorthand $X \\sim \\text{Binom}(n,p)$\n\n-   Quick example: The number of heads in 3 tosses of a fair coin is a binomial random variable with parameters $n = 3$ and $p = 0.5$.\n\n## From Lesson 5: Binomial distribution\n\n::::: definition\n::: def-ttl\nDistribution of a **Binomial** random variable\n:::\n\n::: def-cont\nLet $X$ be the total number of successes in $n$ independent trials, each with probability $p$ of a success. Then probability of observing exactly $k$ successes in $n$ independent trials is\n\n$$P(X = x) = \\binom{n}{x} p^x (1-p)^{n-x},  x= 0, 1, 2, \\dots, n $$\n:::\n:::::\n\n-   The parameters of a binomial distribution are $p$ and $n$.\n\n-   If a r.v. $X$ is modeled by a binomial distribution, then we write in shorthand\n\n::::: orange\n::: orange-ttl\nMean and variance of a Binomial r.v\n:::\n\n::: orange-cont\nIf $X$ is a binomial r.v. with probability of success $p$, then $E(X) = np$ and $\\text{Var}(X)=np(1-p)$\n:::\n:::::\n\n## From Lesson 6: Normal Approximation of the Binomial Distribution\n\n-   Also known as: **Sampling distribution of** $\\widehat{p}$\n\n-   If $X\\sim \\text{Binomial}(n,p)$ and $np>10$ and $nq = n(1-p) > 10$\n\n    -   Ensures sample size ($n$) is moderately large and the $p$ is not too close to 0 or 1\n    -   Other resources use other criteria (like $npq>5$ or $np>5$)\n\n \n\n-   THEN approximately $$X\\sim \\text{Normal}\\big(\\mu_X = np, \\sigma_X = \\sqrt{np(1-p)} \\big)$$\n\n-   **Continuity Correction**: Applied to account for the fact that the binomial distribution is discrete, while the normal distribution is continuous\n\n    -   Adjust the binomial value (# of successes) by ±0.5 before calculating the normal probability.\n    -   For $P(X \\leq k)$ (Binomial), you would instead calculate $P(X \\leq k + 0.5)$ (Normal approx)\n    -   For $P(X \\geq k)$ (Binomial), you would instead calculate $P(X \\leq k - 0.5)$ (Normal approx)\n\n## Sampling distribution of $\\hat{p}$\n\n-   $\\hat{p}=\\frac{X}{n}$ where $X$ is the number of \"successes\" and $n$ is the sample size.\n-   $X \\sim Bin(n,p)$, where $p$ is the population proportion.\n-   For $n$ \"big enough\", the normal distribution can be used to approximate a binomial distribution:\n\n$$X \\sim N\\Big(\\mu = np, \\sigma = \\sqrt{np(1-p)} \\Big)$$\n\n-   Since $\\hat{p}=\\frac{X}{n}$ is a linear transformation of $X$, we have for large n:\n\n$$\\hat{p} \\sim N\\Big(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\Big)$$\n\n-   What is big enough? At least 10 successes and 10 failures are expected in the sample: $np \\geq 10$ and $n(1-p) \\geq 10$\n\n## For proportions: Population parameters vs. sample statistics\n\n::::: columns\n::: {.column width=\"50%\"}\n[**Population parameter**]{style=\"color:#C83532;\"}\n\n-   Proportion: $p$, $\\pi$ (\"pi\")\n\n \n\n-   Standard deviation: $\\sqrt{n \\cdot p \\cdot (1-p)}$\n-   Variance: $n \\cdot p \\cdot (1-p)$\n:::\n\n::: {.column width=\"50%\"}\n[**Sample statistic (point estimate)**]{style=\"color:#EF85B3;\"}\n\n-   Sample proportion: $\\hat{p}$ (\"p-hat\")\n\n \n\n-   Standard deviation: $\\sqrt{n \\cdot \\hat{p} \\cdot (1-\\hat{p})}$\n-   Variance: $n \\cdot \\hat{p} \\cdot (1-\\hat{p})$\n:::\n:::::\n\n \n\n## Where are we?\n\n::: {style=\"font-size: 90%;\"}\nCI's and hypothesis tests for different scenarios:\n\n$$\\text{point estimate} \\pm z^*(or~t^*)\\cdot SE,~~\\text{test stat} = \\frac{\\text{point estimate}-\\text{null value}}{SE}$$\n\n| Day | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| 10 | 5.1 | Pop mean | $\\mu$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$ |\n| 10 | 5.2 | Pop mean of paired diff | $\\mu_d$ or $\\delta$ | Sample mean of paired diff | $\\bar{x}_{d}$ | $\\frac{s_d}{\\sqrt{n}}$ |\n| 11 | 5.3 | [Diff in pop <br> means]{style=\"color:black\"} | [$\\mu_1-\\mu_2$]{style=\"color:black\"} | [Diff in sample <br> means]{style=\"color:black\"} | [$\\bar{x}_1 - \\bar{x}_2$]{style=\"color:black\"} | [$\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}$ or pooled]{style=\"color:black\"} |\n| 12 | 8.1 | [Pop proportion]{style=\"color:green\"} | [$p$]{style=\"color:green\"} | [Sample prop]{style=\"color:green\"} | [$\\widehat{p}$]{style=\"color:green\"} | [**???**]{style=\"color:red\"} |\n| 12 | 8.2 | [Diff in pop <br> proportions]{style=\"color:green\"} | [$p_1-p_2$]{style=\"color:green\"} | [Diff in sample <br> proportions]{style=\"color:green\"} | [$\\widehat{p}_1-\\widehat{p}_2$]{style=\"color:green\"} | [**???**]{style=\"color:red\"} |\n:::\n\n## Approaches to answer a research question\n\n-   **Research question is a generic form for a single proportion:** Is there evidence to support that the population proportion is different than $p_0$?\n\n:::::::::::::: columns\n:::::: {.column width=\"50%\"}\n::::: green2\n::: green2-ttl\nCalculate **CI for the proportion** $p$:\n:::\n\n::: green2-cont\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n$$\\hat{p} \\pm z^* \\cdot SE_{\\hat{p}} = \\hat{p} \\pm z^* \\cdot\\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n\n-   with $z^*$ = z-score that aligns with specific confidence interval\n:::\n:::::\n::::::\n\n::::::::: {.column width=\"50%\"}\n:::::::: pink\n::: pink-ttl\nRun a **hypothesis test**:\n:::\n\n:::::: pink-cont\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n::::: columns\n::: column\nHypotheses\n\n\\begin{align}\nH_0:& p = p_0 \\\\\nH_A:& p \\neq p_0 \\\\\n(or&~ <, >)\n\\end{align}\n:::\n\n::: column\nTest statistic\n\n$$\nz_{\\hat{p}} = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}}\n$$\n:::\n:::::\n::::::\n::::::::\n:::::::::\n::::::::::::::\n\n# LOB\n\n## Example: immune response to advanced melanoma\n\n-   Looking for therapies that trigger an immune response to advanced melanoma\n\n-   In a study where 52 patients were treated concurrently with two new therapies, nivolumab and ipilimumab, 21 had an immune response.[^1]\n\n-   Our outcome that we are measuring is whether or not each person has an immune response\n\n[^1]: Wolchok, et. al. \\textit{NEJM} (2013) 369(2): 122-33.\n\nQuestions that can be addressed with inference...\n\n-   What is the estimated population probability of immune response following concurrent therapy with nivolumab and ipilimumab?\n\n-   What is the 95% confidence interval for the estimated population probability of immune response following concurrent therapy with nivolumab and ipilimumab?\n\n-   In previous studies, the proportion of patients responding to one of these agents was 30% or less. Do these results suggest that the probability of response to concurrent therapy is better than 0.30?\n\n## Reference: Steps in a Hypothesis Test\n\n1.  Check the [**assumptions**]{style=\"color:#3070BF\"}\n\n2.  Set the [**level of significance**]{style=\"color:#3070BF\"} $\\alpha$\n\n3.  Specify the [**null**]{style=\"color:#3070BF\"} ( $H_0$ ) and [**alternative**]{style=\"color:#3070BF\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#3070BF\"}\n\n    1.  In symbols\n    2.  In words\n    3.  Alternative: one- or two-sided?\n\n4.  Calculate the [**test statistic**]{style=\"color:#3070BF\"}.\n\n5.  Calculate the [**p-value**]{style=\"color:#3070BF\"} based on the observed test statistic and its sampling distribution\n\n6.  Write a [**conclusion**]{style=\"color:#3070BF\"} to the hypothesis test\n\n    1.  Do we reject or fail to reject $H_0$?\n    2.  Write a conclusion in the context of the problem\n\n## Step 1: Check the assumptions (easier to do after Step 3)\n\nThe sampling distribution of $\\hat{p}$ is approximately normal when\n\n1.  The sample observations are independent, and\n\n2.  At least 10 successes and 10 failures are expected in the sample: $np_0 \\geq 10$ and $n(1-p_0) \\geq 10$.\\footnote{This condition is commonly referred to as the success-failure condition.}\n\n-   Since $p$ is unknown, it is necessary to substitute $p_0$ (the null value) for $p$ when using the standard error to conduct hypothesis tests\n    -   Because we are assuming the standard error of the null hypothesis!\n\n\n\n\n\n-   For the example, we have $p_0 = 0.30$\n    -   We check: $n p_0 = 52 \\cdot 0.3 = 15.6 > 10$\n    -   We check: $n (1- p_0) = 52 (1 -0.3)= 36.4 > 10$\n\n## Step 2: Set the level of significance\n\n-   **Before doing a hypothesis test**, we set a cut-off for how small the $p$-value should be in order to reject $H_0$.\n\n-   Typically choose $\\alpha = 0.05$\n\n \n\n-   See Lesson 11: Hypothesis Testing 1: Single-sample mean\n\n## Step 3: Null & Alternative Hypotheses (1/2)\n\n::::::::::: columns\n:::::: column\n::::: blue\n::: blue-ttl\nNotation for hypotheses (for paired data)\n:::\n\n::: blue-cont\n\\begin{aligned}\nH_0 &: p = p_0\\\\\n\\text{vs. } H_A&: p \\neq, <, \\textrm{or}, > p_0\n\\end{aligned}\n:::\n:::::\n::::::\n\n:::::: column\n::::: pink\n::: pink-ttl\nHypotheses test for example\n:::\n\n::: pink-cont\n\\begin{aligned}\nH_0 &: p = 0.30\\\\\n\\text{vs. } H_A&: p \\neq 0.30\n\\end{aligned}\n:::\n:::::\n::::::\n:::::::::::\n\nWe call $p_0$ the *null value* (hypothesized population mean difference from $H_0$)\n\n:::::::: columns\n::: {.column width=\"32%\"}\n$H_A: p \\neq p_0$\n\n-   not choosing a priori whether we believe the population proportion is greater or less than the null value $p_0$\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"32%\"}\n$H_A: p < p_0$\n\n-   believe the population proportion is **less** than the null value $p_0$\n:::\n\n::: {.column width=\"2%\"}\n:::\n\n::: {.column width=\"32%\"}\n$H_A: p > p_0$\n\n-   believe the population population proportion is **greater** than the null value $p_0$\n:::\n::::::::\n\n-   $H_A: p \\neq p_0$ is the most common option, since it's the most conservative\n\n## Step 3: Null & Alternative Hypotheses (2/2)\n\nNull and alternative hypotheses in **words** and in **symbols**.\n\n**One sample test**\n\n-   $H_0$: For individuals who have advanced melanoma and received a treatment of nivolumab and ipilimumab, the population proportion of immune response is 0.30\n\n-   $H_A$: For individuals who have advanced melanoma and received a treatment of nivolumab and ipilimumab, the population proportion of immune response is NOT 0.30\n\n\\begin{align}\nH_0:& p = 0.30\\\\\nH_A:& p \\neq 0.30\\\\\n\\end{align}\n\n## Step 4: Test statistic\n\nSampling distribution of $\\hat{p}$ if we assume $H_0: p=p_0$ is true:\n\n$$\\hat{p} \\sim N\\left(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\right) \n\\sim N\\left(\n\\mu_{\\hat{p}}=p_0, \\sigma_{\\hat{p}}=\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}\n\\right)$$\n\nTest statistic for a one sample proportion test:\n\n$$\n\\begin{aligned}\n\\text{test stat} = & \\frac{\\text{point estimate}-\\text{null value}}{SE}\\\\\nz_{\\hat{p}} = & \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}}\n\\end{aligned}\n$$\n\n## Step 4: Test statistic\n\nFrom our example: Recall that $\\hat{p} = \\dfrac{21}{52}= 0.4038$, $n=52$, and $p_0 = 0.30$\n\n\n\n\n\nThe test statistic is:\n\n$$\n\\begin{align}\nz_{\\hat{p}} &= \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}} = \\frac{21/52 - 0.30}{\\sqrt{\\frac{0.30\\cdot(1-0.30)}{52}}} = 1.6341143\n\\end{align}\n$$\n\n-   Let's see the z-score on a Z-distribution (Standard Normal curve)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Step 5: p-value\n\nThe [**p-value**]{style=\"color:#C83532\"} is the **probability** of obtaining a test statistic *just as extreme or more extreme* than the observed test statistic assuming the null hypothesis $H_0$ is true.\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\nCalculate the *p*-value:\n\n\n\n\n\n\\begin{align}\n2 &\\cdot P(\\hat{p}> 0.404) \\\\\n&= 2 \\cdot P\\left(Z_{\\hat{p}} > \\frac{0.404 - 0.30}{\\sqrt{\\frac{0.30\\cdot(1-0.30)}{52}}}\\right)\\\\\n&=2 \\cdot P(Z_{\\hat{p}} > 1.634)\\\\\n&= 0.1022348\n\\end{align}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pnorm(1.634, lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1022589\n```\n:::\n:::\n\n:::\n:::::\n\n## Step 4-5:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 21, n = 52, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  21 out of 52, null probability 0.5\nX-squared = 1.5577, df = 1, p-value = 0.212\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.2731269 0.5487141\nsample estimates:\n        p \n0.4038462 \n```\n:::\n:::\n\n\n## Step 6: Conclusion to hypothesis test\n\n\\begin{align}\nH_0:& p = 0.30\\\\\nH_A:& p \\neq 0.30\\\\\n\\end{align}\n\n-   Recall the $p$-value = 0.1022348\n-   Use $\\alpha$ = 0.05.\n-   Do we reject or fail to reject $H_0$?\n\n**Conclusion statement**:\n\n-   Stats class conclusion\n    -   There is insufficient evidence that the (population) proportion of individuals who had an immune response is different than 0.30 ( $p$-value = 0.102).\n-   More realistic manuscript conclusion:\n    -   In a sample of 52 individuals receiving treatment, 40.4% had an immune response, which is not different from 30% ( $p$-value = 0.102).\n\n# LOB\n\n## Conditions for one proportion: **test vs. CI**\n\n::::::::::: columns\n:::::: {.column width=\"50%\"}\n::::: green2\n::: green2-ttl\nConfidence interval conditions\n:::\n\n::: green2-cont\n1.  *Independent observations*\n    -   The observations were collected independently.\n\n<br>\n\n2.  The number of successes and failures is at least 10:\n\n$$n\\hat{p} \\ge 10, \\ \\ n(1-\\hat{p})\\ge 10$$\n:::\n:::::\n::::::\n\n:::::: {.column width=\"50%\"}\n::::: pink\n::: pink-ttl\nHypothesis test conditions\n:::\n\n::: pink-cont\n1.  *Independent observations*\n    -   The observations were collected independently.\n\n<br>\n\n2.  The number of **expected** successes and **expected** failures is at least 10.\n\n$$n p_0 \\ge 10, \\ \\ n(1-p_0)\\ge 10$$\n:::\n:::::\n::::::\n:::::::::::\n\n\n\n\n\n## 95% CI for population proportion\n\n::::: columns\n::: {.column width=\"50%\"}\nWhat to use for SE in CI formula?\n:::\n\n::: {.column width=\"50%\"}\n$$\\hat{p} \\pm z^* \\cdot SE_{\\hat{p}}$$\n:::\n:::::\n\n::::: columns\n::: {.column width=\"50%\"}\nSampling distribution of $\\hat{p}$:\n:::\n\n::: {.column width=\"50%\"}\n$$\\hat{p} \\sim N\\left(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\right)$$\n:::\n:::::\n\n::::: columns\n::: {.column width=\"50%\"}\nProblem: We don't know what $p$ is - it's what we're estimating with the CI.\\\nSolution: [approximate $p$ with $\\hat{p}$]{style=\"color:purple\"}:\n:::\n\n::: {.column width=\"50%\"}\n$$SE_{\\hat{p}} = \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n:::\n:::::\n\n## 95% CI for the population proportion\n\n95% CI for population mean difference $p$:\n\n\n\n\n\n::::: columns\n::: {.column width=\"50%\"}\n\\begin{align}\n\\hat{p} &\\pm z^* \\cdot SE_{\\hat{p}}\\\\\n\\hat{p} &\\pm z^* \\cdot \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}} \\\\ \n0.404 &\\pm 1.96\\cdot  \\sqrt{\\frac{0.404(1-0.404)}{52}}  \\\\\n0.404 &\\pm 1.96\\cdot 0.068\\\\\n0.404 &\\pm 0.133\\\\\n(0.27&, 0.537)\n\\end{align}\n:::\n\n::: {.column width=\"50%\"}\nUsed $z^*$ = `qnorm(0.975)` = 1.96\n\n \n\nConclusion:\\\nWe are 95% confident that the (population) proportion of individuals with an immune response is between 0.27 and 0.537.\n:::\n:::::\n\n## 95% CI for population proportion (using R)\n\nNEED TO COMPLETE!!!\n\n-   We can use R to get those same values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 21, n = 52, conf.level = 0.95, correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  21 out of 52, null probability 0.5\nX-squared = 1.5577, df = 1, p-value = 0.212\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.2731269 0.5487141\nsample estimates:\n        p \n0.4038462 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"We can tidy the output\"}\n# t.test(x = chol$DiffChol, mu = 0) %>% tidy() %>% gt() %>% \n#   tab_options(table.font.size = 35) # use a different size in your HW\n```\n:::\n\n\nConclusion:\\\nWe are 95% confident that the (population) proportion of individuals with an immune response is between 0.27 and 0.537.\n\n# LOB\n\n## Inference for difference of two independent proportions <br> $\\hat{p}_1-\\hat{p}_2$\n\n-   For means, we went from *inferences on single sample mean* to *inferences on difference in means from two independent samples*\n\n-   We can do the same thing for proportions\n\n-   We will go from *inferences on single sample proportion* to *inferences on difference in proportions from two independent samples*\n\n## Poll Everywhere question\n\n## For difference in proportions: Population parameters vs. sample statistics\n\n::::: columns\n::: {.column width=\"50%\"}\n[**Population parameter**]{style=\"color:#C83532;\"}\n\n-   Population 1 proportion: $p_1$, $\\pi_1$ (\"pi\")\n\n-   Population 2 proportion: $p_2$, $\\pi_2$ (\"pi\")  \n\n-   Difference in proportions: $p_1 - p_2$\n:::\n\n::: {.column width=\"50%\"}\n[**Sample statistic (point estimate)**]{style=\"color:#EF85B3;\"}\n\n-   Sample 1 proportion: $\\hat{p}_1$, $\\hat{\\pi}_1$ (\"pi\")\n\n-   Sample 1 proportion: $\\hat{p}_2$, $\\hat{\\pi}_2$ (\"pi\")  \n\n-   Difference in proportions: $\\hat{p}_1 - \\hat{p}_2$\n:::\n:::::\n\n \n\n## Sampling distribution of $\\hat{p}_1-\\hat{p}_2$\n\n-   $\\hat{p}_1=\\frac{X_1}{n_1}$ and $\\hat{p}_2=\\frac{X_2}{n_2}$,\n    -   $X_1$ & $X_2$ are the number of \"successes\"\n    -   $n_1$ & $n_2$ are the sample sizes of the 1st & 2nd samples\n\n \n\n-   Each $\\hat{p}$ can be approximated by a normal distribution, for \"big enough\" $n$\n-   Since the difference of independent normal random variables is also normal, it follows that for \"big enough\" $n_1$ and $n_2$\n\n$$\\hat{p}_1 - \\hat{p}_2 \\sim N \\left(\\mu_{\\hat{p}_1 - \\hat{p}_2} = p_1 - p_2, ~~\n\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} \n\\right)$$\n\n-   What is \"big enough\"? At least 10 successes and 10 failures are expected in the sample: $n_1p \\geq 10$, $n_1(1-p) \\geq 10$, $n_2p \\geq 10$, and $n_2(1-p) \\geq 10$\n\n# LOB\n\n## Motivating example: effectiveness of mammograms\n\nA 30-year study to investigate the effectiveness of mammograms versus a standard non-mammogram breast cancer exam was conducted in Canada with 89,835 participants. Each person was randomized to receive either annual mammograms or standard physical exams for breast cancer over a 5-year screening period.\n\nBy the end of the 25-year follow-up period, 1,005 people died from breast cancer. The results are summarized in the following table.\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Displaying the contingency table in R\"}\nBC %>% tabyl(Group, Death) %>% \n  adorn_totals(where = c(\"row\", \"col\")) %>% \n  gt() %>% \n  tab_stubhead(label = \"Group\") %>%\n  tab_spanner(label = \"Death from breast cancer?\", \n              columns = c(\"Yes\", \"No\")) %>%\n  tab_options(table.font.size = 45)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ldqxsekkaz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ldqxsekkaz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ldqxsekkaz thead, #ldqxsekkaz tbody, #ldqxsekkaz tfoot, #ldqxsekkaz tr, #ldqxsekkaz td, #ldqxsekkaz th {\n  border-style: none;\n}\n\n#ldqxsekkaz p {\n  margin: 0;\n  padding: 0;\n}\n\n#ldqxsekkaz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 45px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ldqxsekkaz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ldqxsekkaz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ldqxsekkaz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ldqxsekkaz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ldqxsekkaz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ldqxsekkaz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ldqxsekkaz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ldqxsekkaz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ldqxsekkaz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ldqxsekkaz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ldqxsekkaz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ldqxsekkaz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ldqxsekkaz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ldqxsekkaz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ldqxsekkaz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ldqxsekkaz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ldqxsekkaz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ldqxsekkaz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ldqxsekkaz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ldqxsekkaz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ldqxsekkaz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ldqxsekkaz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ldqxsekkaz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ldqxsekkaz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ldqxsekkaz .gt_left {\n  text-align: left;\n}\n\n#ldqxsekkaz .gt_center {\n  text-align: center;\n}\n\n#ldqxsekkaz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ldqxsekkaz .gt_font_normal {\n  font-weight: normal;\n}\n\n#ldqxsekkaz .gt_font_bold {\n  font-weight: bold;\n}\n\n#ldqxsekkaz .gt_font_italic {\n  font-style: italic;\n}\n\n#ldqxsekkaz .gt_super {\n  font-size: 65%;\n}\n\n#ldqxsekkaz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ldqxsekkaz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ldqxsekkaz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ldqxsekkaz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ldqxsekkaz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ldqxsekkaz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ldqxsekkaz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ldqxsekkaz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ldqxsekkaz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Death from breast cancer?\">\n        <div class=\"gt_column_spanner\">Death from breast cancer?</div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"Total\">Total</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Yes\">Yes</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"No\">No</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Control Group</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">505</td>\n<td headers=\"No\" class=\"gt_row gt_right\">44405</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">44910</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Mammogram Group</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">500</td>\n<td headers=\"No\" class=\"gt_row gt_right\">44425</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">44925</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"Yes\" class=\"gt_row gt_right\">1005</td>\n<td headers=\"No\" class=\"gt_row gt_right\">88830</td>\n<td headers=\"Total\" class=\"gt_row gt_right\">89835</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Effectiveness of mammograms...\n\n\\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#analyze the data\nprop.test(x = c(500, 505), n = c(500 + 44425, 505 + 44405), correct=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(500, 505) out of c(500 + 44425, 505 + 44405)\nX-squared = 0.01748, df = 1, p-value = 0.8948\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.001512853  0.001282751\nsample estimates:\n    prop 1     prop 2 \n0.01112966 0.01124471 \n```\n:::\n:::\n\n\n## Reference: Steps in a Hypothesis Test\n\n1.  Check the [**assumptions**]{style=\"color:#3070BF\"}\n\n2.  Set the [**level of significance**]{style=\"color:#3070BF\"} $\\alpha$\n\n3.  Specify the [**null**]{style=\"color:#3070BF\"} ( $H_0$ ) and [**alternative**]{style=\"color:#3070BF\"} ( $H_A$ ) [**hypotheses**]{style=\"color:#3070BF\"}\n\n    1.  In symbols\n    2.  In words\n    3.  Alternative: one- or two-sided?\n\n4.  Calculate the [**test statistic**]{style=\"color:#3070BF\"}.\n\n5.  Calculate the [**p-value**]{style=\"color:#3070BF\"} based on the observed test statistic and its sampling distribution\n\n6.  Write a [**conclusion**]{style=\"color:#3070BF\"} to the hypothesis test\n\n    1.  Do we reject or fail to reject $H_0$?\n    2.  Write a conclusion in the context of the problem\n\n## Before we start, we need to calculate the pooled proportion\n\n- Often, our null hypothesis is that the two proportions are equal\n  - And that both populations are the same\n\n- Thus, we calculate a pooled proportion to represent the proportion under the null distribution\n\n$$\\text{pooled proportion} = \\hat{p}_{pool} = \\dfrac{\\text{total number of successes} }{ \\text{total number of cases}} = \\frac{x_1+x_2}{n_1+n_2}$$\n\n- In this example:\n\n$$\\hat{p}_{pool} = \\frac{x_1+x_2}{n_1+n_2} = \\frac{500 + 505}{(500 + 44425) + (505 + 44405)} = 0.01119$$\n\n## Step 1: Check the assumptions\n\n**Conditions**:\n\n-   *Independent observations & samples*\n    -   The observations were collected independently.\n    -   In particular, observations from the two groups weren't paired in any meaningful way.\n-   The number of expected successes and expected failures is at least 10 *for each group* - using the pooled proportion:\n    -   $n_1\\hat{p}_{pool} \\ge 10, \\ \\ n_1(1-\\hat{p}_{pool}) \\ge 10$\n    -   $n_2\\hat{p}_{pool} \\ge 10, \\ \\ n_2(1-\\hat{p}_{pool}) \\ge 10$\n    \n\n\n\n\n- In the example, we check:\n    -   $n_1\\hat{p}_{pool}=44925 \\cdot 0.0112 = 502.5839 \\ge 10$\n    -   $n_1(1-\\hat{p}_{pool})=  44925 (1-0.0112) = 44422.42 \\ge 10$\n    -   $n_2\\hat{p}_{pool}=44910 \\cdot 0.0112 = 502.4161 \\ge 10$\n    -   $n_2(1-\\hat{p}_{pool})=  44910 (1-0.0112) = 44407.58 \\ge 10$\n\n## Step 3: Null and Alternative Hypothesis test\n\n**Two samples test**\n\n-   $H_0$: The difference in population proportions of deaths from breast cancer among people who received annual mammograms and annual physical check-ups is 0.\n\n-   $H_A$: The difference in population proportions of deaths from breast cancer among people who received annual mammograms and annual physical check-ups is not 0.\n\n\\begin{align}\nH_0:& p_{mamm} - p_{ctrl} = 0\\\\\nH_A:& p_{mamm} - p_{ctrl} \\neq 0\\\\\n\\end{align}\n\n## Step 4: Test statistic (1/2)\n\nSampling distribution of $\\hat{p}_1 - \\hat{p}_2$: $$\\hat{p}_1 - \\hat{p}_2 \\sim N \\left(\\mu_{\\hat{p}_1 - \\hat{p}_2} = p_1 - p_2, ~~\n\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} \n\\right)$$\n\nSince we assume $H_0: p_1 - p_2 = 0$ is true, we \"pool\" the proportions of the two samples to calculate the SE:\n\n$$\\text{pooled proportion} = \\hat{p}_{pool} = \\dfrac{\\text{total number of successes} }{ \\text{total number of cases}} = \\frac{x_1+x_2}{n_1+n_2}$$\n\nTest statistic:\n\n$$\n\\text{test statistic} = z_{\\hat{p}_1 - \\hat{p}_2} = \\frac{\\hat{p}_1 - \\hat{p}_2 - 0}{\\sqrt{\\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_1} + \\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_2}}}\n$$\n\n## Step 4: Test statistic\n\nFrom our example: Recall that $\\hat{p}_1 = \\dfrac{500}{44925}= 0.0111$, $\\hat{p}_2 = \\dfrac{505}{44910}= 0.0112$, $n_1=44925$, $n_2=44910$, and $\\hat{p}_{pool} = 0.01119$\n\n\n\n\n\nThe test statistic is:\n\n$$\n\\begin{align}\nz_{\\hat{p}_1 - \\hat{p}_2} = \\frac{\\hat{p}_1 - \\hat{p}_2 - 0}{\\sqrt{\\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_1} + \\frac{\\hat{p}_{pool}\\cdot(1-\\hat{p}_{pool})}{n_2}}} = \\frac{0.0111 -0.0112}{\\sqrt{\\frac{0.01119\\cdot(1-0.01119)}{44925} + \\frac{0.01119\\cdot(1-0.01119)}{44910}}} = -0.163933\n\\end{align}\n$$\n\n-   Let's see the z-score on a Z-distribution (Standard Normal curve)\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-22-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n## Step 5: p-value\n\nThe [**p-value**]{style=\"color:#C83532\"} is the **probability** of obtaining a test statistic *just as extreme or more extreme* than the observed test statistic assuming the null hypothesis $H_0$ is true.\n\n::::: columns\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](15_Prop_inference_files/figure-revealjs/unnamed-chunk-24-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"55%\"}\nCalculate the *p*-value:\n\n\n\n\n\n\\begin{align}\n& 2 \\cdot P(\\hat{p}_1 - \\hat{p}_2< 0.0111 - 0.0112) \\\\\n&= P\\left(Z_{\\hat{p}_1 - \\hat{p}_2} < \\frac{0.0111 - 0.0112}{\\sqrt{\\frac{0.01119\\cdot(1-0.01119)}{44925} + \\frac{0.01119\\cdot(1-0.01119)}{44910}}}\\right) \\\\\n&= 2 \\cdot P(Z_{\\hat{p}} > -0.164)\\\\\n&= 0.8697839\n\\end{align}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pnorm(-0.1639)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8698099\n```\n:::\n:::\n\n:::\n:::::\n\n## Step 5: Conclusion to hypothesis test\n\n\\begin{align}\nH_0:& p_{mamm} - p_{ctrl} = 0\\\\\nH_A:& p_{mamm} - p_{ctrl} \\neq 0\\\\\n\\end{align}\n\n-   Recall the $p$-value = 0.8698\n-   Use $\\alpha$ = 0.05\n-   Do we reject or fail to reject $H_0$?\n\n**Conclusion statement**:\n\n-   Stats class conclusion\n    -   There is insufficient evidence that the difference in (population) proportions of deaths from breast cancer among people who received annual mammograms and annual physical check-ups different ($p$-value = 0.87).\n-   More realistic manuscript conclusion:\n    -   1.11% of people receiving annual mammograms (n=44925) and 1.12% of people receiving annual physical exams (n=44925) died from breast cancer ($p$-value = 0.87).\n\n# Lob\n\n## Conditions for difference in proportions: **test vs. CI**\n\n::::::::::: columns\n:::::: {.column width=\"50%\"}\n::::: green2\n::: green2-ttl\nConfidence interval conditions\n:::\n\n::: green2-cont\n1.  *Independent observations & samples*\n    -   The observations were collected independently.\n    -   In particular, observations from the two groups weren't paired in any meaningful way.\n\n<br>\n\n2.  The number of successes and failures is at least 10 *for each group*.\n    -   $n_1\\hat{p}_1 \\ge 10, \\ \\ n_1(1-\\hat{p}_1) \\ge 10$\n    -   $n_2\\hat{p}_2 \\ge 10, \\ \\ n_2(1-\\hat{p}_2) \\ge 10$\n:::\n:::::\n::::::\n\n:::::: {.column width=\"50%\"}\n::::: pink\n::: pink-ttl\nHypothesis test conditions\n:::\n\n::: pink-cont\n1.  *Independent observations & samples*\n    -   The observations were collected independently.\n    -   In particular, observations from the two groups weren't paired in any meaningful way.\n\n<br>\n\n2.  The number of **expected** successes and **expected** failures is at least 10 *for each group* - using the pooled proportion:\n    -   $n_1\\hat{p}_{pool} \\ge 10, \\ \\ n_1(1-\\hat{p}_{pool}) \\ge 10$\n    -   $n_2\\hat{p}_{pool} \\ge 10, \\ \\ n_2(1-\\hat{p}_{pool}) \\ge 10$\n:::\n:::::\n::::::\n:::::::::::\n\n\n\n\n\n## 95% CI for population difference in proportions\n\n::::: columns\n::: {.column width=\"50%\"}\nWhat to use for SE in CI formula?\n:::\n\n::: {.column width=\"50%\"}\n$$\\hat{p}_1 - \\hat{p}_2 \\pm z^* \\cdot SE_{\\hat{p}_1 - \\hat{p}_2}$$\n:::\n:::::\n\n::::: columns\n::: {.column width=\"50%\"}\nSE in sampling distribution of $\\hat{p}_1 - \\hat{p}_2$\n:::\n\n::: {.column width=\"50%\"}\n$$\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} $$\n:::\n:::::\n\n::::: columns\n::: {.column width=\"50%\"}\nProblem: We don't know what $p$ is - it's what we're estimating with the CI.\\\nSolution: [approximate $p_1$, $p_2$ with $\\hat{p}_1$, $\\hat{p}_2$]{style=\"color:purple\"}:\n:::\n\n::: {.column width=\"50%\"}\n$$SE_{\\hat{p}_1 - \\hat{p}_2} = \\sqrt{\n\\frac{\\hat{p}_1\\cdot(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2\\cdot(1-\\hat{p}_2)}{n_2}}$$\n:::\n:::::\n\n## 95% CI for the population difference in proportions\n\n95% CI for population mean difference $p_1 - p_2$:\n\n\n\n\n\n\\begin{align}\n\\hat{p}_1 - \\hat{p}_2 &\\pm z^* \\cdot SE_{\\hat{p}_1 - \\hat{p}_2}\\\\\n\\hat{p}_1 - \\hat{p}_2 &\\pm z^* \\cdot \\sqrt{\n\\frac{\\hat{p}_1\\cdot(1-\\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2\\cdot(1-\\hat{p}_2)}{n_2}} \\\\\n0.01113 - 0.01124 &\\pm 1.96 \\cdot \\sqrt{\\frac{0.01113\\cdot(1-0.01113)}{44925} + \\frac{0.01124\\cdot(1-0.01124)}{44910}}\\\\\n0.35 &\\pm 1.96\\cdot 0.001\\\\\n0.35 &\\pm 0.002\\\\\n(-0.002&, 0.002)\n\\end{align}\n\nUsed $z^*$ = `qnorm(0.975)` = 1.96\n\n \n\n**Interpretation**:\\\nWe are 95% confident that the difference in (population) proportions of young male college and noncollege students that participated in sports betting in the previous year is in (-0.127, 0.106).\n\n\n## 95% CI for the population difference in proportions\n\nNEED TO COMPLETE!!!\n\n-   We can use R to get those same values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 21, n = 52, conf.level = 0.95, correct = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test with continuity correction\n\ndata:  21 out of 52, null probability 0.5\nX-squared = 1.5577, df = 1, p-value = 0.212\nalternative hypothesis: true p is not equal to 0.5\n95 percent confidence interval:\n 0.2731269 0.5487141\nsample estimates:\n        p \n0.4038462 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"We can tidy the output\"}\n# t.test(x = chol$DiffChol, mu = 0) %>% tidy() %>% gt() %>% \n#   tab_options(table.font.size = 35) # use a different size in your HW\n```\n:::\n\n\nConclusion:\\\nWe are 95% confident that the (population) proportion of individuals with an immune response is between -0.002 and 0.002.\n\n\n# R: 1- and 2-sample proportions tests\n\n`prop.test(x, n, p = NULL,`\\\n      `alternative = c(\"two.sided\", \"less\", \"greater\"),`\\\n      `conf.level = 0.95,`\\\n      `correct = TRUE)`\n\n-   2 options for data input\n    1.  Summary counts\n        -   `x` = vector with counts of \"successes\"\n        -   `n` = vector with sample size in each group\n    2.  Dataset\n        -   `x = table()` of dataset\n        -   Need to create a dataset based on the summary stats if do not already have one\n-   Continuity correction\n\n# R: 1-sample proportion test\n\n\"1-prop z-test\"\n\n## Summary stats input for 1-sample proportion test\n\n**Example:** A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.\\\nTest $H_0: p=0.36$ vs. $H_A: p \\neq 0.36$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.35*269 # number of \"successes\"; round this value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269,              # x = # successes & n = sample size\n          p = 0.36,                     # null value p0\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)              # no continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  94 out of 269, null probability 0.36\nX-squared = 0.13014, df = 1, p-value = 0.7183\nalternative hypothesis: true p is not equal to 0.36\n95 percent confidence interval:\n 0.2949476 0.4081767\nsample estimates:\n        p \n0.3494424 \n```\n:::\n:::\n\n\nCan `tidy()` test output:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269, p = 0.36, alternative = \"two.sided\", correct = FALSE) %>% \n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"jjqbcjfoxs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jjqbcjfoxs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jjqbcjfoxs thead, #jjqbcjfoxs tbody, #jjqbcjfoxs tfoot, #jjqbcjfoxs tr, #jjqbcjfoxs td, #jjqbcjfoxs th {\n  border-style: none;\n}\n\n#jjqbcjfoxs p {\n  margin: 0;\n  padding: 0;\n}\n\n#jjqbcjfoxs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jjqbcjfoxs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jjqbcjfoxs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jjqbcjfoxs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jjqbcjfoxs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jjqbcjfoxs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jjqbcjfoxs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jjqbcjfoxs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jjqbcjfoxs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jjqbcjfoxs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jjqbcjfoxs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jjqbcjfoxs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jjqbcjfoxs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jjqbcjfoxs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jjqbcjfoxs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jjqbcjfoxs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jjqbcjfoxs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jjqbcjfoxs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jjqbcjfoxs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jjqbcjfoxs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jjqbcjfoxs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jjqbcjfoxs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jjqbcjfoxs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jjqbcjfoxs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jjqbcjfoxs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jjqbcjfoxs .gt_left {\n  text-align: left;\n}\n\n#jjqbcjfoxs .gt_center {\n  text-align: center;\n}\n\n#jjqbcjfoxs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jjqbcjfoxs .gt_font_normal {\n  font-weight: normal;\n}\n\n#jjqbcjfoxs .gt_font_bold {\n  font-weight: bold;\n}\n\n#jjqbcjfoxs .gt_font_italic {\n  font-style: italic;\n}\n\n#jjqbcjfoxs .gt_super {\n  font-size: 65%;\n}\n\n#jjqbcjfoxs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jjqbcjfoxs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jjqbcjfoxs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jjqbcjfoxs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jjqbcjfoxs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jjqbcjfoxs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jjqbcjfoxs .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jjqbcjfoxs .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jjqbcjfoxs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.1301373</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7182897</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2949476</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4081767</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Dataset input for 1-sample proportion test (1/2)\n\n::::: columns\n::: {.column width=\"50%\"}\nSince we don't have a dataset, we first need to create a dataset based on the results:\n\n> \"out of 269 male college students, 35% had participated in sports betting in the previous year\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.35*269 # number of \"successes\"; round this value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\nSportsBet1 <- tibble(\n  Coll = c(rep(\"Bet\", 94),\n           rep(\"NotBet\",269-94))\n  )\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(SportsBet1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 269\nColumns: 1\n$ Coll <chr> \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"B…\n```\n:::\n\n```{.r .cell-code}\nSportsBet1 %>% tabyl(Coll)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Coll   n   percent\n    Bet  94 0.3494424\n NotBet 175 0.6505576\n```\n:::\n:::\n\n\n<br>\n\nR code for proportions test requires input as a base R `table`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(SportsBet1$Coll)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Bet NotBet \n    94    175 \n```\n:::\n:::\n\n:::\n:::::\n\n## Dataset input for 1-sample proportion test (2/2)\n\n-   When using a dataset, `prop.test` requires the input `x` to be a table\n-   Note that we do not also specify `n` since the table already includes all needed information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet1$Coll),   # table() of data\n          p = 0.36,                     # null value p0\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)              # no continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(SportsBet1$Coll), null probability 0.36\nX-squared = 0.13014, df = 1, p-value = 0.7183\nalternative hypothesis: true p is not equal to 0.36\n95 percent confidence interval:\n 0.2949476 0.4081767\nsample estimates:\n        p \n0.3494424 \n```\n:::\n:::\n\n\nCompare output with summary stats method:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269,              # x = # successes & n = sample size\n          p = 0.36,                     # null value p0\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)  %>%         # no continuity correction\n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"tsyhthflte\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tsyhthflte table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tsyhthflte thead, #tsyhthflte tbody, #tsyhthflte tfoot, #tsyhthflte tr, #tsyhthflte td, #tsyhthflte th {\n  border-style: none;\n}\n\n#tsyhthflte p {\n  margin: 0;\n  padding: 0;\n}\n\n#tsyhthflte .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tsyhthflte .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tsyhthflte .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tsyhthflte .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tsyhthflte .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tsyhthflte .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tsyhthflte .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tsyhthflte .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tsyhthflte .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tsyhthflte .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tsyhthflte .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tsyhthflte .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tsyhthflte .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tsyhthflte .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tsyhthflte .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tsyhthflte .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tsyhthflte .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tsyhthflte .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tsyhthflte .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tsyhthflte .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tsyhthflte .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tsyhthflte .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tsyhthflte .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tsyhthflte .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tsyhthflte .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tsyhthflte .gt_left {\n  text-align: left;\n}\n\n#tsyhthflte .gt_center {\n  text-align: center;\n}\n\n#tsyhthflte .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tsyhthflte .gt_font_normal {\n  font-weight: normal;\n}\n\n#tsyhthflte .gt_font_bold {\n  font-weight: bold;\n}\n\n#tsyhthflte .gt_font_italic {\n  font-style: italic;\n}\n\n#tsyhthflte .gt_super {\n  font-size: 65%;\n}\n\n#tsyhthflte .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tsyhthflte .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tsyhthflte .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tsyhthflte .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tsyhthflte .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tsyhthflte .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tsyhthflte .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tsyhthflte .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tsyhthflte div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.1301373</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7182897</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2949476</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4081767</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Continuity correction: 1-prop z-test with vs. without CC\n\n-   Recall that when we approximated the\n-   binomial distribution with a normal distribution to calculate a probability,\n-   that we included a continuity correction (CC)\n-   to account for approximating a discrete distribution with a continuous distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269, p = 0.36, alternative = \"two.sided\", \n          correct = FALSE) %>% \n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"kfnpngrrqn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kfnpngrrqn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kfnpngrrqn thead, #kfnpngrrqn tbody, #kfnpngrrqn tfoot, #kfnpngrrqn tr, #kfnpngrrqn td, #kfnpngrrqn th {\n  border-style: none;\n}\n\n#kfnpngrrqn p {\n  margin: 0;\n  padding: 0;\n}\n\n#kfnpngrrqn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kfnpngrrqn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kfnpngrrqn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kfnpngrrqn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kfnpngrrqn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kfnpngrrqn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kfnpngrrqn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kfnpngrrqn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kfnpngrrqn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kfnpngrrqn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kfnpngrrqn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kfnpngrrqn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kfnpngrrqn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kfnpngrrqn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kfnpngrrqn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kfnpngrrqn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kfnpngrrqn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kfnpngrrqn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kfnpngrrqn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kfnpngrrqn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kfnpngrrqn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kfnpngrrqn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kfnpngrrqn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kfnpngrrqn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kfnpngrrqn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kfnpngrrqn .gt_left {\n  text-align: left;\n}\n\n#kfnpngrrqn .gt_center {\n  text-align: center;\n}\n\n#kfnpngrrqn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kfnpngrrqn .gt_font_normal {\n  font-weight: normal;\n}\n\n#kfnpngrrqn .gt_font_bold {\n  font-weight: bold;\n}\n\n#kfnpngrrqn .gt_font_italic {\n  font-style: italic;\n}\n\n#kfnpngrrqn .gt_super {\n  font-size: 65%;\n}\n\n#kfnpngrrqn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kfnpngrrqn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kfnpngrrqn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kfnpngrrqn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kfnpngrrqn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kfnpngrrqn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kfnpngrrqn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kfnpngrrqn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kfnpngrrqn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.1301373</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7182897</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2949476</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4081767</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = 94, n = 269, p = 0.36, alternative = \"two.sided\", \n          correct = TRUE) %>% \n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"uyptfprcak\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uyptfprcak table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uyptfprcak thead, #uyptfprcak tbody, #uyptfprcak tfoot, #uyptfprcak tr, #uyptfprcak td, #uyptfprcak th {\n  border-style: none;\n}\n\n#uyptfprcak p {\n  margin: 0;\n  padding: 0;\n}\n\n#uyptfprcak .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uyptfprcak .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uyptfprcak .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uyptfprcak .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uyptfprcak .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uyptfprcak .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uyptfprcak .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uyptfprcak .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uyptfprcak .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uyptfprcak .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uyptfprcak .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uyptfprcak .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uyptfprcak .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uyptfprcak .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uyptfprcak .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uyptfprcak .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uyptfprcak .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uyptfprcak .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uyptfprcak .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uyptfprcak .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uyptfprcak .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uyptfprcak .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uyptfprcak .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uyptfprcak .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uyptfprcak .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uyptfprcak .gt_left {\n  text-align: left;\n}\n\n#uyptfprcak .gt_center {\n  text-align: center;\n}\n\n#uyptfprcak .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uyptfprcak .gt_font_normal {\n  font-weight: normal;\n}\n\n#uyptfprcak .gt_font_bold {\n  font-weight: bold;\n}\n\n#uyptfprcak .gt_font_italic {\n  font-style: italic;\n}\n\n#uyptfprcak .gt_super {\n  font-size: 65%;\n}\n\n#uyptfprcak .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uyptfprcak .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uyptfprcak .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uyptfprcak .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uyptfprcak .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uyptfprcak .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uyptfprcak .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uyptfprcak .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uyptfprcak div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.08834805</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7662879</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2931841</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4100774</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test with continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nDifferences are small when sample sizes are large.\n\n# R: 2-samples proportion test\n\n\"2-prop z-test\"\n\n## Summary stats input for 2-samples proportion test\n\n**Example:** A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had. Test $H_0: p_{coll} - p_{noncoll} = 0$ vs. $H_A: p_{coll} - p_{noncoll} \\neq 0$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# round the number of successes:\n.35*269 # number of \"successes\" in college students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\n.36*214 # number of \"successes\" in noncollege students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77.04\n```\n:::\n\n```{.r .cell-code}\nNmbrBet <- c(94, 77)                    # vector for # of successes in each group\nTotalNmbr <- c(269, 214)                # vector for sample size in each group\n\nprop.test(x = NmbrBet,                  # x is # of successes in each group \n          n = TotalNmbr,                # n is sample size in each group\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE)              # no continuity correction\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  NmbrBet out of TotalNmbr\nX-squared = 0.05605, df = 1, p-value = 0.8129\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.09628540  0.07554399\nsample estimates:\n   prop 1    prop 2 \n0.3494424 0.3598131 \n```\n:::\n:::\n\n\n## Dataset input for 2-samples proportion test (1/2)\n\n::::: columns\n::: {.column width=\"50%\"}\nSince we don't have a dataset, we first need to create a dataset based on the results:\n\n> \"out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# round the number of successes:\n.35*269 # college students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\n.36*214 # noncollege students\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77.04\n```\n:::\n\n```{.r .cell-code}\nSportsBet2 <- tibble(\n  Group = c(rep(\"College\", 269), \n         rep(\"NonCollege\", 214)),\n  Bet = c(rep(\"yes\", 94), \n          rep(\"no\", 269-94),\n          rep(\"yes\", 77), \n          rep(\"no\", 214-77))\n)\n```\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(SportsBet2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 483\nColumns: 2\n$ Group <chr> \"College\", \"College\", \"College\", \"College\", \"College\", \"College\"…\n$ Bet   <chr> \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"…\n```\n:::\n\n```{.r .cell-code}\nSportsBet2 %>% tabyl(Group, Bet)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Group  no yes\n    College 175  94\n NonCollege 137  77\n```\n:::\n:::\n\n\n<br>\n\nR code for proportions test requires input as a base R `table`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(SportsBet2$Group, \n      SportsBet2$Bet)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            \n              no yes\n  College    175  94\n  NonCollege 137  77\n```\n:::\n:::\n\n:::\n:::::\n\n## Dataset input for 2-samples proportion test (2/2)\n\n-   When using a dataset, `prop.test` requires the input `x` to be a table\n-   Note that we do not also specify `n` since the table already includes all needed information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet2$Group, SportsBet2$Bet),\n       alternative = \"two.sided\",\n       correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  table(SportsBet2$Group, SportsBet2$Bet)\nX-squared = 0.05605, df = 1, p-value = 0.8129\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.07554399  0.09628540\nsample estimates:\n   prop 1    prop 2 \n0.6505576 0.6401869 \n```\n:::\n:::\n\n\nCompare output with summary stats method:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = NmbrBet,                  # x is # of successes in each group \n          n = TotalNmbr,                # n is sample size in each group\n          alternative = \"two.sided\",    # 2-sided alternative\n          correct = FALSE) %>%          # no continuity correction\n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hqyzmfdxqw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#hqyzmfdxqw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#hqyzmfdxqw thead, #hqyzmfdxqw tbody, #hqyzmfdxqw tfoot, #hqyzmfdxqw tr, #hqyzmfdxqw td, #hqyzmfdxqw th {\n  border-style: none;\n}\n\n#hqyzmfdxqw p {\n  margin: 0;\n  padding: 0;\n}\n\n#hqyzmfdxqw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#hqyzmfdxqw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hqyzmfdxqw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hqyzmfdxqw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hqyzmfdxqw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hqyzmfdxqw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hqyzmfdxqw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hqyzmfdxqw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hqyzmfdxqw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#hqyzmfdxqw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#hqyzmfdxqw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hqyzmfdxqw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hqyzmfdxqw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hqyzmfdxqw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hqyzmfdxqw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hqyzmfdxqw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hqyzmfdxqw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hqyzmfdxqw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#hqyzmfdxqw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hqyzmfdxqw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hqyzmfdxqw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hqyzmfdxqw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hqyzmfdxqw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hqyzmfdxqw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hqyzmfdxqw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hqyzmfdxqw .gt_left {\n  text-align: left;\n}\n\n#hqyzmfdxqw .gt_center {\n  text-align: center;\n}\n\n#hqyzmfdxqw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hqyzmfdxqw .gt_font_normal {\n  font-weight: normal;\n}\n\n#hqyzmfdxqw .gt_font_bold {\n  font-weight: bold;\n}\n\n#hqyzmfdxqw .gt_font_italic {\n  font-style: italic;\n}\n\n#hqyzmfdxqw .gt_super {\n  font-size: 65%;\n}\n\n#hqyzmfdxqw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#hqyzmfdxqw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hqyzmfdxqw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hqyzmfdxqw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hqyzmfdxqw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hqyzmfdxqw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hqyzmfdxqw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#hqyzmfdxqw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#hqyzmfdxqw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.3598131</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.05605044</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8128509</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.0962854</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.07554399</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Continuity correction: 2-prop z-test with vs. without CC\n\n-   Recall that when we approximated the\n-   binomial distribution with a normal distribution to calculate a probability,\n-   that we included a continuity correction (CC)\n-   to account for approximating a discrete distribution with a continuous distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = NmbrBet, n = TotalNmbr, alternative = \"two.sided\", \n          correct = FALSE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"seapexzseb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#seapexzseb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#seapexzseb thead, #seapexzseb tbody, #seapexzseb tfoot, #seapexzseb tr, #seapexzseb td, #seapexzseb th {\n  border-style: none;\n}\n\n#seapexzseb p {\n  margin: 0;\n  padding: 0;\n}\n\n#seapexzseb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#seapexzseb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#seapexzseb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#seapexzseb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#seapexzseb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#seapexzseb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#seapexzseb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#seapexzseb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#seapexzseb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#seapexzseb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#seapexzseb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#seapexzseb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#seapexzseb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#seapexzseb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#seapexzseb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#seapexzseb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#seapexzseb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#seapexzseb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#seapexzseb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#seapexzseb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#seapexzseb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#seapexzseb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#seapexzseb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#seapexzseb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#seapexzseb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#seapexzseb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#seapexzseb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#seapexzseb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#seapexzseb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#seapexzseb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#seapexzseb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#seapexzseb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#seapexzseb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#seapexzseb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#seapexzseb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#seapexzseb .gt_left {\n  text-align: left;\n}\n\n#seapexzseb .gt_center {\n  text-align: center;\n}\n\n#seapexzseb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#seapexzseb .gt_font_normal {\n  font-weight: normal;\n}\n\n#seapexzseb .gt_font_bold {\n  font-weight: bold;\n}\n\n#seapexzseb .gt_font_italic {\n  font-style: italic;\n}\n\n#seapexzseb .gt_super {\n  font-size: 65%;\n}\n\n#seapexzseb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#seapexzseb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#seapexzseb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#seapexzseb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#seapexzseb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#seapexzseb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#seapexzseb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#seapexzseb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#seapexzseb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.3598131</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.05605044</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8128509</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.0962854</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.07554399</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = NmbrBet, n = TotalNmbr, alternative = \"two.sided\", \n          correct = TRUE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"sotjnmlnpf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sotjnmlnpf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sotjnmlnpf thead, #sotjnmlnpf tbody, #sotjnmlnpf tfoot, #sotjnmlnpf tr, #sotjnmlnpf td, #sotjnmlnpf th {\n  border-style: none;\n}\n\n#sotjnmlnpf p {\n  margin: 0;\n  padding: 0;\n}\n\n#sotjnmlnpf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sotjnmlnpf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sotjnmlnpf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sotjnmlnpf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sotjnmlnpf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sotjnmlnpf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sotjnmlnpf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sotjnmlnpf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sotjnmlnpf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sotjnmlnpf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sotjnmlnpf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sotjnmlnpf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sotjnmlnpf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sotjnmlnpf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sotjnmlnpf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sotjnmlnpf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sotjnmlnpf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sotjnmlnpf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sotjnmlnpf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sotjnmlnpf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sotjnmlnpf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sotjnmlnpf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sotjnmlnpf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sotjnmlnpf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sotjnmlnpf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sotjnmlnpf .gt_left {\n  text-align: left;\n}\n\n#sotjnmlnpf .gt_center {\n  text-align: center;\n}\n\n#sotjnmlnpf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sotjnmlnpf .gt_font_normal {\n  font-weight: normal;\n}\n\n#sotjnmlnpf .gt_font_bold {\n  font-weight: bold;\n}\n\n#sotjnmlnpf .gt_font_italic {\n  font-style: italic;\n}\n\n#sotjnmlnpf .gt_super {\n  font-size: 65%;\n}\n\n#sotjnmlnpf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sotjnmlnpf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sotjnmlnpf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sotjnmlnpf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sotjnmlnpf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sotjnmlnpf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sotjnmlnpf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#sotjnmlnpf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#sotjnmlnpf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.3598131</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.01987511</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8878864</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.1004806</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.07973918</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions with continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nDifferences are small when sample sizes are large.\n",
    "supporting": [
      "15_Prop_inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}