{
  "hash": "bb2159ab8326a93ffc6effe7545cc1e6",
  "result": {
    "markdown": "---\ntitle: \"Day 16: Simple Linear Regression Part 2 (Sections 6.3-6.4)\"\nsubtitle: \"BSTA 511/611\"\nauthor: \"Meike Niederhausen, PhD\"\ninstitute: \"OHSU-PSU School of Public Health\"\ndate: \"11/27/2023\"\ncategories: [\"Week 10\"]\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\n    source: repo\n    html-math-method: mathjax\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n# editor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n# Load packages\n\n* Packages need to be loaded _every time_ you restart R or render an Qmd file\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run these every time you open Rstudio\nlibrary(tidyverse)    \nlibrary(oibiostat)\nlibrary(janitor)\nlibrary(rstatix)\nlibrary(knitr)\nlibrary(gtsummary)\nlibrary(moderndive)\nlibrary(gt)\nlibrary(broom) \nlibrary(here) \nlibrary(pwr) \nlibrary(gridExtra) # NEW!!!\n```\n:::\n\n\n\n- You can check whether a package has been loaded or not \n  - by looking at the Packages tab and \n  - seeing whether it has been checked off or not\n\n# Goals for today (Sections 6.3-6.4)\n\nSimple Linear Regression Part 2 \n\n+ Review of \n    * best-fit line (aka regression line or least-squares line)\n    * residuals\n    * population model\n+ LINE conditions and how to assess them\n    * New diagnostic tools:\n        * Normal QQ plots of residuals\n        * Residual plots\n+ Coefficient of determination ($R^2$)\n+ Regression inference\n    1. Inference for population [__slope__]{style=\"color:green\"} $\\beta_1$\n        * CI & hypothesis test\n    2. CI for mean response $\\mu_{Y|x^*}$\n    3. Prediction interval for predicting __individual__ observations\n    + Confidence bands vs. predictions bands\n\n\n# Life expectancy vs. female adult literacy rate\n\n<https://www.gapminder.org/tools/#$model$markers$bubble$encoding$x$data$concept=literacy_rate_adult_female_percent_of_females_ages_15_above&source=sg&space@=country&=time;;&scale$domain:null&zoomed:null&type:null;;&frame$value=2011;;;;;&chart-type=bubbles&url=v1>\n\n\n## Dataset description \n\n* Data file: `lifeexp_femlit_water_2011.csv`\n* Data were downloaded from <https://www.gapminder.org/data/>\n* 2011 is the most recent year with the most complete data\n* __Life expectancy__ = the average number of years a newborn child would live if current mortality patterns were to stay the same. Source: <https://www.gapminder.org/data/documentation/gd004/>\n\n* __Adult literacy rate__ is the percentage of people ages 15 and above who can, with understanding, read and write a short, simple statement on their everyday life. Source: <http://data.uis.unesco.org/>\n\n* __At least basic water source (%)__ = the percentage of people using at least basic water services. This indicator encompasses both people using basic water services as well as those using safely managed water services. Basic drinking water services is defined as drinking water from an improved source, provided collection time is not more than 30 minutes for a round trip. Improved water sources include piped water, boreholes or tubewells, protect dug wells, protected springs, and packaged or delivered water.\n\n\n## Get to know the data\n\nLoad data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm_original <- read_csv(here::here(\"data\", \"lifeexp_femlit_water_2011.csv\"))\n```\n:::\n\n\nGlimpse of the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(gapm_original)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 194\nColumns: 5\n$ country                    <chr> \"Afghanistan\", \"Albania\", \"Algeria\", \"Andor…\n$ life_expectancy_years_2011 <dbl> 56.7, 76.7, 76.7, 82.6, 60.9, 76.9, 76.0, 7…\n$ female_literacy_rate_2011  <dbl> 13.0, 95.7, NA, NA, 58.6, 99.4, 97.9, 99.5,…\n$ water_basic_source_2011    <dbl> 52.6, 88.1, 92.6, 100.0, 40.3, 97.0, 99.5, …\n$ water_2011_quart           <chr> \"Q1\", \"Q2\", \"Q2\", \"Q4\", \"Q1\", \"Q3\", \"Q4\", \"…\n```\n:::\n:::\n\n\nNote the missing values for our variables of interest\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm_original %>% select(life_expectancy_years_2011, female_literacy_rate_2011) %>% \n  get_summary_stats()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 13\n  variable        n   min   max median    q1    q3   iqr   mad  mean    sd    se\n  <fct>       <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 life_expec…   187  47.5  82.9   72.7  64.3  76.9  12.6  9.04  70.7  8.44 0.617\n2 female_lit…    80  13    99.8   91.6  71.0  98.0  27.0 11.4   81.7 22.0  2.45 \n# ℹ 1 more variable: ci <dbl>\n```\n:::\n:::\n\n\n\n\n## Remove missing values\n\nRemove rows with missing data for life expectancy and female literacy rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm <- gapm_original %>% \n  drop_na(life_expectancy_years_2011, female_literacy_rate_2011)\n\nglimpse(gapm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 80\nColumns: 5\n$ country                    <chr> \"Afghanistan\", \"Albania\", \"Angola\", \"Antigu…\n$ life_expectancy_years_2011 <dbl> 56.7, 76.7, 60.9, 76.9, 76.0, 73.8, 71.0, 7…\n$ female_literacy_rate_2011  <dbl> 13.0, 95.7, 58.6, 99.4, 97.9, 99.5, 53.4, 9…\n$ water_basic_source_2011    <dbl> 52.6, 88.1, 40.3, 97.0, 99.5, 97.8, 96.7, 9…\n$ water_2011_quart           <chr> \"Q1\", \"Q2\", \"Q1\", \"Q3\", \"Q4\", \"Q3\", \"Q3\", \"…\n```\n:::\n:::\n\n\nNo missing values now for our variables of interest\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngapm %>% select(life_expectancy_years_2011, female_literacy_rate_2011) %>% \n  get_summary_stats()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 13\n  variable        n   min   max median    q1    q3   iqr   mad  mean    sd    se\n  <fct>       <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 life_expec…    80    48  81.8   72.4  65.9  75.8  9.95  6.30  69.9  7.95 0.889\n2 female_lit…    80    13  99.8   91.6  71.0  98.0 27.0  11.4   81.7 22.0  2.45 \n# ℹ 1 more variable: ci <dbl>\n```\n:::\n:::\n\n\n\n:::{.callout-important}\n* Removing the rows with missing data was not needed to run the regression model.\n* I did this step since later we will be calculating the standard deviations of the explanatory and response variables for _just the values included in the regression model_. It'll be easier to do this if we remove the missing values now. \n:::\n\n\n\n# Regression line = best-fit line\n\n$$\\widehat{y} = b_0 + b_1 \\cdot x $$\n\n* $\\hat{y}$ is the predicted outcome for a specific value of $x$.\n* $b_0$ is the intercept\n* $b_1$ is the slope of the line, i.e., the increase in $\\hat{y}$ for every increase of one (unit increase) in $x$.\n    - slope = *rise over run*\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n\n* __Intercept__\n    - The expected outcome for the $y$-variable when the $x$-variable is 0.\n* __Slope__\n    - For every increase of 1 unit in the $x$-variable, there is an expected increase of, on average, $b_1$ units in the $y$-variable.\n    - We only say that there is an expected increase and not necessarily a causal increase.\n\n\n\n## Regression in R: `lm()`, `summary()`, & `tidy()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(life_expectancy_years_2011 ~ female_literacy_rate_2011,\n                 data = gapm)\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, \n    data = gapm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-22.299  -2.670   1.145   4.114   9.498 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               50.92790    2.66041  19.143  < 2e-16 ***\nfemale_literacy_rate_2011  0.23220    0.03148   7.377  1.5e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.142 on 78 degrees of freedom\nMultiple R-squared:  0.4109,\tAdjusted R-squared:  0.4034 \nF-statistic: 54.41 on 1 and 78 DF,  p-value: 1.501e-10\n```\n:::\n\n```{.r .cell-code}\ntidy(model1) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"rmpvxhnzuj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#rmpvxhnzuj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#rmpvxhnzuj thead, #rmpvxhnzuj tbody, #rmpvxhnzuj tfoot, #rmpvxhnzuj tr, #rmpvxhnzuj td, #rmpvxhnzuj th {\n  border-style: none;\n}\n\n#rmpvxhnzuj p {\n  margin: 0;\n  padding: 0;\n}\n\n#rmpvxhnzuj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#rmpvxhnzuj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#rmpvxhnzuj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#rmpvxhnzuj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#rmpvxhnzuj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#rmpvxhnzuj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#rmpvxhnzuj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#rmpvxhnzuj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#rmpvxhnzuj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#rmpvxhnzuj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#rmpvxhnzuj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#rmpvxhnzuj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#rmpvxhnzuj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#rmpvxhnzuj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#rmpvxhnzuj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmpvxhnzuj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#rmpvxhnzuj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#rmpvxhnzuj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#rmpvxhnzuj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmpvxhnzuj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#rmpvxhnzuj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmpvxhnzuj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#rmpvxhnzuj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmpvxhnzuj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#rmpvxhnzuj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#rmpvxhnzuj .gt_left {\n  text-align: left;\n}\n\n#rmpvxhnzuj .gt_center {\n  text-align: center;\n}\n\n#rmpvxhnzuj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#rmpvxhnzuj .gt_font_normal {\n  font-weight: normal;\n}\n\n#rmpvxhnzuj .gt_font_bold {\n  font-weight: bold;\n}\n\n#rmpvxhnzuj .gt_font_italic {\n  font-style: italic;\n}\n\n#rmpvxhnzuj .gt_super {\n  font-size: 65%;\n}\n\n#rmpvxhnzuj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#rmpvxhnzuj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#rmpvxhnzuj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#rmpvxhnzuj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#rmpvxhnzuj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#rmpvxhnzuj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#rmpvxhnzuj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nRegression equation for our model:\n\n$$\\widehat{\\textrm{life expectancy}} = 50.9 + 0.232 \\cdot \\textrm{female literacy rate} $$\n\n\n\n## Residuals\n\n* __Observed values__ $y_i$ \n  * the values in the dataset\n\n* __Fitted values__ $\\widehat{y}_i$ \n  * the values that fall on the best-fit line for a specific $x_i$\n\n* __Residuals__ $e_i = y_i - \\widehat{y}_i$ \n  * the differences between the observed and fitted values\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-10-1.png){width=480}\n:::\n:::\n\n\n\n## The (population) regresison model\n\n* The (population) regression model is denoted by\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\epsilon$$\n\n* $\\beta_0$ and $\\beta_1$ are unknown population parameters\n* $\\epsilon$ (epsilon) is the error about the line\n    * It is assumed to be a random variable: \n        * $\\epsilon \\sim N(0, \\sigma^2)$\n        * variance $\\sigma^2$ is constant\n\n_See slides for image._\n\n\n* The [__line__]{style=\"color:blue\"} is the average (expected) value of $Y$ given a value of $x$: [$E(Y|x)$]{style=\"color:blue\"}.\n\n* The point estimates for $\\beta_0$ and $\\beta_1$ based on a sample are denoted by $b_0, b_1, s_{residuals}^2$\n    * Note: also common notation is $\\widehat{\\beta}_0, \\widehat{\\beta}_1, \\widehat{\\sigma}^2$\n\n\n\n# What are the LINE conditions?\n\nFor \"good\" model fit and to be able to make inferences and predictions based on our models, 4 conditions need to be satisfied.  \n\nBriefly: \n\n* __L__ inearity of relationship between variables\n* __I__ ndependence of the Y values\n* __N__ ormality of the residuals\n* __E__ quality of variance of the residuals (homoscedasticity)\n\n[More in depth](https://bookdown.org/roback/bookdown-bysh/ch-MLRreview.html#ordinary-least-squares-ols-assumptions):\n\n* __L__ : there is a linear relationship between the mean response (Y) and the explanatory variable (X),\n* __I__ : the errors are independent—there’s no connection between how far any two points lie from the regression line,\n* __N__ : the responses are normally distributed at each level of X, and\n* __E__ : the variance or, equivalently, the standard deviation of the responses is equal for all levels of X.\n\n\n\n## L: Linearity of relationship between variables\n\nIs the association between the variables linear?\n\n* Diagnostic tools:\n    * Scatterplot\n    * Residual plot (see later section for E : Equality of variance of the residuals)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-11-1.png){width=1152}\n:::\n:::\n\n\n\n\n## I: Independence of the residuals ($Y$ values)\n\n* __Are the data points independent of each other?__\n\n* Examples of when they are *not* independent, include\n    * repeated measures (such as baseline, 3 months, 6 months)\n    * data from clusters, such as different hospitals or families\n\n* This condition is checked by reviewing the study *design* and not by inspecting the data\n\n* How to analyze data using regression models when the $Y$-values are not independent is covered in BSTA 519 (Longitudinal data) \n\n\n\n# N: Normality of the residuals\n\n* Extract residuals from regression model in R\n* Diagnostic tools:\n    * Distribution plots of residuals\n    * QQ plots\n\n\n\n## N: Normality of the residuals\n\n* The responses Y are normally distributed at each level of x\n\n_See slides for image._\n\n\n\n## Extract model's residuals in R\n\n* First extract the residuals' values from the model output using the `augment()` function from the `broom` package.\n* Get a tibble with the orginal data, as well as the residuals and some other important values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(life_expectancy_years_2011 ~ female_literacy_rate_2011, \n                data = gapm)\naug1 <- augment(model1) \n\nglimpse(aug1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 80\nColumns: 8\n$ life_expectancy_years_2011 <dbl> 56.7, 76.7, 60.9, 76.9, 76.0, 73.8, 71.0, 7…\n$ female_literacy_rate_2011  <dbl> 13.0, 95.7, 58.6, 99.4, 97.9, 99.5, 53.4, 9…\n$ .fitted                    <dbl> 53.94643, 73.14897, 64.53453, 74.00809, 73.…\n$ .resid                     <dbl> 2.7535654, 3.5510294, -3.6345319, 2.8919074…\n$ .hat                       <dbl> 0.13628996, 0.01768176, 0.02645854, 0.02077…\n$ .sigma                     <dbl> 6.172684, 6.168414, 6.167643, 6.172935, 6.1…\n$ .cooksd                    <dbl> 1.835891e-02, 3.062372e-03, 4.887448e-03, 2…\n$ .std.resid                 <dbl> 0.48238134, 0.58332052, -0.59972251, 0.4757…\n```\n:::\n:::\n\n\n\n\n## Check normality with \"usual\" distribution plots\n\nNote that below I save each figure, and then combine them together in one row of output using `grid.arrange()` from the `gridExtra` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist1 <- ggplot(aug1, aes(x = .resid)) +\n  geom_histogram()\n\ndensity1 <- ggplot(aug1, aes(x = .resid)) +\n  geom_density()\n\nbox1 <- ggplot(aug1, aes(x = .resid)) +\n  geom_boxplot()\n\nlibrary(gridExtra) # NEW!!!\ngrid.arrange(hist1, density1, box1, nrow = 1)\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-13-1.png){width=576}\n:::\n:::\n\n\n\n\n## Normal QQ plots (QQ = quantile-quantile)\n\n* It can be tricky to eyeball with a histogram or density plot whether the residuals are normal or not\n* QQ plots are often used to help with this\n\n\n* _Vertical axis_: __data quantiles__\n  * data points are sorted in order and \n  * assigned quantiles based on how many data points there are\n* _Horizontal axis_: __theoretical quantiles__\n    * mean and standard deviation (SD) calculated from the data points\n    * theoretical quantiles are calculated for each point, assuming the data are modeled by a normal distribution with the mean and SD of the data\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-14-1.png){width=480}\n:::\n:::\n\n\n* __Data are approximately normal if points fall on a line.__\n\nSee more info at <https://data.library.virginia.edu/understanding-QQ-plots/> \n\n\n\n### Examples of Normal QQ plots \n\n_See slides for examples._\n\n\n\n## QQ plot of residuals of `model1`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid.arrange(hist1, density1, box1, nrow = 1)\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-15-1.png){width=480}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(aug1, aes(sample = .resid)) + \n  stat_qq() +     # points\n  stat_qq_line()  # line\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-16-1.png){width=480}\n:::\n:::\n\n\n\n\n## Compare to randomly generated Normal QQ plots \n\n\nHow \"_good_\" we can expect a QQ plot to look depends on the sample size. \n\n* The QQ plots on the next slides are randomly generated\n    * using random samples from actual standard normal distributions $N(0,1)$.\n\n* Thus, all the points in the QQ plots __should theoretically__ fall in a line\n\n* However, there is sampling variability...\n\n\n### Randomly generated Normal QQ plots: n=100 \n\n* Note that `stat_qq_line()` doesn't work with randomly generated samples, and thus the code below manually creates the line that the points should be on (which is $y=x$ in this case.)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamplesize <- 100\n\nrand_qq1 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  # line y=x\n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\") \n\nrand_qq2 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\nrand_qq3 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\nrand_qq4 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\ngrid.arrange(rand_qq1, rand_qq2, \n             rand_qq3, rand_qq4, ncol =2)\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-17-1.png){width=480}\n:::\n:::\n\n\n\n\n### Examples of simulated Normal QQ plots: n=10 \n\nWith fewer data points,\n\n* simulated QQ plots are more likely to look \"less normal\" \n* even though the data points were sampled from normal distributions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamplesize <- 10  # only change made to code!\n\nrand_qq1 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  # line y=x\n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\") \n\nrand_qq2 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\nrand_qq3 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\nrand_qq4 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\ngrid.arrange(rand_qq1, rand_qq2, \n             rand_qq3, rand_qq4, ncol =2)\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-18-1.png){width=480}\n:::\n:::\n\n\n\n\n### Examples of simulated Normal QQ plots: n=1,000 \n\nWith more data points,\n\n* simulated QQ plots are more likely to look \"more normal\" \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsamplesize <- 1000 # only change made to code!\n\nrand_qq1 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  # line y=x\n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\") \n\nrand_qq2 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\nrand_qq3 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\nrand_qq4 <- ggplot() +\n  stat_qq(aes(sample = rnorm(samplesize))) + \n  geom_abline(intercept = 0, slope = 1, \n              color = \"blue\")\n\ngrid.arrange(rand_qq1, rand_qq2, \n             rand_qq3, rand_qq4, ncol =2)\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-19-1.png){width=480}\n:::\n:::\n\n\n\n\n## Back to our example\n\nResiduals from Life Expectancy vs. Female Literacy Rate Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(aug1, \n      aes(sample = .resid)) + \n  stat_qq() + \n  stat_qq_line() \n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-20-1.png){width=480}\n:::\n:::\n\n\nSimulated QQ plot of Normal Residuals with n = 80  \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# number of observations \n# in fitted model\nnobs(model1) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\nggplot() +\n  stat_qq(aes(\n    sample = rnorm(80))) + \n  geom_abline(\n    intercept = 0, slope = 1, \n    color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-21-1.png){width=480}\n:::\n:::\n\n\n\n\n# E: Equality of variance of the residuals {.nostretch}\n\n* Homoscedasticity\n* Diagnostic tool: __residual plot__\n\n\n\n## Residual plot\n\n* $x$ = explanatory variable from regression model  \n    * (or the fitted values for a multiple regression)\n* $y$ = residuals from regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(aug1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"life_expectancy_years_2011\" \"female_literacy_rate_2011\" \n[3] \".fitted\"                    \".resid\"                    \n[5] \".hat\"                       \".sigma\"                    \n[7] \".cooksd\"                    \".std.resid\"                \n```\n:::\n\n```{.r .cell-code}\nggplot(aug1, \n       aes(x = female_literacy_rate_2011, \n           y = .resid)) + \n  geom_point() +\n  geom_abline(\n    intercept = 0, \n    slope = 0, \n    color = \"orange\") +\n  labs(title = \"Residual plot\")\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-22-1.png){width=480}\n:::\n:::\n\n\n\n\n## E: Equality of variance of the residuals (Homoscedasticity)\n\n* The __variance__ or, equivalently, the standard deviation of the responses is __equal for all values of x__.\n* This is called __homoskedasticity__ (top row)\n* If there is __heteroskedasticity__ (bottom row), then the assumption is not met.\n\n_See slides for image._\n\n\n\n# $R^2$ = Coefficient of determination\n\nAnother way to assess model fit\n\n\n\n## $R^2$ = Coefficient of determination (1/2)\n\n+ Recall that the correlation coefficient $r$ measures the strength of the linear relationship between two numerical variables\n+ $R^2$ is usually used to measure the strength of a _linear fit_\n  + For a simple linear regression model (one numerical predictor), $R^2$ is just the square of the correlation coefficient\n+ In general, $R^2$ is the proportion of the variability of the dependent variable that is __explained__ by the independent variable(s)\n\n$$R^2 = \\frac{\\textrm{variance of predicted y-values}}\n{\\textrm{variance of observed y-values}} = \\frac{\\sum_{i=1}^n(\\widehat{y}_i-\\bar{y})^2}\n{\\sum_{i=1}^n(y_i-\\bar{y})^2} \n = \\frac{s_y^2 - s_{\\textrm{residuals}}^2}\n{s_y^2}$$\n$$R^2 = 1- \\frac{s_{\\textrm{residuals}}^2}\n{s_y^2}$$\nwhere $\\frac{s_{\\textrm{residuals}}^2}{s_y^2}$ is the proportion of \"unexplained\" variability in the $y$ values,  \nand thus $R^2 = 1- \\frac{s_{\\textrm{residuls}}^2}{s_y^2}$ is the proportion of \"explained\" variability in the $y$ values \n\n\n\n## $R^2$ = Coefficient of determination (2/2)\n\n+ Recall, $-1<r<1$\n\n+ Thus, $0<R^2<1$\n\n+ In practice, we want \"high\" $R^2$ values, i.e. $R^2$ as close to 1 as possible.\n\nCalculating $R^2$ in R using `glance()` from the `broom` package:\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.411         0.403  6.14      54.4 1.50e-10     1  -258.  521.  529.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n\n```{.r .cell-code}\nglance(model1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4109366\n```\n:::\n:::\n\n\n:::{.callout-warning}\n* A model can have a high $R^2$ value when there is a curved pattern.\n* Always first check whether a linear model is reasonable or not.\n:::\n\n\n\n## $R^2$ in `summary()` R output\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, \n    data = gapm)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-22.299  -2.670   1.145   4.114   9.498 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               50.92790    2.66041  19.143  < 2e-16 ***\nfemale_literacy_rate_2011  0.23220    0.03148   7.377  1.5e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.142 on 78 degrees of freedom\nMultiple R-squared:  0.4109,\tAdjusted R-squared:  0.4034 \nF-statistic: 54.41 on 1 and 78 DF,  p-value: 1.501e-10\n```\n:::\n:::\n\n\nCompare to the square of the correlation coefficient $r$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- cor(x = gapm$life_expectancy_years_2011, \n    y = gapm$female_literacy_rate_2011,\n    use =  \"complete.obs\")\nr\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6410434\n```\n:::\n\n```{.r .cell-code}\nr^2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4109366\n```\n:::\n:::\n\n\n\n# Regression inference\n\n1. Inference for population [__slope__]{style=\"color:green\"} $\\beta_1$\n2. CI for mean response $\\mu_{Y|x^*}$\n3. Prediction interval for predicting __individual__ observations\n\n\n## Inference for population [__slope__]{style=\"color:green\"} $\\beta_1$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit regression model:\nmodel1 <- lm(life_expectancy_years_2011 ~ female_literacy_rate_2011,\n                 data = gapm)\n# Get regression table:\ntidy(model1, conf.int = TRUE) %>% gt() # conf.int = TRUE part is new! \n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"mcuelenhvk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mcuelenhvk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mcuelenhvk thead, #mcuelenhvk tbody, #mcuelenhvk tfoot, #mcuelenhvk tr, #mcuelenhvk td, #mcuelenhvk th {\n  border-style: none;\n}\n\n#mcuelenhvk p {\n  margin: 0;\n  padding: 0;\n}\n\n#mcuelenhvk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mcuelenhvk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mcuelenhvk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mcuelenhvk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mcuelenhvk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mcuelenhvk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mcuelenhvk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mcuelenhvk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mcuelenhvk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mcuelenhvk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mcuelenhvk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mcuelenhvk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mcuelenhvk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mcuelenhvk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mcuelenhvk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mcuelenhvk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mcuelenhvk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mcuelenhvk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mcuelenhvk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mcuelenhvk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mcuelenhvk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mcuelenhvk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mcuelenhvk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mcuelenhvk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mcuelenhvk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mcuelenhvk .gt_left {\n  text-align: left;\n}\n\n#mcuelenhvk .gt_center {\n  text-align: center;\n}\n\n#mcuelenhvk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mcuelenhvk .gt_font_normal {\n  font-weight: normal;\n}\n\n#mcuelenhvk .gt_font_bold {\n  font-weight: bold;\n}\n\n#mcuelenhvk .gt_font_italic {\n  font-style: italic;\n}\n\n#mcuelenhvk .gt_super {\n  font-size: 65%;\n}\n\n#mcuelenhvk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mcuelenhvk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mcuelenhvk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mcuelenhvk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mcuelenhvk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mcuelenhvk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mcuelenhvk .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\\begin{align}\n\\widehat{y} =& b_0 + b_1 \\cdot x\\\\\n\\widehat{\\text{life expectancy}} =& 50.9 + 0.232 \\cdot \\text{female literacy rate}\n\\end{align}\n\n+ What are $H_0$ and $H_A$?\n+ How do we calculate the standard error, statistic, _p_-value, and CI?\n\n:::{.callout-note}\n* We can also test & calculate CI for the population intercept\n* This will be covered in BSTA 512\n:::\n\n\n\n### Inference for the population [__slope__]{style=\"color:green\"}: CI and hypothesis test\n\n__Population model__  \n_line + random \"noise\"_\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\varepsilon$$\nwith $\\varepsilon \\sim N(0,\\sigma)$  \n$\\sigma$ is the variability (SD) of the residuals\n\n<br>\n\n__Sample best-fit (least-squares) line:__\n\n$$\\widehat{y} = b_0 + b_1 \\cdot x $$\n\nNote: Some sources use $\\widehat{\\beta}$ instead of $b$. \n\n\n+ Construct a __95% confidence interval__ for the __population slope__ $\\beta_1$\n\n<br>\n\n+ Conduct the __hypothesis test__ \n\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n\n<br>\n\n_Note: R reports p-values for 2-sided tests_\n\n\n\n### CI for population [__slope__]{style=\"color:green\"} $\\beta_1$\n\nRecall the general CI formula: \n\n$$\\textrm{Point Estimate} \\pm t^*\\cdot SE_{\\textrm{Point Estimate}}$$\n\nFor the CI of the coefficient $b_1$ this translates to\n\n$$b_1 \\pm t^*\\cdot SE_{b_1}$$\nwhere $t^*$ is the critical value from a $t$-distribution with $df = n -2$.\n\n<br>\n\n_How is_ $\\text{SE}_{b_1}$ _calculated?_ See next slide.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 7\n  term                  estimate std.error statistic  p.value conf.low conf.high\n  <chr>                    <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)             50.9      2.66       19.1  3.33e-31   45.6      56.2  \n2 female_literacy_rate…    0.232    0.0315      7.38 1.50e-10    0.170     0.295\n```\n:::\n:::\n\n\n\n\n### Standard error of fitted slope $b_1$\n\n$$\\text{SE}_{b_1} = \\frac{s_{\\textrm{residuals}}}{s_x\\sqrt{n-1}}$$\n\n$\\text{SE}_{b_1}$ is the __variability__ of the statistic $b_1$\n\n+ $s_{\\textrm{residuals}}^2$ is the sd of the residuals\n+ $s_x$ is the sample sd of the explanatory variable $x$\n+ $n$ is the sample size, or the number of (complete) pairs of points\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.411         0.403  6.14      54.4 1.50e-10     1  -258.  521.  529.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n:::\n\n```{.r .cell-code}\n# standard deviation of the residuals (Residual standard error in summary() output)\n(s_resid <- glance(model1)$sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.142157\n```\n:::\n\n```{.r .cell-code}\n# standard deviation of x's\n(s_x <- sd(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.95371\n```\n:::\n\n```{.r .cell-code}\n# number of pairs of complete observations\n(n <- nobs(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(se_b1 <- s_resid/(s_x * sqrt(n-1))) # compare to SE in regression output\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.03147744\n```\n:::\n:::\n\n\n\n\n### Calculate CI for population [__slope__]{style=\"color:green\"} $\\beta_1$\n\n$$b_1 \\pm t^*\\cdot SE_{b_1}$$  \n\nwhere $t^*$ is the $t$-distribution critical value with $df = n -2$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"mzumfpwbxo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mzumfpwbxo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mzumfpwbxo thead, #mzumfpwbxo tbody, #mzumfpwbxo tfoot, #mzumfpwbxo tr, #mzumfpwbxo td, #mzumfpwbxo th {\n  border-style: none;\n}\n\n#mzumfpwbxo p {\n  margin: 0;\n  padding: 0;\n}\n\n#mzumfpwbxo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mzumfpwbxo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mzumfpwbxo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mzumfpwbxo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mzumfpwbxo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mzumfpwbxo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mzumfpwbxo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mzumfpwbxo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mzumfpwbxo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mzumfpwbxo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mzumfpwbxo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mzumfpwbxo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mzumfpwbxo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mzumfpwbxo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mzumfpwbxo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzumfpwbxo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mzumfpwbxo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mzumfpwbxo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mzumfpwbxo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzumfpwbxo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mzumfpwbxo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzumfpwbxo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mzumfpwbxo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzumfpwbxo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mzumfpwbxo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzumfpwbxo .gt_left {\n  text-align: left;\n}\n\n#mzumfpwbxo .gt_center {\n  text-align: center;\n}\n\n#mzumfpwbxo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mzumfpwbxo .gt_font_normal {\n  font-weight: normal;\n}\n\n#mzumfpwbxo .gt_font_bold {\n  font-weight: bold;\n}\n\n#mzumfpwbxo .gt_font_italic {\n  font-style: italic;\n}\n\n#mzumfpwbxo .gt_super {\n  font-size: 65%;\n}\n\n#mzumfpwbxo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mzumfpwbxo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mzumfpwbxo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mzumfpwbxo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mzumfpwbxo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mzumfpwbxo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mzumfpwbxo .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nSave regression output for the row with the slope's information: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_b1 <-tidy(model1) %>% filter(term == \"female_literacy_rate_2011\")\nmodel1_b1 %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"finojixofv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#finojixofv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#finojixofv thead, #finojixofv tbody, #finojixofv tfoot, #finojixofv tr, #finojixofv td, #finojixofv th {\n  border-style: none;\n}\n\n#finojixofv p {\n  margin: 0;\n  padding: 0;\n}\n\n#finojixofv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#finojixofv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#finojixofv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#finojixofv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#finojixofv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#finojixofv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#finojixofv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#finojixofv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#finojixofv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#finojixofv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#finojixofv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#finojixofv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#finojixofv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#finojixofv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#finojixofv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#finojixofv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#finojixofv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#finojixofv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#finojixofv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#finojixofv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#finojixofv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#finojixofv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#finojixofv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#finojixofv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#finojixofv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#finojixofv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#finojixofv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#finojixofv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#finojixofv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#finojixofv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#finojixofv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#finojixofv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#finojixofv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#finojixofv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#finojixofv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#finojixofv .gt_left {\n  text-align: left;\n}\n\n#finojixofv .gt_center {\n  text-align: center;\n}\n\n#finojixofv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#finojixofv .gt_font_normal {\n  font-weight: normal;\n}\n\n#finojixofv .gt_font_bold {\n  font-weight: bold;\n}\n\n#finojixofv .gt_font_italic {\n  font-style: italic;\n}\n\n#finojixofv .gt_super {\n  font-size: 65%;\n}\n\n#finojixofv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#finojixofv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#finojixofv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#finojixofv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#finojixofv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#finojixofv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#finojixofv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nSave values needed for CI:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb1 <- model1_b1$estimate\nSE_b1 <- model1_b1$std.error\n\nnobs(model1) # sample size n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, df = 80-2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n:::\n\n\nCompare CI bounds below with the ones in the regression table above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(CI_LB <- b1 - tstar*SE_b1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1695284\n```\n:::\n\n```{.r .cell-code}\n(CI_UB <- b1 + tstar*SE_b1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2948619\n```\n:::\n:::\n\n\n\n\n### Hypothesis test for population [__slope__]{style=\"color:green\"} $\\beta_1$\n\n\\begin{align}\nH_0 &: \\beta_1 = 0\\\\\n\\text{vs. } H_A&: \\beta_1 \\neq 0\n\\end{align}\n\nThe __test statistic__ for $b_1$ is \n\n$$t = \\frac{ b_1 - \\beta_1}{ \\text{SE}_{b_1}} = \\frac{ b_1}{ \\text{SE}_{b_1}}$$\n\nwhen we assume $H_0: \\beta_1 = 0$ is true.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"wqctsycmlt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wqctsycmlt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wqctsycmlt thead, #wqctsycmlt tbody, #wqctsycmlt tfoot, #wqctsycmlt tr, #wqctsycmlt td, #wqctsycmlt th {\n  border-style: none;\n}\n\n#wqctsycmlt p {\n  margin: 0;\n  padding: 0;\n}\n\n#wqctsycmlt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wqctsycmlt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wqctsycmlt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wqctsycmlt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wqctsycmlt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wqctsycmlt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wqctsycmlt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wqctsycmlt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wqctsycmlt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wqctsycmlt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wqctsycmlt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wqctsycmlt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wqctsycmlt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wqctsycmlt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wqctsycmlt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqctsycmlt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wqctsycmlt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wqctsycmlt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wqctsycmlt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqctsycmlt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wqctsycmlt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqctsycmlt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wqctsycmlt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqctsycmlt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wqctsycmlt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqctsycmlt .gt_left {\n  text-align: left;\n}\n\n#wqctsycmlt .gt_center {\n  text-align: center;\n}\n\n#wqctsycmlt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wqctsycmlt .gt_font_normal {\n  font-weight: normal;\n}\n\n#wqctsycmlt .gt_font_bold {\n  font-weight: bold;\n}\n\n#wqctsycmlt .gt_font_italic {\n  font-style: italic;\n}\n\n#wqctsycmlt .gt_super {\n  font-size: 65%;\n}\n\n#wqctsycmlt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wqctsycmlt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wqctsycmlt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wqctsycmlt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wqctsycmlt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wqctsycmlt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wqctsycmlt .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nCalculate the test statistic using the values in the regression table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# recall model1_b1 is regression table restricted to b1 row\n(TestStat <- model1_b1$estimate / model1_b1$std.error)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.376557\n```\n:::\n:::\n\n\nCompare this test statistic value to the one from the regression table above\n\n\n\n### $p$-value for testing population [__slope__]{style=\"color:green\"} $\\beta_1$\n\n* As usual, the $p$-value is the _probability of obtaining a test statistic_ __just as extreme or more extreme__ _than the observed test statistic assuming the null hypothesis_ $H_0$ _is true._\n\n* To calculate the $p$-value, we need to know the probability distribution of the test statistic (the _null distribution_) assuming $H_0$ is true.\n\n+ Statistical theory tells us that the test statistic $t$ can be modeled by a [__$t$-distribution__]{style=\"color:green\"} with [__$df = n-2$__]{style=\"color:green\"}.\n\n+ Recall that this is a 2-sided test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pv = 2*pt(TestStat, df=80-2, lower.tail=F))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.501286e-10\n```\n:::\n:::\n\n\nCompare the $p$-value to the one from the regression table below\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(model1, conf.int = TRUE) %>% gt()  # compare p-value calculated above to p-value in table\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"puvzrfkuyh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#puvzrfkuyh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#puvzrfkuyh thead, #puvzrfkuyh tbody, #puvzrfkuyh tfoot, #puvzrfkuyh tr, #puvzrfkuyh td, #puvzrfkuyh th {\n  border-style: none;\n}\n\n#puvzrfkuyh p {\n  margin: 0;\n  padding: 0;\n}\n\n#puvzrfkuyh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#puvzrfkuyh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#puvzrfkuyh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#puvzrfkuyh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#puvzrfkuyh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#puvzrfkuyh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#puvzrfkuyh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#puvzrfkuyh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#puvzrfkuyh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#puvzrfkuyh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#puvzrfkuyh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#puvzrfkuyh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#puvzrfkuyh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#puvzrfkuyh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#puvzrfkuyh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#puvzrfkuyh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#puvzrfkuyh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#puvzrfkuyh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#puvzrfkuyh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#puvzrfkuyh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#puvzrfkuyh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#puvzrfkuyh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#puvzrfkuyh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#puvzrfkuyh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#puvzrfkuyh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#puvzrfkuyh .gt_left {\n  text-align: left;\n}\n\n#puvzrfkuyh .gt_center {\n  text-align: center;\n}\n\n#puvzrfkuyh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#puvzrfkuyh .gt_font_normal {\n  font-weight: normal;\n}\n\n#puvzrfkuyh .gt_font_bold {\n  font-weight: bold;\n}\n\n#puvzrfkuyh .gt_font_italic {\n  font-style: italic;\n}\n\n#puvzrfkuyh .gt_super {\n  font-size: 65%;\n}\n\n#puvzrfkuyh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#puvzrfkuyh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#puvzrfkuyh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#puvzrfkuyh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#puvzrfkuyh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#puvzrfkuyh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#puvzrfkuyh .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">45.6314348</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">56.2243615</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.1695284</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.2948619</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n# Prediction (& inference)\n\n1. Prediction for mean response \n2. Prediction for new individual observation\n\n\n\n## Prediction with regression line\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"gucstlenba\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gucstlenba table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gucstlenba thead, #gucstlenba tbody, #gucstlenba tfoot, #gucstlenba tr, #gucstlenba td, #gucstlenba th {\n  border-style: none;\n}\n\n#gucstlenba p {\n  margin: 0;\n  padding: 0;\n}\n\n#gucstlenba .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gucstlenba .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gucstlenba .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gucstlenba .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gucstlenba .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gucstlenba .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gucstlenba .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gucstlenba .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gucstlenba .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gucstlenba .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gucstlenba .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gucstlenba .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gucstlenba .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gucstlenba .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gucstlenba .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gucstlenba .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gucstlenba .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gucstlenba .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gucstlenba .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gucstlenba .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gucstlenba .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gucstlenba .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gucstlenba .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gucstlenba .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gucstlenba .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gucstlenba .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gucstlenba .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gucstlenba .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gucstlenba .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gucstlenba .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gucstlenba .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gucstlenba .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gucstlenba .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gucstlenba .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gucstlenba .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gucstlenba .gt_left {\n  text-align: left;\n}\n\n#gucstlenba .gt_center {\n  text-align: center;\n}\n\n#gucstlenba .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gucstlenba .gt_font_normal {\n  font-weight: normal;\n}\n\n#gucstlenba .gt_font_bold {\n  font-weight: bold;\n}\n\n#gucstlenba .gt_font_italic {\n  font-style: italic;\n}\n\n#gucstlenba .gt_super {\n  font-size: 65%;\n}\n\n#gucstlenba .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gucstlenba .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gucstlenba .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gucstlenba .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gucstlenba .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gucstlenba .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gucstlenba .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">50.9278981</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.66040695</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">19.142898</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.325312e-31</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">female_literacy_rate_2011</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.2321951</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03147744</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">7.376557</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.501286e-10</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n$$\\widehat{\\textrm{life expectancy}} = 50.9 + 0.232 \\cdot \\textrm{female literacy rate} $$\n\nWhat is the predicted life expectancy for a country with female literacy rate 60%?\n\n$$\\widehat{\\textrm{life expectancy}} = 50.9 + 0.232 \\cdot 60 = 64.82$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(y_60 <- 50.9 + 0.232*60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64.82\n```\n:::\n:::\n\n\n<br>\n\n* How do we interpret the predicted value?\n* How variable is it?\n\n\n\n### Prediction with regression line\n\nRecall the population model:\n\n_line + random \"noise\"_\n\n$$Y = \\beta_0 + \\beta_1 \\cdot X + \\varepsilon$$\nwith $\\varepsilon \\sim N(0,\\sigma)$  \n$\\sigma$ is the variability (SD) of the residuals\n\n<br>\n\n* When we take the expected value, at a given value $x^*$, we have that the predicted response is the average expected response at $x^*$:\n\n$$\\widehat{E[Y|x^*]} = b_0 + b_1 x^*$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gapm, aes(x = female_literacy_rate_2011,\n                 y = life_expectancy_years_2011)) +\n  geom_point() +\n  labs(x = \"female literacy rate\", \n       y = \"life expectancy\",\n       title = \"Life expectancy vs. female literacy rate\") +  \n  geom_smooth(method = \"lm\", se = TRUE) +\n  geom_vline(xintercept = 60, color = \"green3\")\n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-39-1.png){width=480}\n:::\n:::\n\n\n* These are the points on the regression line.\n* The mean responses has variability, and we can calculate a CI for it, for every value of $x^*$. \n\n\n\n### CI for mean response $\\mu_{Y|x^*}$\n\n$$\\widehat{E[Y|x^*]} \\pm t_{n-2}^* \\cdot SE_{\\widehat{E[Y|x^*]}}$$\n\n* $SE_{\\widehat{E[Y|x^*]}}$ is calculated using\n\n$$SE_{\\widehat{E[Y|x^*]}} = s_{residuals} \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}$$\n\n+ $\\widehat{E[Y|x^*]}$ is the predicted value at the specified point $x^*$ of the explanatory variable\n+ $s_{\\textrm{residuals}}^2$ is the sd of the residuals\n+ $n$ is the sample size, or the number of (complete) pairs of points\n+ $\\bar{x}$ is the sample mean of the explanatory variable $x$\n+ $s_x$ is the sample sd of the explanatory variable $x$\n\n<br>\n\n* Recall that $t_{n-2}^*$ is calculated using `qt()` and depends on the confidence level.\n\n\n\n### Example: CI for mean response $\\mu_{Y|x^*}$\n\n__Find the 95% CI for the mean life expectancy when the female literacy rate is 60.__\n\n\\begin{align}\n\\widehat{E[Y|x^*]} &\\pm t_{n-2}^* \\cdot SE_{\\widehat{E[Y|x^*]}}\\\\\n64.8596 &\\pm 1.990847 \\cdot s_{residuals} \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}\\\\\n64.8596 &\\pm 1.990847 \\cdot 6.142157 \\sqrt{\\frac{1}{80} + \\frac{(60 - 81.65375)^2}{(80-1)21.95371^2}}\\\\\n64.8596 &\\pm 1.990847 \\cdot 0.9675541\\\\\n64.8596 &\\pm 1.926252\\\\\n(62.93335 &, 66.78586)\n\\end{align}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Y60 <- 50.9278981 + 0.2321951 * 60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64.8596\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, df = 78))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n\n```{.r .cell-code}\n(s_resid <- glance(model1)$sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.142157\n```\n:::\n\n```{.r .cell-code}\n(n <- nobs(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(mx <- mean(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 81.65375\n```\n:::\n\n```{.r .cell-code}\n(s_x <- sd(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.95371\n```\n:::\n\n```{.r .cell-code}\n(SE_Yx <- s_resid *sqrt(1/n + (60 - mx)^2/((n-1)*s_x^2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9675541\n```\n:::\n\n```{.r .cell-code}\n(MOE_Yx <- SE_Yx*tstar)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.926252\n```\n:::\n\n```{.r .cell-code}\nY60 - MOE_Yx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 62.93335\n```\n:::\n\n```{.r .cell-code}\nY60 + MOE_Yx\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 66.78586\n```\n:::\n:::\n\n\n\n\n### Example: Using R for CI for mean response $\\mu_{Y|x^*}$\n\n__Find the 95% CI's for the mean life expectancy when the female literacy rate is 40, 60, and 80.__\n\n* Use the base R `predict()` function\n* Requires specification of a `newdata` \"value\"\n  * The `newdata` value is $x^*$\n  * This has to be in the format of a data frame though\n  * with column name identical to the predictor variable in the model \n\n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata <- data.frame(female_literacy_rate_2011 = c(40, 60, 80)) \nnewdata\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  female_literacy_rate_2011\n1                        40\n2                        60\n3                        80\n```\n:::\n\n```{.r .cell-code}\npredict(model1, \n        newdata=newdata, \n        interval=\"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       fit      lwr      upr\n1 60.21570 57.26905 63.16236\n2 64.85961 62.93335 66.78586\n3 69.50351 68.13244 70.87457\n```\n:::\n:::\n\n\n\n\n### Interpretation\n\nWe are 95% confident that the __average__ life expectancy for a country with a 60% female literacy rate will be between 62.9 and 66.8 years.\n\n\n\n### Confidence bands for mean response $\\mu_{Y|x^*}$\n\n* Often we plot the CI for many values of X, creating __confidence bands__\n* The confidence bands are what ggplot creates when we set `se = TRUE` within `geom_smooth`\n* For what values of x are the confidence bands (intervals) narrowest?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(gapm,\n       aes(x=female_literacy_rate_2011, \n           y=life_expectancy_years_2011)) +\n  geom_point()+\n  geom_smooth(method = lm, se=TRUE)+\n  ggtitle(\"Life expectancy vs. female literacy rate\") \n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-42-1.png){width=480}\n:::\n:::\n\n\n\n\n### Width of confidence bands for mean response $\\mu_{Y|x^*}$\n\n* For what values of $x^*$ are the confidence bands (intervals) narrowest? widest?\n\n\\begin{align}\n\\widehat{E[Y|x^*]} &\\pm t_{n-2}^* \\cdot SE_{\\widehat{E[Y|x^*]}}\\\\\n\\widehat{E[Y|x^*]} &\\pm t_{n-2}^* \\cdot s_{residuals} \\sqrt{\\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}\n\\end{align}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-43-1.png){width=480}\n:::\n:::\n\n\n\n\n## Prediction interval for predicting __individual__ observations\n\n* We do not call this interval a CI since $Y$ is a random variable instead of a parameter\n* The form is similar to a CI though:\n\n$$\\widehat{Y|x^*} \\pm t_{n-2}^* \\cdot s_{residuals} \\sqrt{1 + \\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}$$\n\n* Note that the only difference to the CI for a mean value of y is the additional `1+` under the square root.\n    * Thus the width is wider!\n\n\n\n### Example: Prediction interval\n\n__Find the 95% prediction interval for the life expectancy when the female literacy rate is 60.__\n\n\\begin{align}\n\\widehat{Y|x^*} &\\pm t_{n-2}^* \\cdot s_{residuals} \\sqrt{1 + \\frac{1}{n} + \\frac{(x^* - \\bar{x})^2}{(n-1)s_x^2}}\\\\\n64.8596 &\\pm 1.990847 \\cdot 6.142157 \\sqrt{1+\\frac{1}{80} + \\frac{(60 - 81.65375)^2}{(80-1)21.95371^2}}\\\\\n(52.48072 &, 77.23849)\n\\end{align}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Y60 <- 50.9278981 + 0.2321951 * 60)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64.8596\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(.975, df = 78))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.990847\n```\n:::\n\n```{.r .cell-code}\n(s_resid <- glance(model1)$sigma)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.142157\n```\n:::\n\n```{.r .cell-code}\n(n <- nobs(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 80\n```\n:::\n\n```{.r .cell-code}\n(mx <- mean(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 81.65375\n```\n:::\n\n```{.r .cell-code}\n(s_x <- sd(gapm$female_literacy_rate_2011))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.95371\n```\n:::\n\n```{.r .cell-code}\n(SE_Ypred <- s_resid *sqrt(1 + 1/n + (60 - mx)^2/((n-1)*s_x^2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.217898\n```\n:::\n\n```{.r .cell-code}\n(MOE_Ypred <- SE_Ypred*tstar)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 12.37888\n```\n:::\n\n```{.r .cell-code}\nY60 - MOE_Ypred\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 52.48072\n```\n:::\n\n```{.r .cell-code}\nY60 + MOE_Ypred\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77.23849\n```\n:::\n:::\n\n\n\n\n### Example: Using R for prediction interval\n\n__Find the 95% prediction intervals for the life expectancy when the female literacy rate is 40, 60, and 80.__\n    \n\n::: {.cell}\n\n```{.r .cell-code}\nnewdata  # previously defined for CI's\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  female_literacy_rate_2011\n1                        40\n2                        60\n3                        80\n```\n:::\n\n```{.r .cell-code}\npredict(model1, \n        newdata=newdata, \n        interval=\"prediction\")  # prediction instead of \"confidence\"\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       fit      lwr      upr\n1 60.21570 47.63758 72.79382\n2 64.85961 52.48072 77.23849\n3 69.50351 57.19879 81.80823\n```\n:::\n:::\n\n\n\n### Interpretation\n\nWe are 95% confident that a new selected country with a 60% female literacy rate will have a life expectancy between 52.5 and 77.2 years.\n\n\n\n## Prediction bands vs. confidence bands (1/2)\n\nCreate a scatterplot with the regression line, 95% confidence bands, and 95% prediction bands.\n\n\n* First create a data frame with the original data points (both x and y values), their respective predicted values, andtheir respective prediction intervals\n* Can do this with `augment()` from the `broom` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1_pred_bands <- augment(model1, interval = \"prediction\")\n\n# take a look at new object:\nnames(model1_pred_bands) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"life_expectancy_years_2011\" \"female_literacy_rate_2011\" \n [3] \".fitted\"                    \".lower\"                    \n [5] \".upper\"                     \".resid\"                    \n [7] \".hat\"                       \".sigma\"                    \n [9] \".cooksd\"                    \".std.resid\"                \n```\n:::\n\n```{.r .cell-code}\n# glimpse of select variables of interest:\nmodel1_pred_bands %>% \n  select(life_expectancy_years_2011, female_literacy_rate_2011, \n         .fitted:.upper) %>% \n  glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 80\nColumns: 5\n$ life_expectancy_years_2011 <dbl> 56.7, 76.7, 60.9, 76.9, 76.0, 73.8, 71.0, 7…\n$ female_literacy_rate_2011  <dbl> 13.0, 95.7, 58.6, 99.4, 97.9, 99.5, 53.4, 9…\n$ .fitted                    <dbl> 53.94643, 73.14897, 64.53453, 74.00809, 73.…\n$ .lower                     <dbl> 40.91166, 60.81324, 52.14572, 61.65365, 61.…\n$ .upper                     <dbl> 66.98121, 85.48470, 76.92334, 86.36253, 86.…\n```\n:::\n:::\n\n\n\n### Prediction bands vs. confidence bands (2/2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(model1_pred_bands) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"life_expectancy_years_2011\" \"female_literacy_rate_2011\" \n [3] \".fitted\"                    \".lower\"                    \n [5] \".upper\"                     \".resid\"                    \n [7] \".hat\"                       \".sigma\"                    \n [9] \".cooksd\"                    \".std.resid\"                \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(model1_pred_bands, \n       aes(x=female_literacy_rate_2011, y=life_expectancy_years_2011)) +\n  geom_point() +\n  geom_ribbon(aes(ymin = .lower, ymax = .upper), # prediction bands\n              alpha = 0.2, fill = \"red\") +\n  geom_smooth(method=lm) +  # confidence bands\n  labs(title = \"SLR with Confidence & Prediction Bands\") \n```\n\n::: {.cell-output-display}\n![](Day16_bsta511_code_files/figure-html/unnamed-chunk-48-1.png){width=480}\n:::\n:::\n",
    "supporting": [
      "Day16_bsta511_code_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}