{
  "hash": "b1dd1004a94a4de0d6b40e0d899c0e38",
  "result": {
    "markdown": "---\ntitle: \"Homework 4 Answers\"\nsubtitle: \"EPI 525\"\ndate-modified: \"today\"\nformat: \n  html: \n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n```{=html}\n<style>\ndiv.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}\n</style>\n```\n\n\n\n# Book exercises {.unnumbered}\n\n## 3.38 Stenographer’s typos {.unnumbered}\n\n__A very skilled court stenographer makes one typographical error (typo) per hour on average.__\n\n### a {.unnumbered}\n\n__What are the mean and the standard deviation of the number of typos this stenographer makes in an hour?__\n\n::: blue\nLet $X$ be the number of typos this stenographer makes in an hour. Then $X$ can be modeled by a Poisson random variable with $\\lambda = 1$ error per hour:\n\n$$X \\sim Pois (\\lambda = 1)$$  \n\nFor a Poisson r.v., the mean and variance are both equal to $\\lambda$:\n\n\\begin{align}\n\\mu &= E(X)= \\lambda = 1 \\\\\n\\sigma &= \\sqrt {Var(X)} = \\sqrt {\\lambda} = \\sqrt {1} = 1\n\\end{align}\n\nThe mean number of typos the stenographer makes in an hour is 1 with standard deviation 1.\n\n:::\n\n### b {.unnumbered}\n\n__Calculate the probability that this stenographer makes at most 3 typos in a given hour.__\n\n::: blue\n$$X \\sim Pois (\\lambda = 1)$$   \n$$P(X \\leq 3) = \\sum_{k=0}^{3}\\frac{e^{-1}(1^{k})}{k!}$$\n\nThis can be calculated \"directly\" in R using the formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# vector of x values whose probabilities need to be added\nx <- 0:3  \n# vector of respective Poisson prob's of x values\n(Poisson_prob_0_3 <- exp(-1)*(1^x)/factorial(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.36787944 0.36787944 0.18393972 0.06131324\n```\n:::\n\n```{.r .cell-code}\n# add up the probabilities\nsum(Poisson_prob_0_3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9810118\n```\n:::\n:::\n\n\n\nUsing the R command `ppois` we have:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Pleq3 <- ppois(3,1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9810118\n```\n:::\n:::\n\n\n\nThe probability that the stenographer made no more than 3 typos in an hour is 0.981.\n\n*Note: the assignment did not specify which way to calculate the probability (ppois vs. formula), and thus either one is correct. Make sure you know how to calculate it both ways though.*\n\n:::\n\n### c {.unnumbered}\n\n__Calculate the probability that this stenographer makes at least 5 typos over 3 hours.__\n\n::: blue\nLet $X$ be the number of typos this stenographer makes in 3 hours. Then $X$ can be modeled by a Poisson random variable with $\\lambda = 3$ errors per 3 hours since $\\lambda_{t=3} = \\lambda_{t=1} \\cdot 3 = 3$:\n\n$$X \\sim Pois (\\lambda = 3)$$  \n\nThe probability that this stenographer makes at least 5 typos over 3 hours is:\n\n\\begin{align}\nP(X \\geq 5) &= 1 - P(X < 5) \\\\\n&= 1 - P(X \\leq 4) \\\\\n&= 1 -\\sum_{k=0}^{4} \\frac{e^{-3} (3)^{k}}{k!}\n\\end{align}\n\nThere are various ways this can be calculated.\n\n* Calculated \"directly\" in R using the formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# vector of x values whose probabilities need to be added\nx <- 0:4  \n# vector of respective Poisson prob's of x values\n(Poisson_prob_0_4 <- exp(-3)*(3^x)/factorial(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.04978707 0.14936121 0.22404181 0.22404181 0.16803136\n```\n:::\n\n```{.r .cell-code}\n# add up the probabilities\n1 - sum(Poisson_prob_0_4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1847368\n```\n:::\n:::\n\n\n\nUsing the R command `ppois` we have two options depending on whether we use `lower.tail = TRUE` or `lower.tail = FALSE`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(X >= 5) for Pois(lambda = 3) random variable\n# P(X >= 5) = 1 - P(X <= 4)\n1 - ppois(q = 4, lambda = 3, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1847368\n```\n:::\n\n```{.r .cell-code}\n# P(X >= 5) for Pois(lambda = 3) random variable\n# P(X >= 5) = P(X > 4)\n(Pgeq5 <- ppois(q = 4, lambda = 3, lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1847368\n```\n:::\n:::\n\n\n\n\nThe probability that the stenographer made 5 or more typos over 3 hours is 0.185.\n:::\n\n## 3.40 Osteosarcoma in NYC {.unnumbered}\n\n__Osteosarcoma is a relatively rare type of bone cancer.  It occurs most often in young adults, age 10 - 19; it is diagnosed in approximately 8 per 1,000,000 individuals per year in that age group. In New York City (including all five boroughs), the number of young adults in this age range is approximately 1,400,000.__\n\n::: blue\n* Let $X$ be the number of young adults diagnosed with osteosarcoma in NYC in a given year\n  * The probability of diagnosis is $p = 8/1,000,000$ .\n  * The number of young adults in this age range living in New York City is $n=1,400,000$ .\n* Then $X\\sim Bin(n=1,400,000, p=\\frac{8}{1,000,000}$ assuming that all of the young adults in NYC get osteosarcoma independently of each other.\n* Based on the rule of thumb shown in class ( $\\frac{1}{10} \\leq np(1-p) \\leq 10$ )\n    * $X$ does not satisfy the criteria to be approximated by a Poisson random variable since $np(1-p)$ is bigger than 10:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 1400000\np <- 8/1000000\n\n(npq <- n*p*(1-p))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11.19991\n```\n:::\n:::\n\n\n\n$$np(1-p) = 1,400,000 \\cdot \\frac{8}{1,000,000}\\cdot \\frac{999,992}{1,000,000} = 11.2$$\n\n* However, \n    * since\n        * the textbook doesn't mention this rule of thumb,\n        * 11.2 is only slightly bigger than 10, and\n        * this exercise is in the Poisson distribution section of the book,\n    * we will proceed to use the Poisson distribution to model osteosarcoma cases.\n* But!! \n    * if this problem were on the exam, \n    * you should check the rule of thumb and then decide that the Binomial distribution is a more appropriate model for these questions.\n:::\n\n### a {.unnumbered}\n\n__What is the expected number of cases of osteosarcoma in NYC in a given year?__\n\n::: blue\n*Note: Regardless of whether $X$ is being modeled by a binomial or Poisson distribution, the expected number of cases is $np$.*\n\nLet $X$ be a Poisson random variable with $\\lambda=np=1,400,000 \\cdot \\frac{8}{1,000,000}$ cases per year:\n\n$$X \\sim Pois (\\lambda = 1,400,000 \\cdot \\frac{8}{1,000,000}=11.2)$$  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(np <- n*p)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11.2\n```\n:::\n:::\n\n\n\n* The expected value of a Poisson random variable is $\\lambda$, which is 11.2.\n\n\nThe expected number of cases of osteosarcoma in NYC amongst young adults in a given year is 11.2.\n:::\n\n### b {.unnumbered}\n\n__What is the probability that 15 or more cases will be diagnosed in a given year?__\n\n::: blue\nWe still are using $X \\sim Pois (\\lambda = 11.2)$.   \n\nThe probability that 15 or more cases will be diagnosed in a given year is:\n\n\\begin{align}\nP(X \\geq 15) &= 1 - P(X < 15) \\\\\n&= 1 - P(X \\leq 14) \\\\\n&= 1 - \\sum_{k=0}^{14} \\frac{e^{-11.2} (11.2)^{k}}{k!}\n\\end{align}\n\nThere are various ways this can be calculated.\n\n* Calculated \"directly\" in R using the formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# vector of x values whose probabilities need to be added\nx <- 0:14  \n# vector of respective Poisson prob's of x values\n(Poisson_prob_0_14 <- exp(-11.2)*(11.2^x)/factorial(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 0.0000136742 0.0001531510 0.0008576456 0.0032018768 0.0089652551\n [6] 0.0200821714 0.0374867200 0.0599787520 0.0839702528 0.1044963146\n[11] 0.1170358723 0.1191637973 0.1112195441 0.0958199149 0.0766559320\n```\n:::\n\n```{.r .cell-code}\n# add up the probabilities\n1 - sum(Poisson_prob_0_14)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1608991\n```\n:::\n:::\n\n\n\nUsing the R command `ppois` we have two options depending on whether we use `lower.tail = TRUE` or `lower.tail = FALSE`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(X >= 15) for Pois(lambda = 11.2) random variable\n# P(X >= 15) = 1 - P(X <= 14)\n1 - ppois(q = 14, lambda = 11.2, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1608991\n```\n:::\n\n```{.r .cell-code}\n# P(X >= 15) for Pois(lambda = 11.2) random variable\n# P(X >= 15) = P(X > 14)\n(Pgeq15 <- ppois(q = 14, lambda = 11.2, lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1608991\n```\n:::\n:::\n\n\n\nThe probability that 15 or more cases of osteosarcoma will be diagnosed in a given year in NYC amongst young adults is 0.161.\n:::\n\n### c {.unnumbered}\n\n__The largest concentration of young adults in NYC is in the borough of Brooklyn, where the population in that age range is approximately 450,000. What is the probability of 10 or more cases in Brooklyn in a given year?__\n\n::: blue\nFirst, calculate $\\lambda_B$ given that n=450,000 for Brooklyn.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnB <- 450000\n(nBp <- nB*p)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.6\n```\n:::\n:::\n\n\n\n$$X_B \\sim Pois (\\lambda_B = 450,000 \\cdot \\frac{8}{1,000,000}= 3.6)$$  \n\nThen, the probability of 10 or more cases in Brooklyn in a given year is\n\n\\begin{align}\nP(X_B \\geq 10) &= 1 - P(X_B < 10) \\\\\n&= 1 - P(X_B \\leq 9) \\\\\n&= 1 -\\sum_{k=0}^{9} \\frac{e^{-3.6} (3.6)^{k}}{k!}\n\\end{align}\n\nThere are various ways this can be calculated.\n\n* Calculated \"directly\" in R using the formula:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# vector of x values whose probabilities need to be added\nx <- 0:9  \n# vector of respective Poisson prob's of x values\n(Poisson_prob_0_9 <- exp(-3.6)*(3.6^x)/factorial(x))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 0.027323722 0.098365401 0.177057721 0.212469266 0.191222339 0.137680084\n [7] 0.082608051 0.042484140 0.019117863 0.007647145\n```\n:::\n\n```{.r .cell-code}\n# add up the probabilities\n1 - sum(Poisson_prob_0_9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.004024267\n```\n:::\n:::\n\n\n\nUsing the R command `ppois` we have two options depending on whether we use `lower.tail = TRUE` or `lower.tail = FALSE`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(X >= 10) for Pois(lambda = 3.6) random variable\n# P(X >= 10) = 1 - P(X <= 9)\n1 - ppois(q = 9, lambda = 3.6, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.004024267\n```\n:::\n\n```{.r .cell-code}\n# P(X >= 10) for Pois(lambda = 3.6) random variable\n# P(X >= 10) = P(X > 9)\n(Pgeq10 <- ppois(q = 9, lambda = 3.6, lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.004024267\n```\n:::\n:::\n\n\n\n\nThe probability of observing 10 or more cases of osteosarcoma will be diagnosed in a given year in Brooklyn in a given year is 0.004.\n:::\n\n### d {.unnumbered}\n\n__Suppose that in a given year, 10 cases of osteosarcoma were observed in NYC, with all 10 cases occurring among young adults living in Brooklyn. An official from the NYC Public Health Department claims that the probability of this event (that is, the probability of 10 or more cases being observed, and all of them occurring in Brooklyn) is what was calculated in part c). Is the official correct? Explain your answer. You may assume that your answer to part c) is correct. This question can be answered without doing any calculations.__\n\n::: blue\n* The official is not correct since the probability calculated in (c) is restricted to only cases within Brooklyn and in particular depended on the size of Brooklyn. This probability ignored all other boroughs. \n\n* If boroughs are independent of each other, then the probability of 10 or more cases being observed, and all of them occurring in Brooklyn is \n\n$$P(Y= 0~\\textrm{in boroughs other than Brooklyn}) \\cdot P(X \\geq 10~\\textrm{in Brooklyn}),$$\n\nwhere $Y$ is a Poisson distribution with its rate $\\lambda$ dependent on the sample size of all the boroughs excluding Brooklyn.\n\nThe official would be correct if $P(Y= 0~\\textrm{in boroughs other than Brooklyn})=1$, but we do not expect this to the case.\n:::\n\n### e {.unnumbered}\n\n__Suppose that over five years, there was one year in which 10 or more cases of osteosarcoma were observed in Brooklyn. Is the probability of this event equal to the probability calculated in part c)? Explain your answer.__\n\n::: blue\n* No, these are not the same probabilities. \n* Assuming cases in different years are independent of each other, then the probability of 10 or more cases in Brooklyn in a single year, over 5 different years is modeled by a \n    * binomial distribution with \n    * $n = 5$ years and\n    * $p$ being the probability of 10 or more cases in Brooklyn in a single year.\n\nNote that $p$ is the probability that was calculate in part (c):\n\n$$p=P(X_B \\geq 10) = 0.004.$$\nLet $Y\\sim Bin(n=5, p = 0.004)$. \n  \nThen, the probability that over five years, there was one year in which 10 or more cases of osteosarcoma were observed in Brooklyn is\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Py1 <- choose(5,1) * Pgeq10^1 * (1-Pgeq10)^4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01979939\n```\n:::\n:::\n\n\n\n\n$$P(Y = 1) = \\binom{5}{1}(0.004)^1 (0.996)^{5-1} = 0.02$$\n\nOr using R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# P(Y = 1) for Bin(n=5, p=Pgeq10) random variable\nPgeq10\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.004024267\n```\n:::\n\n```{.r .cell-code}\ndbinom(x = 1, size = 5, prob = Pgeq10) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01979939\n```\n:::\n:::\n\n\n:::\n\n# R exercises\n\n## R exercise 1\n\nBelow you will be using a dataset from Gapminder to complete a few R exercises.\n\n### Load all the packages you need below here\n\nYou don't need to do it all at once, you can add more libraries as you realize you need them.\n\n::: blue\n\n\n::: {.cell}\n\n:::\n\n\n:::\n\n### Import dataset\n\nImport the dataset called \"Gapminder_2011_LifeExp_CO2.csv\" You can find it in the student files under Data then Homework. You will need to download the file onto your computer, and use the correct file path to import the data. \n\n::: blue\n\n\n::: {.cell}\n\n:::\n\n\n:::\n\n### Make a histogram\n\nUsing `ggplot2`, make a histogram of the variable `CO2emissions`.\n\n::: blue\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](HW_04_ans_files/figure-pdf/unnamed-chunk-16-1.pdf)\n:::\n:::\n\n\n:::\n\n",
    "supporting": [
      "HW_04_ans_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}