---
title: "Muddy Points"
date: "10/7/2024"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## 1. COVID-19 rapid testing example!

Here's another video and PDF with a better explanation of what we did in class!

[Please follow this link for my work through of the example.](https://ohsuitg-my.sharepoint.com/:v:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525/Recordings/04_Cond_prob_example.mp4?csf=1&web=1&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=urPXgR) 

And [here is the PDF with my work](/lessons/04_Cond_prob/04_Cond_prob_example.pdf).

## 2. Bayes' theorem: applications

See the last two questions in the above example for the application of Bayes' Theorem!!

## 3. 2 x 2 diagnostic table for diagnostic problems

See above link to video and pdf where I use the 2 x 2 table. It's not necessary for this type of problem, but you can use it! I also like tree diagrams, which I included in the example above. 

### Can we use a 2x2 in homework solutions?

Yes, definitely!! But do not confuse a 2x2 diagnostic table with the probability or contingency tables. The diagnostic table puts conditional probabilities in the cells instead of joint probabilities!!

## 4. Will probability language be necessary to remember for assignments in the future?

Not in such a precise way like we use them in this week's word problems. Understanding joint, marginal, and conditional probabilities are important. And knowing the mathematical implications of independent and not independent events. Honestly, it's more important for you to have a sense of what someone means when they (most likely me hehe) use those words in passing to define something else. There are a lot of statistics methods that hinge on independence, joint, marginal, and conditional.

## 5. Does the upside down U mean "intersection", "union", as well as "and"?

- $\cup$ means "union" and "or." You can think of $A \cup B$ as: event A on its own OR event B on its own OR both events

- $\cap$ means "intersection" and "and." You can think of $A \cap B$ as: event A and B happening (cannot be each on their own)

- [Here's me posing a similar question to ChatGPT](https://chatgpt.com/share/6709715f-8d34-8006-806c-08aa4d8d101f)

## 6. Why does $P(B|A) + P(B^c|A) = 1$?

A few facts will help us here:

- $B$ and $B^c$ are disjoint events (this is by nature of complements)
- For disjoint events, the probability of the union is the addition of each probability: $$P(B \cup B^c) = P(B) + P(B^c)$$
- $P(B|A) = \dfrac{P(B\cap A)}{P(A)}$ and we can even extend this to something like $P(D \cup C|A) = \dfrac{P([D \cup C]\cap A)}{P(A)}$
  - No matter what is on the left or right side of the "|" (given) statement, we can apply the same conditional probability

We can start with the fact that

$$P(B \cup B^c | A) = 1$$

Why is that?

$$\begin{aligned}
P(B \cup B^c | A) = \dfrac{P([B \cup B^c]\cap A)}{P(A)}
\end{aligned}$$

The union ($\cup$) of $B$ and $B^c$ is the sample space, so when we talk about $[B \cup B^c]\cap A$, we are asking about the shared space between the sample space and $A$, which is just $A$

So....

$$\begin{aligned}
P(B \cup B^c | A) = & \dfrac{P([B \cup B^c]\cap A)}{P(A)} \\ 
= & \dfrac{P(S\cap A)}{P(A)} \\ 
= & \dfrac{P(A)}{P(A)} \\ 
= & 1 \\ 
\end{aligned}$$

So we have shown $$P(B \cup B^c | A) = 1$$

Now we can split $P(B \cup B^c | A)$ into a different form since $B$ and $B^c$ are disjoint:

$$\begin{aligned}
P(B \cup B^c | A) = & 1 \\ 
\dfrac{P([B \cup B^c]\cap A)}{P(A)} = & 1 \\ 
\dfrac{P(B\cap A) + P(B^c \cap A)}{P(A)}= & 1 \\ 
\dfrac{P(B\cap A)}{P(A)} + \dfrac{P(B^c \cap A)}{P(A)}= & 1 \\ 
P(B|A) + P(B^c|A)= & 1\\ 
\end{aligned}$$
