{
  "hash": "d86230c665b0b620ab228f3f6b83dabe",
  "result": {
    "markdown": "---\ntitle: \"DRAFT Day 10: Hypothesis testing for one-sample mean (4.3, 5.1) & two-sample paired data mean (5.2)\"\nsubtitle: \"BSTA 511/611\"\nauthor: \"Meike Niederhausen, PhD\"\ninstitute: \"OHSU-PSU School of Public Health\"\ndate: \"11/1/2023\"\ncategories: [\"Week 6\"]\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n# editor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n## Load packages\n\n* Packages need to be loaded _every time_ you restart R or render an Qmd file\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run these every time you open Rstudio\nlibrary(tidyverse)    \nlibrary(oibiostat)\nlibrary(janitor)\nlibrary(rstatix)\nlibrary(knitr)\nlibrary(gtsummary)\nlibrary(moderndive)\nlibrary(gt)\nlibrary(broom) # NEW!!\n\nset.seed(456)\n```\n:::\n\n\n\n- You can check whether a package has been loaded or not \n  - by looking at the Packages tab and \n  - seeing whether it has been checked off or not\n\n\n# Goals for today\n\n## Part 1 \n\n### (4.3, 5.1) Hypothesis testing for mean from one sample  \n\n* Introduce hypothesis testing using the case of analyzing a mean from one sample (group)\n\n::: columns\n::: {.column width=\"50%\"}\n* [Steps of a hypothesis test:]{style=\"color:purple\"}\n    1. level of significance\n    1. null ( $H_0$ ) and alternative ( $H_A$ ) hypotheses\n    1. test statistic\n    1. p-value\n    1. conclusion\n:::\n::: {.column width=\"50%\"}\n* [Run a hypothesis test in R]{style=\"color:green\"}\n    * Load a dataset - need to specify location of dataset\n    * R projects\n    * Run a t-test in R\n    * `tidy()` the test output using `broom` package\n:::\n:::\n\n### (4.3.3) Confidence intervals (CIs) vs. hypothesis tests \n\n\n## Part 2 - Class discussion\n\n### (5.2) Inference for __mean difference__ from dependent/paired 2 samples  \n\n* Inference: CIs and hypothesis testing\n* Exploratory data analysis (EDA) to visualize data\n* Run paired t-test in R\n\n### One-sided CIs\n\n### Class discussion\n\n* Inference for the mean difference from dependent/paired data is a special case of the inference for the mean from just one sample, that was already covered.\n* Thus this part will be used for class discussion to practice CIs and hypothesis testing for one mean and apply it in this new setting.\n* In class I will briefly introduce this topic, explain how it is similar and different from what we already covered, and let you work through the slides and code. \n\n\n## MoRitz's tip of the day: use [__R projects__]{style=\"color:darkorange\"} to organize analyses\n\n\nMoRitz loves using R projects to \n\n* organize analyses and \n* make it easier to load data files \n* and also save output\n\nOther bonuses include \n\n* making to it easier to collaborate with others, \n* including yourself when accessing files from different computers.\n\n<br>\n\n\nWe will discuss how to use projects later in today's slides when loading a dataset.  \nSee file [Projects in RStudio](../resources/Projects_in_R.html) for more information.\n\n\n\n# Is 98.6°F  really the mean \"healthy\" body temperature?\n\n* __Where did the 98.6°F value come from?__\n    * German physician Carl Reinhold August [Wunderlich](https://www.google.com/books/edition/_/a6UNq33GPfIC?hl=en&gbpv=1&pg=PP14) determined  98.6°F (or 37°C) based on temperatures from 25,000 patients in Leipzig in 1851.\n\n* [1992 JAMA article](https://jamanetwork.com/journals/jama/article-abstract/400116) by Mackowiak, Wasserman, & Levine\n    * They claim that 98.2°F (36.8°C) is a more accurate average body temp\n    * Sample: n = 148 healthy men and women aged 18 - 40 years\n\n* In January 2020, a group from Stanford published _[Decreasing human body temperature in the United States since the Industrial Revolution](https://elifesciences.org/articles/49555)_ in eLIFE.\n    * \"determined that mean body temperature in men and women, after adjusting for age, height, weight and, in some models date and time of day, has decreased monotonically by 0.03°C (0.05°F) per birth decade\"\n    * September 2023 update: _[Defining Usual Oral Temperature Ranges in Outpatients Using an Unsupervised Learning Algorithm](https://jamanetwork.com/journals/jamainternalmedicine/article-abstract/2809098)_ in JAMA Internal Medicine\n        * Average is 36.64 °C (97.95 °F); \"range of mean temperatures for the coolest to the warmest individuals was 36.24 °C to 36.89 °C\" (97.23 to 98.40 °F); based 2008-2017 data\n        * \"findings suggest that age, sex, height, weight, and time of day are factors that contribute to variations in individualized normal temperature ranges.\"\n\n* NYT article [The Average Human Body Temperature Is Not 98.6 Degrees](../resources/NYT_What_Is_a_Fever_Why_Your_Body_Temperature_May_Be_Cooler_Than_98.6_Degrees.pdf), Oct 12, 2023, by Dana G. Smith\n\n__[Question:]{style=\"color:darkorange\"} based on the 1992 JAMA data, is there evidence to support that the population mean body temperature is different from 98.6°F?__\n\n\n\n## Question: based on the 1992 JAMA data, is there evidence to support that the population mean body temperature is different from 98.6°F?\n\n\nTwo approaches to answer this question:\n\n1. Create a __[confidence interval (CI)]{style=\"color:purple\"}__ for the population mean $\\mu$ and determine whether 98.6°F is inside the CI or not.\n    * is 98.6°F a plausible value?\n\n2. Run a __[hypothesis test]{style=\"color:green\"}__ to see if there is evidence that the population mean $\\mu$ is _significantly different_ from 98.6°F or not.\n    * This does not give us a range of plausible values for the population mean $\\mu$.\n    \n    * Instead, we calculate a _test statistic_ and _p-value_ \n        * to see how likely we are to observe the sample mean $\\bar{x}$\n        * or a more extreme sample mean \n        * assuming that the population mean $\\mu$ is 98.6°F.\n\n\n\n### Approach 1: Create a [95% C I]{style=\"color:purple\"} for the population mean body temperature\n\n* Use data based on the results from the 1992 JAMA study\n    * The original dataset used in the JAMA article is not available\n    * However, Allen Shoemaker from Calvin College created a [dataset](http://jse.amstat.org/datasets/normtemp.dat.txt) with the same summary statistics as in the JAMA article, which we will use:\n\n$$\\bar{x} = 98.25,~s=0.733,~n=130$$\nCI for $\\mu$:\n\n\n\n\n\n\n\\begin{align}\n\\bar{x} &\\pm t^*\\cdot\\frac{s}{\\sqrt{n}}\\\\\n98.25 &\\pm 1.979\\cdot\\frac{0.733}{\\sqrt{130}}\\\\\n98.25 &\\pm 0.127\\\\\n(98.123&, 98.377)\n\\end{align}\n\nUsed $t^*$ = `qt(.975, df=129)` \n\nConclusion:  \nWe are 95% confident that the (population) mean body temperature is between 98.123°F and 98.377°F.\n\n* _How does the CI compare to 98.6°F?_\n\n\n### Approach 2: [Hypothesis Test]{style=\"color:green\"} \n\nFrom before: \n\n* Run a __hypothesis test__ to see if there is evidence that the population mean $\\mu$ is _significantly different_ from 98.6°F or not.\n    * This does not give us a range of plausible values for the population mean $\\mu$.\n    \n    * Instead, we calculate a _test statistic_ and _p-value_ \n        * to see how likely we are to observe the sample mean $\\bar{x}$\n        * or a more extreme sample mean \n        * assuming that the population mean $\\mu$ is 98.6°F.\n\n__How do we calculate a _test statistic_ and _p-value_?__\n\n\n\n\n### Recall the sampling distribution of the mean\n\nFrom the __[Central Limit Theorem (CLT)]{style=\"color:darkorange\"}__, we know that\n\n* For **[\"large\" sample sizes]{style=\"color:cornflowerblue\"}** ( $n\\geq 30$ ),\n    * the [__sampling distribution__ of the sample mean]{style=\"color:green\"}\n    * can be approximated by a __normal distribution__,with \n      * _mean_ equal to the _population mean_ value $\\mu$, and \n      * _standard deviation_ $\\frac{\\sigma}{\\sqrt{n}}$\n\n$$\\bar{X}\\sim N\\Big(\\mu_{\\bar{X}} = \\mu, \\sigma_{\\bar{X}}= \\frac{\\sigma}{\\sqrt{n}}\\Big)$$\n\n* For **[small sample sizes]{style=\"color:cornflowerblue\"}**, if the population is known to be normally distributed, then\n    * the same result holds\n\n\n\n### Case 1: suppose we know the population sd $\\sigma$\n\n* [How likely we are to observe the sample mean $\\bar{x}$ ,]{style=\"color:green\"}\n    * [or a more extreme sample mean, ]{style=\"color:green\"}\n    * [assuming that the population mean $\\mu$ is 98.6°F?]{style=\"color:green\"}\n* Use $\\bar{x} = 98.25$, $\\sigma=0.733$, and $n=130$\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-4-1.png){width=576}\n:::\n:::\n\n\n\n### Case 2: we don't know the population sd $\\sigma$ \n\n\n* This is usually the case in real life\n* We estimate $\\sigma$ with the sample standard deviation $s$\n* From last time, we know that in this case we need to use the __t-distribution with d.f. = n-1__, instead of the normal distribution \n* [Question: How likely we are to observe the sample mean $\\bar{x}$ or a more extreme sample mean, assuming that the population mean $\\mu$ is 98.6°F?]{style=\"color:green\"}\n* Use $\\bar{x} = 98.25$, $s=0.733$, and $n=130$\n\n\n# Steps in a Hypothesis Test\n\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[null]{style=\"color:darkorange\"}__ ( $H_0$ ) and __[alternative]{style=\"color:darkorange\"}__ ( $H_A$ ) __[hypotheses]{style=\"color:darkorange\"}__\n    1. In symbols\n    1. In words\n    1. Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n    1. Do we reject or fail to reject $H_0$?\n    1. Write a conclusion in the context of the problem\n\n\n\n## Step 2: Null & Alternative Hypotheses\n\nIn statistics, a __hypothesis__ is a statement about the value of an __unknown population parameter__.\n\n\nA __[hypothesis test]{style=\"color:darkorange\"}__ consists of a test between two competing hypotheses: \n\n1. a __[null]{style=\"color:darkorange\"}__ hypothesis $H_0$ (pronounced “H-naught”) vs. \n1. an __[alternative]{style=\"color:darkorange\"}__ hypothesis $H_A$ (also denoted $H_1$)\n\nExample of hypotheses in words: \n\n\\begin{aligned}\nH_0 &: \\text{The population mean body temperature is 98.6°F}\\\\\n\\text{vs. } H_A &: \\text{The population mean body temperature is not 98.6°F}\n\\end{aligned}\n\n1. $H_0$ is a claim that there is “no effect” or “no difference of interest.”\n1. $H_A$ is the claim a researcher wants to establish or find evidence to support. It is viewed as a “challenger” hypothesis to the null hypothesis $H_0$\n\n### Notation for hypotheses\n\n\\begin{aligned}\nH_0 &: \\mu = \\mu_0\\\\\n\\text{vs. } H_A&: \\mu \\neq, <, \\textrm{or}, > \\mu_0\n\\end{aligned}\n\nWe call $\\mu_0$ the *null value*\n\n::: columns\n::: {.column width=\"40%\"}\n$H_A: \\mu \\neq \\mu_0$\n\n::: {style=\"font-size: 90%;\"}\n* not choosing a priori whether we believe the population mean is greater or less than the null value $\\mu_0$\n:::\n:::\n\n::: {.column width=\"30%\"}\n$H_A: \\mu < \\mu_0$\n\n::: {style=\"font-size: 90%;\"}\n* believe the population mean is **less** than the null value $\\mu_0$\n:::\n:::\n\n::: {.column width=\"30%\"}\n$H_A: \\mu > \\mu_0$\n\n::: {style=\"font-size: 90%;\"}\n* believe the population mean is **greater** than the null value $\\mu_0$\n:::\n:::\n:::\n\n* $H_A: \\mu \\neq \\mu_0$ is the most common option, since it's the most conservative\n\nExample: \n\n\\begin{aligned}\nH_0 &: \\mu = 98.6\\\\\n\\text{vs. } H_A&: \\mu \\neq 98.6\n\\end{aligned}\n\n\n\n## Step 3: [Test statistic]{style=\"color:darkorange\"} (& its distribution)\n\n__[Case 1: know population sd $\\sigma$]{style=\"color:purple\"}__\n\n$$\n\\text{test statistic} = z_{\\bar{x}} = \\frac{\\bar{x} - \\mu_0}{\\frac{\\sigma}{\\sqrt{n}}}\n$$\n\n* Statistical theory tells us that [$z_{\\bar{x}}$]{style=\"color:purple\"} follows a [__Standard Normal distribution__ $N(0,1)$]{style=\"color:purple\"}\n\n\n__[Case 2: don't know population sd $\\sigma$]{style=\"color:green\"}__\n\n$$\n\\text{test statistic} = t_{\\bar{x}} = \\frac{\\bar{x} - \\mu_0}{\\frac{s}{\\sqrt{n}}}\n$$\n\n* Statistical theory tells us that [$t_{\\bar{x}}$]{style=\"color:green\"} follows a [__Student's t distribution__ with degrees of freedom (df) = $n-1$]{style=\"color:green\"}\n\n\n\n$\\bar{x}$ = sample mean,  \n$\\mu_0$ = hypothesized population mean from $H_0$,  \n$\\sigma$ = _population_ standard deviation,  \n$s$ = _sample_ standard deviation,   \n$n$ = sample size\n\n__[Assumptions]{style=\"color:darkorange\"}__: same as CLT\n\n* __Independent observations__ \n    * The observations were collected independently.\n* __Approximately normal sample or big n__ \n    * The distribution of the sample should be approximately normal \n    * _or_ the sample size should be at least 30.\n\n## Step 3: Test statistic calculation\n\nRecall that $\\bar{x} = 98.25$, $s=0.733$, and $n=130.$\n\nThe test statistic is:\n\n$$t_{\\bar{x}} = \\frac{\\bar{x} - \\mu_0}{\\frac{s}{\\sqrt{n}}}\n= \\frac{98.25 - 98.6}{\\frac{0.73}{\\sqrt{130}}}\n= -5.45$$\n\n* Statistical theory tells us that $t_{\\bar{x}}$ follows a __Student's t-distribution__ with $d.f. = n-1 = 129$.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-5-1.png){width=576}\n:::\n:::\n\n\n\n__Assumptions met?__\n\n## Step 4: p-value\n\nThe __[p-value]{style=\"color:darkorange\"}__ is the [__probability__ of obtaining a test statistic _just as extreme or more extreme_ than the observed test statistic assuming the null hypothesis $H_0$ is true.]{style=\"color:darkblue\"} \n\n\n* The $p$-value is a quantification of \"surprise\"\n    * Assuming $H_0$ is true, _how surprised are we with the observed results_?\n    * _Ex_: assuming that the true mean body temperature is 98.6°F, how surprised are we to get a sample mean of 98.25°F  (or more extreme)?\n    \n* If the $p$-value is \"small,\" it means there's a small probability that we would get the observed statistic (or more extreme) when $H_0$ is true.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-6-1.png){width=576}\n:::\n:::\n\n\n\n## Step 4: p-value calculation \n\nCalculate the _p_-value using the __Student's t-distribution__ with $d.f. = n-1 = 129$:\n\n$$p-value=P(T \\leq -5.45) + P(T \\geq 5.45) = 2.410889 \\times 10^{-07}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use pt() instead of pnorm()\n# need to specify df\n2*pt(-5.4548, df = 130-1, lower.tail = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.410889e-07\n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-8-1.png){width=576}\n:::\n:::\n\n\n## Step 4: p-value estimation using $t$-table\n\n* $t$-table only gives us *bounds* on the p-value\n* Recall from using the $t$-table for CIs, that the table gives us the cutoff values for varying tail probabilities (1-tail & 2-tail)\n* Find the row with the appropriate degrees of freedom\n    * Use next smallest df in table if actual df not shown\n    * I.e., for df = 129, use df = 100 in table\n* Figure out where the test statistic's absolute value is in relation to the values in the columns, i.e. between which columns is the test statistic?\n* The header rows for those columns gives the lower & upper bounds for the p-value\n    * Choosing one-tail vs. two-tail test, depends on the alternative hypothesis $H_A$.\n    * For a 2-sided test ( $H_A: \\mu \\neq \\mu_0$ ), use two-tails \n    * For a 1-sided test ( $H_A: \\mu < \\textrm{or} > \\mu_0$ ), use one-tail \n    \n\n## Step 1: Significance Level $\\alpha$\n\n* __Before doing a hypothesis test__, we set a cut-off for how small the $p$-value should be in order to reject $H_0$.\n* We call this the __[significance level]{style=\"color:darkorange\"}__, denoted by the Greek symbol [alpha ( $\\alpha$ )]{style=\"color:darkorange\"}\n* [Typical $\\alpha$]{style=\"color:darkblue\"} values are \n    * 0.05 - _most common by far!!_\n    * 0.01 and 0.1\n* Decision rule:    \n    * When [$p$-value < $\\alpha$]{style=\"color:green\"}, we \"__[reject]{style=\"color:green\"}__ the null hypothesis [$H_0$]{style=\"color:green\"}.\"\n    * When [$p$-value $\\geq \\alpha$]{style=\"color:purple\"}, we \"__[fail to reject]{style=\"color:purple\"}__ the null hypothesis [$H_0$]{style=\"color:purple\"}.\"\n\n:::{.callout-important}\n* \"Failing to reject\" $H_0$ is __NOT__ the same as \"accepting\" $H_0$! \n* By failing to reject $H_0$ we are just saying that we don't have sufficient evidence to support the alternative $H_A$.\n* _This does not imply that $H_0$ is true!!_\n:::\n\n\n\n## Step 5: Conclusion to hypothesis test\n\n\\begin{aligned}\nH_0 &: \\mu = 98.6\\\\\n\\text{vs. } H_A&: \\mu \\neq 98.6\n\\end{aligned}\n\n* Recall the $p$-value = $2.410889 \\times 10^{-07}$ \n* Use $\\alpha$ = 0.05.\n* Do we reject or fail to reject $H_0$?\n\n__Conclusion statement__:\n\n* Basic: (\"stats class\" conclusion)\n    * There is sufficient evidence that the (population) mean body temperature is discernibly different from 98.6°F ( $p$-value < 0.001).\n\n* Better: (\"manuscript style\" conclusion)\n    * The average body temperature in the sample was 98.25°F (95% CI 98.12, 98.38°F), which is discernibly different from 98.6°F ( $p$-value < 0.001).\n\n## Confidence Intervals vs. Hypothesis Testing\n\n* See also V&H Section 4.3.3\n\n# Running a t-test in R\n\n* Working directory\n* Load a dataset - need to specify location of dataset\n* R projects\n* Run a t-test in R\n* `tidy()` the test output using `broom` package\n\n## Working directory\n\n* In order to load a dataset from a file, you need to tell R where the dataset is located\n* To do this you also need to know the location from which R is working, i.e. your __working directory__\n* You can figure out your working directory by running the `getwd()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngetwd()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"/Users/niederha/Library/CloudStorage/OneDrive-OregonHealth&ScienceUniversity/teaching/BSTA 511/F23/0_webpage/BSTA_511_F23\"\n```\n:::\n:::\n\n\n* Above is the working directory of this slides file\n    * _In this case, this is NOT the location of the actual qmd file though!_\n\n* To make it easier to juggle the working directory, the location of your qmd file, and the location of the data, \n    * [I highly recommend using __R Projects__!]{style=\"color:darkred\"}\n\n## R projects\n\n* I *highly, highly, HIGHLY* recommend using R Projects to organize your analyses and make it easier to load data files and also save output.\n* When you create an R Project on your computer, the Project is associated with the folder (directory) you created it in. \n  * This folder becomes the \"root\" of your working directory, and RStudio's point of reference from where to load files from and to. \n* I create separate Projects for every analysis project and every class I teach. \n* You can run multiple sessions of RStudio by opening different Projects, and the environments (or working directory) of each are working independently of each other. \n\n:::{.callout-note}\n* Although we are using Quarto files, \n    * I will show how to set up and use a __\"regular\" R Project__\n    * instead of \"Quarto Project\"\n* Quarto Projects include extra features and thus complexity. Once you are used to how regular R Projects work, you can try out a Quarto Project. \n:::\n\n## How to create an R Project\n\n* Demonstration in class recording\n* Posit's (RStudio's) directions for creating Projects\n  * [https://support.rstudio.com/hc/en-us/articles/200526207-Using-RStudio-Projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-RStudio-Projects)\n\n* See file [Projects in RStudio](../slides_code/Projects_in_R.html) for more information on R Projects.\n\n\n## Load the dataset\n\n* The data are in a csv file called `BodyTemperatures.csv`\n* You need to tell R where the dataset is located!\n* I recommend saving all datasets in a folder called data. \n    * The code I will be providing you will be set up this way.\n\n* To make it easier to specify where the dataset is located, I recommend using the `here()` function from the `here` package: `here::here()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read_csv() is a function from the readr package that is a part of the tidyverse\nlibrary(here)   # first install this package\n\nBodyTemps <- read_csv(here::here(\"data\", \"BodyTemperatures.csv\"))\n#                     location: look in \"data\" folder\n#                               for the file \"BodyTemperatures.csv\"\n\nglimpse(BodyTemps)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 130\nColumns: 3\n$ Temperature <dbl> 96.3, 96.7, 96.9, 97.0, 97.1, 97.1, 97.1, 97.2, 97.3, 97.4…\n$ Gender      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ HeartRate   <dbl> 70, 71, 74, 80, 73, 75, 82, 64, 69, 70, 68, 72, 78, 70, 75…\n```\n:::\n:::\n\n\n## `here::here()`\n\nGeneral use of `here::here()`\n\n`here::here(\"folder_name\", \"filename\")`\n\nResources for `here::here()`:\n\n* [how to use the `here` package](http://jenrichmond.rbind.io/post/how-to-use-the-here-package/) (Jenny Richmond)\n* [Ode to the here package](https://github.com/jennybc/here_here) (Jenny Bryan)\n\n[Project-oriented workflow](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/) (Jenny Bryan)\n\n\n\n## `t.test`: base R's function for testing one mean \n\n* Use the body temperature example with $H_A: \\mu \\neq 98.6$\n* We called the dataset `BodyTemps` when we loaded it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(BodyTemps)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 130\nColumns: 3\n$ Temperature <dbl> 96.3, 96.7, 96.9, 97.0, 97.1, 97.1, 97.1, 97.2, 97.3, 97.4…\n$ Gender      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ HeartRate   <dbl> 70, 71, 74, 80, 73, 75, 82, 64, 69, 70, 68, 72, 78, 70, 75…\n```\n:::\n\n```{.r .cell-code}\n(temps_ttest <- t.test(x = BodyTemps$Temperature,\n       # alternative = \"two.sided\",  # default\n       mu = 98.6))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  BodyTemps$Temperature\nt = -5.4548, df = 129, p-value = 2.411e-07\nalternative hypothesis: true mean is not equal to 98.6\n95 percent confidence interval:\n 98.12200 98.37646\nsample estimates:\nmean of x \n 98.24923 \n```\n:::\n:::\n\n\nNote that the test output also gives the 95% CI using the t-distribution.\n\n\n## `tidy()` the `t.test` output\n\n* Use the `tidy()` function from the `broom` package for briefer output in table format that's stored as a `tibble`\n* Combined with the `gt()` function from the `gt` package, we get a nice table \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(temps_ttest) %>% \n  gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"mecfuynzio\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mecfuynzio table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mecfuynzio thead, #mecfuynzio tbody, #mecfuynzio tfoot, #mecfuynzio tr, #mecfuynzio td, #mecfuynzio th {\n  border-style: none;\n}\n\n#mecfuynzio p {\n  margin: 0;\n  padding: 0;\n}\n\n#mecfuynzio .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mecfuynzio .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mecfuynzio .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mecfuynzio .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mecfuynzio .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mecfuynzio .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mecfuynzio .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mecfuynzio .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mecfuynzio .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mecfuynzio .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mecfuynzio .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mecfuynzio .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mecfuynzio .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mecfuynzio .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mecfuynzio .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecfuynzio .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mecfuynzio .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mecfuynzio .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mecfuynzio .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecfuynzio .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mecfuynzio .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecfuynzio .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mecfuynzio .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecfuynzio .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mecfuynzio .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mecfuynzio .gt_left {\n  text-align: left;\n}\n\n#mecfuynzio .gt_center {\n  text-align: center;\n}\n\n#mecfuynzio .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mecfuynzio .gt_font_normal {\n  font-weight: normal;\n}\n\n#mecfuynzio .gt_font_bold {\n  font-weight: bold;\n}\n\n#mecfuynzio .gt_font_italic {\n  font-style: italic;\n}\n\n#mecfuynzio .gt_super {\n  font-size: 65%;\n}\n\n#mecfuynzio .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mecfuynzio .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mecfuynzio .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mecfuynzio .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mecfuynzio .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mecfuynzio .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mecfuynzio .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">98.24923</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-5.454823</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">2.410632e-07</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">129</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">98.122</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">98.37646</td>\n<td headers=\"method\" class=\"gt_row gt_left\">One Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n* Since the `tidy()` output is a tibble, we can easily `pull()` specific values from it:\n\n::: columns\n::: {.column width=\"50%\"}\n\nUsing base R's `$`\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(temps_ttest)$p.value  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.410632e-07\n```\n:::\n:::\n\n\nAdvantage: quick and easy\n:::\n\n::: {.column width=\"50%\"}\nOr the `tidyverse` way: using `pull()` from `dplyr` package \n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(temps_ttest) %>% pull(p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.410632e-07\n```\n:::\n:::\n\n\nAdvantage: can use together with piping (`%>%`) other functions\n:::\n:::\n\n\n## What's next? \n\nCI's and hypothesis testing for different scenarios:\n\n\n| Day | Section |  Population parameter   |       Symbol        |       Point estimate       |            Symbol             |\n|:----:|:------:|:----------:|:--------:|:----------:|:-------:|\n| 10  |   5.1   |        Pop mean         |        $\\mu$        |        Sample mean         |           $\\bar{x}$           |\n| 10  |   5.2   | Pop mean of paired diff | $\\mu_d$ or $\\delta$ | Sample mean of paired diff |         $\\bar{x}_{d}$         |\n| 11  |   5.3   |    Diff in pop means    |    $\\mu_1-\\mu_2$    |    Diff in sample means    |    $\\bar{x}_1 - \\bar{x}_2$    |\n| 12  |   8.1   |     Pop proportion      |         $p$         |        Sample prop         |         $\\widehat{p}$         |\n| 12  |   8.2   |   Diff in pop prop's    |      $p_1-p_2$      |   Diff in sample prop's    | $\\widehat{p}_1-\\widehat{p}_2$ |\n\n\n\n# Day 10 Part 2: Inference for mean difference from two-sample dependent/paired data  (Section 5.2)\n\n## What we covered in Day 10 Part 1 \n\n### (4.3, 5.1) Hypothesis testing for mean from one sample  \n\n* Introduce hypothesis testing using the case of analyzing a mean from one sample (group)\n\n::: columns\n::: {.column width=\"50%\"}\n* [Steps of a hypothesis test:]{style=\"color:purple\"}\n    1. level of significance\n    1. null ( $H_0$ ) and alternative ( $H_A$ ) hypotheses\n    1. test statistic\n    1. p-value\n    1. conclusion\n:::\n::: {.column width=\"50%\"}\n* [Run a hypothesis test in R]{style=\"color:green\"}\n    * Load a dataset - need to specify location of dataset\n    * R projects\n    * Run a t-test in R\n    * `tidy()` the test output using `broom` package\n:::\n:::\n\n### (4.3.3) Confidence intervals (CIs) vs. hypothesis tests \n\n\n## Goals for today: Part 2 - Class discussion\n\n### (5.2) Inference for __mean difference__ from dependent/paired 2 samples  \n\n* Inference: CIs and hypothesis testing\n* Exploratory data analysis (EDA) to visualize data\n* Run paired t-test in R\n\n### One-sided CIs\n\n### Class discussion\n\n* Inference for the mean difference from dependent/paired data is a special case of the inference for the mean from just one sample, that was already covered.\n* Thus this part will be used for class discussion to practice CIs and hypothesis testing for one mean and apply it in this new setting.\n* In class I will briefly introduce this topic, explain how it is similar and different from what we already covered, and let you work through the slides and code. \n\n\n## CI's and hypothesis tests for different scenarios: \n\n::: {style=\"font-size: 90%;\"}\n$$\\text{point~estimate} \\pm z^*(or~t^*)\\cdot SE,~~\\text{test~stat} = \\frac{\\text{point~estimate}-\\text{null~value}}{SE}$$\n\nDay | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE\n--|--|--|--|--|--|--\n10 | 5.1 | Pop mean | $\\mu$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$\n10 | 5.2 | [Pop mean of paired diff]{style=\"color:green\"} | [$\\mu_d$ or $\\delta$]{style=\"color:green\"} | [Sample mean of paired diff]{style=\"color:green\"} | [$\\bar{x}_{d}$]{style=\"color:green\"}  | [**???**]{style=\"color:red\"}\n11 | 5.3 | Diff in pop <br> means | $\\mu_1-\\mu_2$ | Diff in sample <br> means | $\\bar{x}_1 - \\bar{x}_2$  |\n12 | 8.1 | Pop proportion | $p$ | Sample prop | $\\widehat{p}$  |\n12 | 8.2 | Diff in pop <br> proportions | $p_1-p_2$ | Diff in sample <br> proportions | $\\widehat{p}_1-\\widehat{p}_2$ |\n\n:::\n\n\n## Steps in a Hypothesis Test\n\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[null]{style=\"color:darkorange\"}__ ( $H_0$ ) and __[alternative]{style=\"color:darkorange\"}__ ( $H_A$ ) __[hypotheses]{style=\"color:darkorange\"}__\n    1. In symbols\n    1. In words\n    1. Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n    1. Do we reject or fail to reject $H_0$?\n    1. Write a conclusion in the context of the problem\n\n\n# Goals for today (Section 5.2)\n\n* Statistical inference for paired data (2 samples)\n    1. What are paired data?  \n    1. EDA of data\n    1. Hypothesis test\n    1. Confidence Interval\n    1. Run test in R\n\n\n## Examples of paired designs (two samples)\n\n* Enroll pairs of identical twins to study a disease\n* Enroll father & son pairs to study cholesterol levels\n* Studying pairs of eyes\n* Enroll people and collect data before & after an intervention (longitudinal data)\n* Book: Compare maximal speed of competitive swimmers wearing a wetsuit vs. wearing a regular swimsuit\n\n\n# Can a vegetarian diet change cholesterol levels?\n\n* __Scenario__:\n  * 24 non-vegetarian people were enrolled in a study\n  * They were instructed to adopt a vegetarian diet\n  * Cholesterol levels were measured before and after the diet\n* __Question__: Is there evidence to support that cholesterol levels changed after the vegetarian diet?\n* How to answer the question?\n  * First, calculate changes (differences) in cholesterol levels\n      * We usually do after - before if the data are longitudinal\n\n\nCalculate __CI for the mean difference__ $\\delta$:\n\n$$\\bar{x}_d \\pm t^*\\cdot\\frac{s_d}{\\sqrt{n}}$$\n\nRun a __hypothesis test__\n\nHypotheses\n\n$$H_0: \\delta = \\delta_0 \\\\\nH_A: \\delta \\neq \\delta_0 \\\\\n(or~ <, >)$$\n\n\nTest statistic\n\n$$\nt_{\\bar{x}_d} = \\frac{\\bar{x}_d - \\delta_0}{\\frac{s_d}{\\sqrt{n}}}\n$$\n\n\n## EDA: Explore the cholesterol data\n\n* Scenario:\n  * 24 non-vegetarian people were enrolled in a study\n  * They were instructed to adopt a vegetarian diet\n  * Cholesterol levels were measured before and after the diet\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchol <- read_csv(\"data/chol213.csv\")\nglimpse(chol)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 24\nColumns: 2\n$ Before <dbl> 195, 145, 205, 159, 244, 166, 250, 236, 192, 224, 238, 197, 169…\n$ After  <dbl> 146, 155, 178, 146, 208, 147, 202, 215, 184, 208, 206, 169, 182…\n```\n:::\n\n```{.r .cell-code}\nchol %>% get_summary_stats(type = \"common\") %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"zskwhnmeto\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zskwhnmeto table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zskwhnmeto thead, #zskwhnmeto tbody, #zskwhnmeto tfoot, #zskwhnmeto tr, #zskwhnmeto td, #zskwhnmeto th {\n  border-style: none;\n}\n\n#zskwhnmeto p {\n  margin: 0;\n  padding: 0;\n}\n\n#zskwhnmeto .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zskwhnmeto .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zskwhnmeto .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zskwhnmeto .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zskwhnmeto .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zskwhnmeto .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zskwhnmeto .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zskwhnmeto .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zskwhnmeto .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zskwhnmeto .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zskwhnmeto .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zskwhnmeto .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zskwhnmeto .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zskwhnmeto .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zskwhnmeto .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zskwhnmeto .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zskwhnmeto .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zskwhnmeto .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zskwhnmeto .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zskwhnmeto .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zskwhnmeto .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zskwhnmeto .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zskwhnmeto .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zskwhnmeto .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zskwhnmeto .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zskwhnmeto .gt_left {\n  text-align: left;\n}\n\n#zskwhnmeto .gt_center {\n  text-align: center;\n}\n\n#zskwhnmeto .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zskwhnmeto .gt_font_normal {\n  font-weight: normal;\n}\n\n#zskwhnmeto .gt_font_bold {\n  font-weight: bold;\n}\n\n#zskwhnmeto .gt_font_italic {\n  font-style: italic;\n}\n\n#zskwhnmeto .gt_super {\n  font-size: 65%;\n}\n\n#zskwhnmeto .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zskwhnmeto .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zskwhnmeto .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zskwhnmeto .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zskwhnmeto .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zskwhnmeto .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zskwhnmeto .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min\">min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"max\">max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"iqr\">iqr</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\">se</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci\">ci</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_center\">Before</td>\n<td headers=\"n\" class=\"gt_row gt_right\">24</td>\n<td headers=\"min\" class=\"gt_row gt_right\">137</td>\n<td headers=\"max\" class=\"gt_row gt_right\">250</td>\n<td headers=\"median\" class=\"gt_row gt_right\">179</td>\n<td headers=\"iqr\" class=\"gt_row gt_right\">44.5</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">187.792</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">33.160</td>\n<td headers=\"se\" class=\"gt_row gt_right\">6.769</td>\n<td headers=\"ci\" class=\"gt_row gt_right\">14.002</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_center\">After</td>\n<td headers=\"n\" class=\"gt_row gt_right\">24</td>\n<td headers=\"min\" class=\"gt_row gt_right\">125</td>\n<td headers=\"max\" class=\"gt_row gt_right\">215</td>\n<td headers=\"median\" class=\"gt_row gt_right\">165</td>\n<td headers=\"iqr\" class=\"gt_row gt_right\">38.0</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">168.250</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">26.796</td>\n<td headers=\"se\" class=\"gt_row gt_right\">5.470</td>\n<td headers=\"ci\" class=\"gt_row gt_right\">11.315</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n### EDA: Cholesterol levels before and after vegetarian diet\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(chol, aes(x=Before)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-16-1.png){width=480}\n:::\n\n```{.r .cell-code}\nggplot(chol, aes(x=Before)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-16-2.png){width=480}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(chol, aes(x=After)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-17-1.png){width=480}\n:::\n\n```{.r .cell-code}\nggplot(chol, aes(x=After)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-17-2.png){width=480}\n:::\n:::\n\n\n\n### EDA: Spaghetti plot of cholesterol levels before & after diet\n\n* Visualize the individual before vs. after diet changes in cholesterol levels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchol_long <- chol %>% \n  # need an ID column for the plot\n  # make it factor so that coloring is not on continuous scale\n  mutate(ID = factor(1:n())) %>% \n  # make data long for plot: \n  pivot_longer(\n    cols = Before:After,\n    names_to = \"Time\",  # need a column for Before & After on x-axis\n    values_to = \"Cholesterol\") %>% # need a column of all cholesterol values for y-axis\n  mutate(\n    # change Time a factor variable so that can reorder\n    # levels so that Before is before After\n    Time = factor(Time, levels = c(\"Before\", \"After\"))\n    )\n  \nggplot(chol_long, \n       aes(x=Time, y = Cholesterol, \n           # need to include group = ID \n           # to create a line for each ID\n           color = ID, group = ID)) + \n  geom_line(show.legend = FALSE)\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-18-1.png){width=480}\n:::\n:::\n\n\n\n### EDA: Differences in cholesterol levels: After - Before diet\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchol <- chol %>% \n  mutate(DiffChol = After-Before) \nhead(chol, 12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 12 × 3\n   Before After DiffChol\n    <dbl> <dbl>    <dbl>\n 1    195   146      -49\n 2    145   155       10\n 3    205   178      -27\n 4    159   146      -13\n 5    244   208      -36\n 6    166   147      -19\n 7    250   202      -48\n 8    236   215      -21\n 9    192   184       -8\n10    224   208      -16\n11    238   206      -32\n12    197   169      -28\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nchol %>% \n  get_summary_stats(type = \"common\") %>% \n  gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"yqfheibtzd\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yqfheibtzd table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yqfheibtzd thead, #yqfheibtzd tbody, #yqfheibtzd tfoot, #yqfheibtzd tr, #yqfheibtzd td, #yqfheibtzd th {\n  border-style: none;\n}\n\n#yqfheibtzd p {\n  margin: 0;\n  padding: 0;\n}\n\n#yqfheibtzd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yqfheibtzd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yqfheibtzd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yqfheibtzd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yqfheibtzd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yqfheibtzd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yqfheibtzd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yqfheibtzd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yqfheibtzd .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yqfheibtzd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yqfheibtzd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yqfheibtzd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yqfheibtzd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yqfheibtzd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yqfheibtzd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfheibtzd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yqfheibtzd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yqfheibtzd .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yqfheibtzd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfheibtzd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yqfheibtzd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfheibtzd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yqfheibtzd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfheibtzd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yqfheibtzd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yqfheibtzd .gt_left {\n  text-align: left;\n}\n\n#yqfheibtzd .gt_center {\n  text-align: center;\n}\n\n#yqfheibtzd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yqfheibtzd .gt_font_normal {\n  font-weight: normal;\n}\n\n#yqfheibtzd .gt_font_bold {\n  font-weight: bold;\n}\n\n#yqfheibtzd .gt_font_italic {\n  font-style: italic;\n}\n\n#yqfheibtzd .gt_super {\n  font-size: 65%;\n}\n\n#yqfheibtzd .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yqfheibtzd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yqfheibtzd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yqfheibtzd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yqfheibtzd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yqfheibtzd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yqfheibtzd .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min\">min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"max\">max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"iqr\">iqr</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\">se</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci\">ci</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_center\">Before</td>\n<td headers=\"n\" class=\"gt_row gt_right\">24</td>\n<td headers=\"min\" class=\"gt_row gt_right\">137</td>\n<td headers=\"max\" class=\"gt_row gt_right\">250</td>\n<td headers=\"median\" class=\"gt_row gt_right\">179</td>\n<td headers=\"iqr\" class=\"gt_row gt_right\">44.50</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">187.792</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">33.160</td>\n<td headers=\"se\" class=\"gt_row gt_right\">6.769</td>\n<td headers=\"ci\" class=\"gt_row gt_right\">14.002</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_center\">After</td>\n<td headers=\"n\" class=\"gt_row gt_right\">24</td>\n<td headers=\"min\" class=\"gt_row gt_right\">125</td>\n<td headers=\"max\" class=\"gt_row gt_right\">215</td>\n<td headers=\"median\" class=\"gt_row gt_right\">165</td>\n<td headers=\"iqr\" class=\"gt_row gt_right\">38.00</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">168.250</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">26.796</td>\n<td headers=\"se\" class=\"gt_row gt_right\">5.470</td>\n<td headers=\"ci\" class=\"gt_row gt_right\">11.315</td></tr>\n    <tr><td headers=\"variable\" class=\"gt_row gt_center\">DiffChol</td>\n<td headers=\"n\" class=\"gt_row gt_right\">24</td>\n<td headers=\"min\" class=\"gt_row gt_right\">-49</td>\n<td headers=\"max\" class=\"gt_row gt_right\">13</td>\n<td headers=\"median\" class=\"gt_row gt_right\">-19</td>\n<td headers=\"iqr\" class=\"gt_row gt_right\">20.25</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">-19.542</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">16.806</td>\n<td headers=\"se\" class=\"gt_row gt_right\">3.430</td>\n<td headers=\"ci\" class=\"gt_row gt_right\">7.096</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n### EDA: Differences in cholesterol levels: After - Before diet\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(chol, aes(x=Before)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-21-1.png){width=480}\n:::\n\n```{.r .cell-code}\nggplot(chol, aes(x=After)) +\n  geom_density()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-21-2.png){width=480}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(chol, aes(x=DiffChol)) + \n  geom_density()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-22-1.png){width=480}\n:::\n\n```{.r .cell-code}\nggplot(chol, aes(x=DiffChol)) + \n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-22-2.png){width=480}\n:::\n:::\n\n\n\n# Steps in a Hypothesis Test\n\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[null]{style=\"color:darkorange\"}__ ( $H_0$ ) and __[alternative]{style=\"color:darkorange\"}__ ( $H_A$ ) __[hypotheses]{style=\"color:darkorange\"}__\n    1. In symbols\n    1. In words\n    1. Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n    1. Do we reject or fail to reject $H_0$?\n    1. Write a conclusion in the context of the problem\n\n\n## Step 2: Null & Alternative Hypotheses \n\n* __Question__: Is there evidence to support that cholesterol levels changed after the vegetarian diet?\n\n\nNull and alternative hypotheses in __words__\nInclude as much context as possible\n\n<br>\n\n* $H_0$: The population mean difference in cholesterol levels after a vegetarian diet is  \n\n* $H_A$: The population mean difference in cholesterol levels after a vegetarian diet is\n\n\n\nNull and alternative hypotheses in __symbols__\n\n$$~~~~H_0: \\delta =  \\\\\nH_A: \\delta   \\\\$$\n\n\n## Step 3: Test statistic \n\n\n::: {.cell}\n\n```{.r .cell-code}\nchol %>% select(DiffChol) %>% get_summary_stats(type = \"common\") %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"jajxyktkxb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jajxyktkxb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jajxyktkxb thead, #jajxyktkxb tbody, #jajxyktkxb tfoot, #jajxyktkxb tr, #jajxyktkxb td, #jajxyktkxb th {\n  border-style: none;\n}\n\n#jajxyktkxb p {\n  margin: 0;\n  padding: 0;\n}\n\n#jajxyktkxb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jajxyktkxb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jajxyktkxb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jajxyktkxb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jajxyktkxb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jajxyktkxb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jajxyktkxb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jajxyktkxb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jajxyktkxb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jajxyktkxb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jajxyktkxb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jajxyktkxb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jajxyktkxb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jajxyktkxb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jajxyktkxb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jajxyktkxb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jajxyktkxb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jajxyktkxb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jajxyktkxb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jajxyktkxb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jajxyktkxb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jajxyktkxb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jajxyktkxb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jajxyktkxb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jajxyktkxb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jajxyktkxb .gt_left {\n  text-align: left;\n}\n\n#jajxyktkxb .gt_center {\n  text-align: center;\n}\n\n#jajxyktkxb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jajxyktkxb .gt_font_normal {\n  font-weight: normal;\n}\n\n#jajxyktkxb .gt_font_bold {\n  font-weight: bold;\n}\n\n#jajxyktkxb .gt_font_italic {\n  font-style: italic;\n}\n\n#jajxyktkxb .gt_super {\n  font-size: 65%;\n}\n\n#jajxyktkxb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jajxyktkxb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jajxyktkxb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jajxyktkxb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jajxyktkxb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jajxyktkxb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jajxyktkxb .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min\">min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"max\">max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"iqr\">iqr</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\">se</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci\">ci</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_center\">DiffChol</td>\n<td headers=\"n\" class=\"gt_row gt_right\">24</td>\n<td headers=\"min\" class=\"gt_row gt_right\">-49</td>\n<td headers=\"max\" class=\"gt_row gt_right\">13</td>\n<td headers=\"median\" class=\"gt_row gt_right\">-19</td>\n<td headers=\"iqr\" class=\"gt_row gt_right\">20.25</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">-19.542</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">16.806</td>\n<td headers=\"se\" class=\"gt_row gt_right\">3.43</td>\n<td headers=\"ci\" class=\"gt_row gt_right\">7.096</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n$$\nt_{\\bar{x}_d} = \\frac{\\bar{x}_d - \\delta_0}{\\frac{s_d}{\\sqrt{n}}}\n$$\n\n* Based on the value of the test statistic, do you think we are going to reject or fail to reject $H_0$?\n* What probability distribution does the test statistic have?\n* Are the __[assumptions]{style=\"color:darkorange\"}__ for a paired t-test satisfied so that we can use the probability distribution to calculate the $p$-value??\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 24\nalpha <- 0.05\nmu <- 0\n(p_area <- 1-alpha/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.975\n```\n:::\n\n```{.r .cell-code}\n(xbar <- mean(chol$DiffChol))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -19.54167\n```\n:::\n\n```{.r .cell-code}\n(sd <- sd(chol$DiffChol))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.80574\n```\n:::\n\n```{.r .cell-code}\n(se <- sd/sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.430458\n```\n:::\n\n```{.r .cell-code}\n(tstat <- (xbar - mu)/se)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -5.696519\n```\n:::\n:::\n\n\n\n\n## Step 4: p-value\n\nThe __[p-value]{style=\"color:darkorange\"}__ is the __probability__ of obtaining a test statistic _just as extreme or more extreme_ than the observed test statistic assuming the null hypothesis $H_0$ is true. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# specify upper and lower bounds of shaded region below\nmu <- 0\nstd <- se\n\n# The following figure is only an approximation of the \n# sampling distribution since I used a normal instead\n# of t-distribution to make it.\n\nggplot(data.frame(x = c(mu-6*std, mu+6*std)), aes(x = x)) + \n  stat_function(fun = dnorm, \n                args = list(mean = mu, sd = std)) + \n  scale_y_continuous(breaks = NULL) +\n  scale_x_continuous(breaks=c(mu, mu - 3.4*(1:6), mu + 3.4*(1:6))) +\n  theme(axis.text.x=element_text(angle = -30, hjust = 0)) +\n  labs(y = \"\", \n       x = \"sample mean difference\",\n       title = \"Sampling distribution of mean difference\") +\n  geom_vline(xintercept = c(-xbar, xbar), \n             color = \"red\")\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-25-1.png){width=480}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = data.frame(x = c(-6, 6)), aes(x)) + \n  stat_function(fun = dt, args = list(df = n-1)) + \n  ylab(\"\") + \n  xlab(\"t-dist with df = 23\") +\n  scale_y_continuous(breaks = NULL) + \n  scale_x_continuous(breaks=c(mu, mu - (1:5), mu + (1:5))) +\n  geom_vline(xintercept = c(-tstat,tstat), \n             color = \"red\")\n```\n\n::: {.cell-output-display}\n![](Day10_bsta511_code_files/figure-html/unnamed-chunk-26-1.png){width=480}\n:::\n:::\n\n\n\nCalculate the _p_-value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pv <- 2*(pt(tstat, df=n-1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 8.434775e-06\n```\n:::\n:::\n\n\n\n## Step 5: Conclusion to hypothesis test\n\n$$~~~~H_0: \\delta = 0 \\\\\nH_A: \\delta \\neq 0  \\\\$$\n\n* Recall the $p$-value = $8.434775 \\cdot 10 ^{-6}$\n* Use $\\alpha$ = 0.05.\n* Do we reject or fail to reject $H_0$?\n\n__Conclusion statement__:\n\n* Stats class conclusion\n    * There is sufficient evidence that the (population) mean difference in cholesterol levels after a vegetarian diet is different from 0 mg/dL ( $p$-value < 0.001).\n\n* More realistic manuscript conclusion: \n    * After a vegetarian diet, cholesterol levels decreased by on average 19.54 mg/dL (SE = 3.43 mg/dL, 2-sided $p$-value < 0.001).\n\n\n\n# 95% CI for the mean difference in cholesterol levels\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchol %>% select(DiffChol) %>% get_summary_stats(type = \"common\") %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"fkcopadtpi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fkcopadtpi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fkcopadtpi thead, #fkcopadtpi tbody, #fkcopadtpi tfoot, #fkcopadtpi tr, #fkcopadtpi td, #fkcopadtpi th {\n  border-style: none;\n}\n\n#fkcopadtpi p {\n  margin: 0;\n  padding: 0;\n}\n\n#fkcopadtpi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fkcopadtpi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fkcopadtpi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fkcopadtpi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fkcopadtpi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fkcopadtpi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fkcopadtpi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fkcopadtpi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fkcopadtpi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fkcopadtpi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fkcopadtpi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fkcopadtpi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fkcopadtpi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fkcopadtpi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fkcopadtpi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkcopadtpi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fkcopadtpi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fkcopadtpi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fkcopadtpi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkcopadtpi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fkcopadtpi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkcopadtpi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fkcopadtpi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkcopadtpi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fkcopadtpi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkcopadtpi .gt_left {\n  text-align: left;\n}\n\n#fkcopadtpi .gt_center {\n  text-align: center;\n}\n\n#fkcopadtpi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fkcopadtpi .gt_font_normal {\n  font-weight: normal;\n}\n\n#fkcopadtpi .gt_font_bold {\n  font-weight: bold;\n}\n\n#fkcopadtpi .gt_font_italic {\n  font-style: italic;\n}\n\n#fkcopadtpi .gt_super {\n  font-size: 65%;\n}\n\n#fkcopadtpi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fkcopadtpi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fkcopadtpi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fkcopadtpi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fkcopadtpi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fkcopadtpi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fkcopadtpi .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"min\">min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"max\">max</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"median\">median</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"iqr\">iqr</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"se\">se</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ci\">ci</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variable\" class=\"gt_row gt_center\">DiffChol</td>\n<td headers=\"n\" class=\"gt_row gt_right\">24</td>\n<td headers=\"min\" class=\"gt_row gt_right\">-49</td>\n<td headers=\"max\" class=\"gt_row gt_right\">13</td>\n<td headers=\"median\" class=\"gt_row gt_right\">-19</td>\n<td headers=\"iqr\" class=\"gt_row gt_right\">20.25</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">-19.542</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">16.806</td>\n<td headers=\"se\" class=\"gt_row gt_right\">3.43</td>\n<td headers=\"ci\" class=\"gt_row gt_right\">7.096</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nCI for $\\mu_d$ (or $\\delta$):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 24\nalpha <- 0.05\n(p_area <- 1-alpha/2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.975\n```\n:::\n\n```{.r .cell-code}\n(xbar <- mean(chol$DiffChol))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -19.54167\n```\n:::\n\n```{.r .cell-code}\n(sd <- sd(chol$DiffChol))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 16.80574\n```\n:::\n\n```{.r .cell-code}\n(tstar <- qt(p_area, df=n-1))  # df = n-1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.068658\n```\n:::\n\n```{.r .cell-code}\n(se <- sd/sqrt(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.430458\n```\n:::\n\n```{.r .cell-code}\n(moe <- tstar * se) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 7.096443\n```\n:::\n\n```{.r .cell-code}\n(LB <- xbar - moe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -26.63811\n```\n:::\n\n```{.r .cell-code}\n(UB <- xbar + moe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -12.44522\n```\n:::\n:::\n\n\n\n$$\\bar{x}_d \\pm t^*\\cdot\\frac{s_d}{\\sqrt{n}}\\\\\n-19.542 \\pm 2.069\\cdot\\frac{16.806}{\\sqrt{24}}\\\\\n-19.542 \\pm 2.069\\cdot 3.43\\\\\n-19.542 \\pm 7.096\\\\\n(-26.638, -12.445)$$\n\n\nConclusion:  \nWe are 95% that the (population) mean difference in cholesterol levels after a vegetarian diet is between -26.638 mg/dL and -12.445 mg/dL.\n\n* _Based on the CI, is there evidence the diet made a difference in cholesterol levels? Why or why not?_\n\n# R\n\n## R option 1: Run a 1-sample `t.test` using the paired differences\n\n$H_A: \\delta \\neq 0$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x = chol$DiffChol, mu = 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  chol$DiffChol\nt = -5.6965, df = 23, p-value = 8.435e-06\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -26.63811 -12.44522\nsample estimates:\nmean of x \n-19.54167 \n```\n:::\n:::\n\n\n\n\n## R option 2: Run a 2-sample `t.test` with `paired = TRUE` option\n\n$H_A: \\delta \\neq 0$\n\n* For a 2-sample t-test we specify both `x=` and `y=`\n* Note: `mu = 0` is the default value and doesn't need to be specified\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x = chol$Before, y = chol$After, mu = 0, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  chol$Before and chol$After\nt = 5.6965, df = 23, p-value = 8.435e-06\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 12.44522 26.63811\nsample estimates:\nmean difference \n       19.54167 \n```\n:::\n:::\n\n\n\n\n## R option 3: Run a 2-sample `t.test` with `paired = TRUE` option, but using the long data and a \"formula\"\n\n\n* Use the usual `t.test`\n* What's different is that \n    * instead of specifying the variables with `x=` and `y=`, \n    * we give a __formula__ of the form `y ~ x` using _just the variable names_,\n    * and then specify the name of the dataset using `data =`\n* This method is often used in practice, and more similar to the coding style of running a regression model (BSTA 512 & 513)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# using long data with columns Cholesterol & Time:\nt.test(Cholesterol ~ Time, \n       paired = TRUE, \n       data = chol_long)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  Cholesterol by Time\nt = 5.6965, df = 23, p-value = 8.435e-06\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 12.44522 26.63811\nsample estimates:\nmean difference \n       19.54167 \n```\n:::\n:::\n\n\n\n\n## `tidy` the `t.test` output & compare the 3 options\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# option 1\nt.test(x = chol$DiffChol, mu = 0) %>% tidy() %>% gt() # tidy from broom package\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ybwppxvyco\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ybwppxvyco table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ybwppxvyco thead, #ybwppxvyco tbody, #ybwppxvyco tfoot, #ybwppxvyco tr, #ybwppxvyco td, #ybwppxvyco th {\n  border-style: none;\n}\n\n#ybwppxvyco p {\n  margin: 0;\n  padding: 0;\n}\n\n#ybwppxvyco .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ybwppxvyco .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ybwppxvyco .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ybwppxvyco .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ybwppxvyco .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ybwppxvyco .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ybwppxvyco .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ybwppxvyco .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ybwppxvyco .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ybwppxvyco .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ybwppxvyco .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ybwppxvyco .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ybwppxvyco .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ybwppxvyco .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ybwppxvyco .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybwppxvyco .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ybwppxvyco .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ybwppxvyco .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ybwppxvyco .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybwppxvyco .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ybwppxvyco .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybwppxvyco .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ybwppxvyco .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybwppxvyco .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ybwppxvyco .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ybwppxvyco .gt_left {\n  text-align: left;\n}\n\n#ybwppxvyco .gt_center {\n  text-align: center;\n}\n\n#ybwppxvyco .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ybwppxvyco .gt_font_normal {\n  font-weight: normal;\n}\n\n#ybwppxvyco .gt_font_bold {\n  font-weight: bold;\n}\n\n#ybwppxvyco .gt_font_italic {\n  font-style: italic;\n}\n\n#ybwppxvyco .gt_super {\n  font-size: 65%;\n}\n\n#ybwppxvyco .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ybwppxvyco .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ybwppxvyco .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ybwppxvyco .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ybwppxvyco .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ybwppxvyco .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ybwppxvyco .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">-19.54167</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-5.696519</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">8.434775e-06</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">23</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-26.63811</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">-12.44522</td>\n<td headers=\"method\" class=\"gt_row gt_left\">One Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\n# option 2\nt.test(x = chol$Before, y = chol$After, mu = 0, paired = TRUE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"zcwalwlqbq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zcwalwlqbq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zcwalwlqbq thead, #zcwalwlqbq tbody, #zcwalwlqbq tfoot, #zcwalwlqbq tr, #zcwalwlqbq td, #zcwalwlqbq th {\n  border-style: none;\n}\n\n#zcwalwlqbq p {\n  margin: 0;\n  padding: 0;\n}\n\n#zcwalwlqbq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zcwalwlqbq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zcwalwlqbq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zcwalwlqbq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zcwalwlqbq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zcwalwlqbq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zcwalwlqbq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zcwalwlqbq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zcwalwlqbq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zcwalwlqbq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zcwalwlqbq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zcwalwlqbq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zcwalwlqbq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zcwalwlqbq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zcwalwlqbq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zcwalwlqbq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zcwalwlqbq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zcwalwlqbq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zcwalwlqbq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zcwalwlqbq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zcwalwlqbq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zcwalwlqbq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zcwalwlqbq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zcwalwlqbq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zcwalwlqbq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zcwalwlqbq .gt_left {\n  text-align: left;\n}\n\n#zcwalwlqbq .gt_center {\n  text-align: center;\n}\n\n#zcwalwlqbq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zcwalwlqbq .gt_font_normal {\n  font-weight: normal;\n}\n\n#zcwalwlqbq .gt_font_bold {\n  font-weight: bold;\n}\n\n#zcwalwlqbq .gt_font_italic {\n  font-style: italic;\n}\n\n#zcwalwlqbq .gt_super {\n  font-size: 65%;\n}\n\n#zcwalwlqbq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zcwalwlqbq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zcwalwlqbq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zcwalwlqbq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zcwalwlqbq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zcwalwlqbq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zcwalwlqbq .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">19.54167</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.696519</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">8.434775e-06</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">23</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">12.44522</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">26.63811</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Paired t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\n# option 3\nt.test(Cholesterol ~ Time, paired = TRUE, data = chol_long) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"endsoyqvje\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#endsoyqvje table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#endsoyqvje thead, #endsoyqvje tbody, #endsoyqvje tfoot, #endsoyqvje tr, #endsoyqvje td, #endsoyqvje th {\n  border-style: none;\n}\n\n#endsoyqvje p {\n  margin: 0;\n  padding: 0;\n}\n\n#endsoyqvje .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#endsoyqvje .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#endsoyqvje .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#endsoyqvje .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#endsoyqvje .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#endsoyqvje .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#endsoyqvje .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#endsoyqvje .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#endsoyqvje .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#endsoyqvje .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#endsoyqvje .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#endsoyqvje .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#endsoyqvje .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#endsoyqvje .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#endsoyqvje .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#endsoyqvje .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#endsoyqvje .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#endsoyqvje .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#endsoyqvje .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#endsoyqvje .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#endsoyqvje .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#endsoyqvje .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#endsoyqvje .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#endsoyqvje .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#endsoyqvje .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#endsoyqvje .gt_left {\n  text-align: left;\n}\n\n#endsoyqvje .gt_center {\n  text-align: center;\n}\n\n#endsoyqvje .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#endsoyqvje .gt_font_normal {\n  font-weight: normal;\n}\n\n#endsoyqvje .gt_font_bold {\n  font-weight: bold;\n}\n\n#endsoyqvje .gt_font_italic {\n  font-style: italic;\n}\n\n#endsoyqvje .gt_super {\n  font-size: 65%;\n}\n\n#endsoyqvje .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#endsoyqvje .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#endsoyqvje .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#endsoyqvje .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#endsoyqvje .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#endsoyqvje .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#endsoyqvje .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">19.54167</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">5.696519</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">8.434775e-06</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">23</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">12.44522</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">26.63811</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Paired t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n# What if we wanted to test whether the diet _decreased_ cholesterol levels?\n\n\nHow are the steps different?\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[hypotheses]{style=\"color:darkorange\"}__ $H_0$ and $H_A$\n    * Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n\n\n## R: What if we wanted to test whether the diet _decreased_ cholesterol levels?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# alternative = c(\"two.sided\", \"less\", \"greater\")\nt.test(x = chol$DiffChol, mu = 0, alternative = \"less\") %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"fsqdchvmzj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fsqdchvmzj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fsqdchvmzj thead, #fsqdchvmzj tbody, #fsqdchvmzj tfoot, #fsqdchvmzj tr, #fsqdchvmzj td, #fsqdchvmzj th {\n  border-style: none;\n}\n\n#fsqdchvmzj p {\n  margin: 0;\n  padding: 0;\n}\n\n#fsqdchvmzj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fsqdchvmzj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fsqdchvmzj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fsqdchvmzj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fsqdchvmzj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fsqdchvmzj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fsqdchvmzj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fsqdchvmzj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fsqdchvmzj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fsqdchvmzj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fsqdchvmzj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fsqdchvmzj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fsqdchvmzj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fsqdchvmzj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fsqdchvmzj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsqdchvmzj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fsqdchvmzj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fsqdchvmzj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fsqdchvmzj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsqdchvmzj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fsqdchvmzj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsqdchvmzj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fsqdchvmzj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsqdchvmzj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fsqdchvmzj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fsqdchvmzj .gt_left {\n  text-align: left;\n}\n\n#fsqdchvmzj .gt_center {\n  text-align: center;\n}\n\n#fsqdchvmzj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fsqdchvmzj .gt_font_normal {\n  font-weight: normal;\n}\n\n#fsqdchvmzj .gt_font_bold {\n  font-weight: bold;\n}\n\n#fsqdchvmzj .gt_font_italic {\n  font-style: italic;\n}\n\n#fsqdchvmzj .gt_super {\n  font-size: 65%;\n}\n\n#fsqdchvmzj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fsqdchvmzj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fsqdchvmzj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fsqdchvmzj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fsqdchvmzj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fsqdchvmzj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fsqdchvmzj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">-19.54167</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">-5.696519</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">4.217387e-06</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">23</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-Inf</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">-13.6623</td>\n<td headers=\"method\" class=\"gt_row gt_left\">One Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">less</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n# One-sided confidence intervals\n\n\nFormula for a __2-sided__ (1- $\\alpha$ )% __CI__:\n\n$$\\bar{x} \\pm t^*\\cdot\\frac{s}{\\sqrt{n}}$$\n* $t^*$ = `qt(1-alpha/2, df = n-1)`\n* $\\alpha$ is split over both tails of the distribution\n\n\nA __one-sided__ (1- $\\alpha$ )% __CI__ has all (1- $\\alpha$ )% on just the left or the right tail of the distribution:\n\n$$(\\bar{x} - t^*\\cdot\\frac{s}{\\sqrt{n}},~\\infty) \\\\\n(\\infty,~\\bar{x} + t^*\\cdot\\frac{s}{\\sqrt{n}})$$\n\n* $t^*$ = `qt(1-alpha, df = n-1)` for a 1-sided lower (1- $\\alpha$ )% CI\n* $t^*$ = `qt(alpha, df = n-1)` for a 1-sided upper (1- $\\alpha$ )% CI\n* A 1-sided CI gives estimates for a lower or upper bound of the population mean.\n* See Section 4.2.3 of the V&H book for more\n\n\n# Confidence Intervals vs. Hypothesis Testing\n\n* See also V&H Section 4.3.3\n\n\n\n# What's next? \n\n\nCI's and hypothesis tests for different scenarios:\n\n$$point~estimate \\pm z^*(or~t^*)\\cdot SE,~~~~~~~~test~stat = \\frac{point~estimate-null~value}{SE}$$\n\nDay | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE\n--------|--------|--------|--------|--------|--------|--------\n11-12 | 5.1 | Pop mean | $\\mu$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$\n13 | 5.2 | Diff in paired <br> pop means | $\\mu_d$ or $\\delta$ | Diff in paired <br> sample means | $\\bar{x}_{d}$  | $\\frac{s_d}{\\sqrt{n}}$\n14 | 5.3 | Diff in pop <br> means | $\\mu_1-\\mu_2$ | Diff in sample <br> means | $\\bar{x}_1 - \\bar{x}_2$  |\n | 8.1 | Pop proportion | $p$ | Sample prop | $\\widehat{p}$  |\n | 8.2 | Diff in pop <br> proportions | $p_1-p_2$ | Diff in sample <br> proportions | $\\widehat{p}_1-\\widehat{p}_2$ |\n\n",
    "supporting": [
      "Day10_bsta511_code_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}