{
  "hash": "82562f340e2b3fd7801dd9591181ad35",
  "result": {
    "markdown": "---\ntitle: \"Homework 2 Answers\"\nsubtitle: \"EPI 525\"\ndate-modified: \"today\"\nformat: \n  html: \n    link-external-newwindow: true\n    toc: true\n  pdf: default \neditor_options: \n  chunk_output_type: console\n---\n\n\n\nThese are the **some** numeric/short answers to the homework. Often, these answers are insufficient for your own work or solutions. I just wanted to give you a part of the answer to help guide you in the right direction.\n\n\n\n::: {.cell}\n\n:::\n\n\n\n# Book exercises {.unnumbered}\n\n## 2.6 Poverty and language {.unnumbered}  \n  \nThe American Community Survey is an ongoing survey that provides data every year to give communities the current information they need to plan investments and services. The 2010 American Community Survey estimates that 14.6% of Americans live below the poverty line, 20.7% speak a language other than English (foreign language) at home, and 4.2% fall into both categories.\n\n### a   {.unnumbered}\n\nNot disjoint\n\n### b     {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](HW_02_files/figure-pdf/unnamed-chunk-3-1.pdf)\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n(polygon[GRID.polygon.1], polygon[GRID.polygon.2], polygon[GRID.polygon.3], polygon[GRID.polygon.4], text[GRID.text.5], text[GRID.text.6], text[GRID.text.7], text[GRID.text.8], text[GRID.text.9]) \n```\n:::\n:::\n\n\n\n\n### c     {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n10.4% \n\n### d    {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n31.1%\n\n### e     {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n68.9% \n\n### f     {.unnumbered}\n\nNot independent\n\n## 2.8 School absences {.unnumbered}\n\n### a   {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n0.32\n\n### b     {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n0.57\n\n### c     {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n0.68\n\n### d     {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n0.1024\n\n### e     {.unnumbered}\n\n\n\n::: {.cell}\n\n:::\n\n\n\n0.4624\n\n## 2.10 Health coverage, frequencies {.unnumbered}  \n\n*The Behavioral Risk Factor Surveillance System (BRFSS) is an annual telephone survey designed to identify risk factors in the adult population and report emerging health trends.*\n\n*The following table summarizes two variables for the respondents: health status and health coverage, which describes whether each respondent had health insurance.*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#table. not required\n(covg.tab <- data.frame(\n  health_status = c(\"No\",\"Yes\",\"total\"),\n  Excellent = c(459,4198,4657),\n  Very_good = c(727,6245,6972),\n  Good = c(854,4821,5675),\n  Fair = c(385,1634,2019),\n  Poor = c(99,578,677),\n  Total = c(2524,17476,20000)\n)) %>% gt()\n```\n\n::: {.cell-output-display}\n\\begingroup\n\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{longtable}{lrrrrrr}\n\\toprule\nhealth\\_status & Excellent & Very\\_good & Good & Fair & Poor & Total \\\\ \n\\midrule\\addlinespace[2.5pt]\nNo & 459 & 727 & 854 & 385 & 99 & 2524 \\\\ \nYes & 4198 & 6245 & 4821 & 1634 & 578 & 17476 \\\\ \ntotal & 4657 & 6972 & 5675 & 2019 & 677 & 20000 \\\\ \n\\bottomrule\n\\end{longtable}\n\\endgroup\n:::\n:::\n\n\n\n\n### a     {.unnumbered}\n\nIf one individual is drawn at random, what is the probability that the respondent has excellent health and doesn’t have health coverage?  \n\n::: blue\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(eh.no_covg <- (459/20000))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02295\n```\n:::\n:::\n\n\n\nThe probability the respondent drawn at random has excellent health and doesn't have health coverage is 0.02295.  \n:::\n\n### b     {.unnumbered}\n\nIf one individual is drawn at random, what is the probability that the respondent has excellent health or doesn’t have health coverage?    \n\n::: blue\nLet A = excellent health and B = doesn't have health coverage. \n$$P(A ~or~ B) = P(A)+P(B)-P(A ~and~ B)$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 4657/20000; b <- 2524/20000; c <- 459/20000\n(eh_or_no.hc <- a+b-c)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3361\n```\n:::\n:::\n\n\n\nThe probability that the respondent drawn at random has excellent health OR doesn't have health coverage is 0.3361.   \n:::\n\n## 2.14 Health coverage, relative frequencies {.unnumbered}  \n\n*The Behavioral Risk Factor Surveillance System (BRFSS) is an annual telephone survey designed to identify risk factors in the adult population and report emerging health trends. The following table displays the distribution of health status of respondents to this survey (excellent, very good, good, fair, poor) conditional on whether or not they have health insurance.*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(covg.tab <- data.frame(\n  health_status = c(\"No\",\"Yes\",\"total\"),\n  Excellent = c(0.0230, 0.2099,0.2329),\n  Very_good = c(0.0364, 0.3123,0.3486),\n  Good = c(0.0427,0.2410,0.2838),\n  Fair = c(0.0192,0.0817,0.1009),\n  Poor = c(0.0050,0.0289,0.0338),\n  Total = c(0.1262,0.8738,1.0000)\n)) %>% gt()\n```\n\n::: {.cell-output-display}\n\\begingroup\n\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{longtable}{lrrrrrr}\n\\toprule\nhealth\\_status & Excellent & Very\\_good & Good & Fair & Poor & Total \\\\ \n\\midrule\\addlinespace[2.5pt]\nNo & 0.0230 & 0.0364 & 0.0427 & 0.0192 & 0.0050 & 0.1262 \\\\ \nYes & 0.2099 & 0.3123 & 0.2410 & 0.0817 & 0.0289 & 0.8738 \\\\ \ntotal & 0.2329 & 0.3486 & 0.2838 & 0.1009 & 0.0338 & 1.0000 \\\\ \n\\bottomrule\n\\end{longtable}\n\\endgroup\n:::\n:::\n\n\n       \n### a  \n\nAre being in excellent health and having health coverage mutually exclusive?    \n::: blue\nNo. 0.2099 is the proportion of respondents that have health coverage and excellent health, which is not 0. \n:::\n\n### b     {.unnumbered}\n\nWhat is the probability that a randomly chosen individual has excellent health?    \n::: blue\nThe probability that a randomly chosen individual has excellent health is 0.2329. This value is shown in the table. \n:::\n\n### c    {.unnumbered}\n\nWhat is the probability that a randomly chosen individual has excellent health given that he has health coverage?    \n\n::: blue\n$$P(A | B) = \\frac{P(A ~and~ B)}{P(B)} $$\n\n\n::: {.cell}\n\n```{.r .cell-code}\neh <- 0.2329; hc <- 0.8738; eh_and_hc <- 0.2099\n(eh_give_hc <- eh_and_hc/hc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2402152\n```\n:::\n:::\n\n\n\nThe probability that a randomly chosen individual has excellent health given that he has health coverage is 0.2402152. \n:::\n\n### d    {.unnumbered}\n\nWhat is the probability that a randomly chosen individual has excellent health given that he doesn’t have health coverage?    \n\n::: blue\n\n\n::: {.cell}\n\n```{.r .cell-code}\nno_hc <- 0.1262; eh_and_no_hc <- 0.0230\n(eh_give_no_hc <- eh_and_no_hc/no_hc)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1822504\n```\n:::\n:::\n\n\n\nThe probability that a randomly chosen individual has excellent health given that he doesn’t have health coverage is 0.1822504. \n:::\n\n### e     {.unnumbered}\n\nDo having excellent health and having health coverage appear to be independent?    \n::: blue\nNo, because the probability that a person has excellent health varies between the two health coverage categories (24% vs 18%). That is, knowing something about someone’s health coverage provides useful information in predicting whether the person has excellent health, which means the variables are not independent.\n:::\n\n\n## 2.18 Predisposition for thrombosis {.unnumbered}  \n\n*A genetic test is used to determine if people have a predisposition for thrombosis, which is the formation of a blood clot inside a blood vessel that obstructs the flow of blood through the circulatory system. It is believed that 3% of people actually have this predisposition. The genetic test is 99% accurate if a person actually has the predisposition, meaning that the probability of a positive test result when a person actually has the predisposition is 0.99. The test is 98% accurate if a person does not have the predisposition.*  \n\n### a   {.unnumbered}\n\nWhat is the probability that a randomly selected person who tests positive for the predisposition by the test actually has the predisposition?    \n\n::: blue\nLet the events below be defined as follows:\n\n* $D$ = has disease (predisposition for thrombosis),  \n* $D^c$ = absence of disease (no predisposition for thrombosis), \n* $T^+$ = test positive for predisposition for thrombosis, and \n* $T^-$ = test negative for predisposition for thrombosis.   \n\nWe are given the probabilities below, and can calculate the probabilities of their complements:\n\n\n\\begin{align}\nP(D) &= 0.03, ~P(D^c) = 0.97 \\\\\nP(T^+|D) &= 0.99, ~P(T^-|D) = 1-P(T^+|D) = 0.01 \\\\ \nP(T^-|D^c) &= 0.98, ~P(T^+|D^c) = 1-P(T^+|D) = 0.02\n\\end{align}\n\nThen using Bayes' Rule, we have\n\n\\begin{align}\nP(D | T^+) = \\frac{P(D ~and~ T^+)}{P(T^+)} \n&=\\frac{P(T^+|D)P(D)}{P(T^+|D)P(D) + P(T^+|D^c)P(D^c)}\\\\\n&= \\frac{(0.99)(0.03)}{(0.99)(0.03) + (0.02)(0.97)}\n\\end{align}  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#set each variable: \ndis <- 0.03 #prob of having disease (predisposition)\ndis.c <- (1-dis) #prob of not having predisposition\npos.giv.d <- 0.99 #prob of positive test given disease\nneg.giv.dc <- 0.98 #prob of negative test given not having disease\n(pos.giv.dc <- 1-neg.giv.dc) #prob of positive test given not having disease\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02\n```\n:::\n\n```{.r .cell-code}\n(neg.giv.d <- 1-pos.giv.d)  #prob of negative test given having disease\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#find the probability of having the disease given a positive test\n(dis.giv.pos <- (pos.giv.d*dis)/((dis*pos.giv.d)+(dis.c*pos.giv.dc)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.604888\n```\n:::\n:::\n\n\n\nThe probability that a randomly selected person who tests positive for thrombosis predisposition by the test actually has a predisposition for thrombosis is 0.605.   \n:::\n\n### b     {.unnumbered}\n\nWhat is the probability that a randomly selected person who tests negative for the predisposition by the test actually does not have the predisposition?    \n\n::: blue\nUsing Bayes' Rule, we have  \n\n\\begin{align}\nP(D^c | T^-) = \\frac{P(D^c ~and~ T^-)}{P(T^-)} \n&=\\frac{P(T^-|D^c)P(D^c)}{P(T^-|D)P(D)+P(T^-|D^c)P(D^c)}\\\\\n&= \\frac{(0.98)(0.97)}{(0.01)(0.03)+(0.98)(0.97)}\n\\end{align}  \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#find the probability of not having the disease given testing negative for the predisposition \n(nodis.giv.neg <- (neg.giv.dc*dis.c) / (dis*neg.giv.d + dis.c*neg.giv.dc))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9996845\n```\n:::\n:::\n\n\n\nThe probability that a randomly selected person who tests negative for thrombosis predisposition by the test actually does not have thrombosis predisposition is 0.9997. \n:::\n\n## 2.24 Breast cancer and age {.unnumbered}  \n\n*The strongest risk factor for breast cancer is age; as a woman gets older, her risk of developing breast cancer increases. The following table shows the average percentage of American women in each age group who develop breast cancer, according to statistics from the National Cancer Institute. For example, approximately 3.56% of women in their 60’s get breast cancer.  A mammogram typically identifies a breast cancer about 85% of the time, and is correct 95% of the time when a woman does not have breast cancer.*\n\n### a  {.unnumbered}\n\nCalculate the PPV for each age group. Describe any trend(s) you see in the PPV values as prevalence changes. Explain the reason for the trend(s) in language that someone who has not taken a statistics course would understand      \n\n::: blue\nLet the events below be defined as follows:\n\n* $D$ = has breast cancer, \n* $D^c$ = absence of breast cancer, \n* $T^+$ = test positive for breast cancer, and\n* $T^-$ = test negative for breast cancer.   \n\nLet P(D30) = prevalence of breast cancer at ages 30-40, P(D40) at ages 40-50, and so on.   \n\nWe are given the probabilities below, and can calculate the probabilities of their complements:\n\n\n\\begin{align}\nsensitivity: ~P(T^+|D) &= 0.85,~P(T^-|D) = 1-P(T^+|D) = 0.15\\\\ \nspecificity: ~P(T^-|D^c) &= 0.95,~P(T^+|D^c) = 1-P(T^+|D) = 0.05\n\\end{align}  \n\nThen using Bayes' Rule, we have\n\n$$PPV = P(D | T^+) = \\frac{P(D ~and~ T^+)}{P(T^+)} =\n\\frac{P(T^+|D)P(D)}{P(T^+|D)P(D) + P(T^+|D^c)P(D^c)}$$\n\nDefine variables in R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#define variables\nd30 <- 0.0044 #30-40\nd40 <- 0.0147 #40-50\nd50 <- 0.0238 #50-60\nd60 <- 0.0356 #60-70\nd70 <- 0.0382 #70-80\npos.g.d <- 0.85 #prob of positive test given disease\nneg.g.dc <- 0.95 #prob of negative test given not having disease\n(pos.g.dc <- 1-neg.g.dc) #prob of positive test given not having disease.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n(neg.g.d <- 1-pos.g.d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.15\n```\n:::\n:::\n\n\n\nPPV calculations in R for different age groups:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Below we take advantage of R's capability of doing vector-wise calculations\n\n# Create a vector of the prevalences\nprevalence <- c(d30, d40, d50, d60, d70)\n\n# Compute the PPV's using the vector of prevalences\n(PPV <- round((pos.g.d*prevalence) / (prevalence*pos.g.d + (1-prevalence)*pos.g.dc), digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.070 0.202 0.293 0.386 0.403\n```\n:::\n:::\n\n\n  \nThe resulting PPV's are the following: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_group <- c(\"30 - 40\", \"40 - 50\", \"50 - 60\", \"60 - 70\", \"70 - 80\")\n\ndata.frame(age_group, prevalence, PPV) %>% \n  gt()\n```\n\n::: {.cell-output-display}\n\\begingroup\n\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{longtable}{rrr}\n\\toprule\nage\\_group & prevalence & PPV \\\\ \n\\midrule\\addlinespace[2.5pt]\n30 - 40 & 0.0044 & 0.070 \\\\ \n40 - 50 & 0.0147 & 0.202 \\\\ \n50 - 60 & 0.0238 & 0.293 \\\\ \n60 - 70 & 0.0356 & 0.386 \\\\ \n70 - 80 & 0.0382 & 0.403 \\\\ \n\\bottomrule\n\\end{longtable}\n\\endgroup\n:::\n:::\n\n\n  \nFrom the table we see that as the prevalence of breast cancer increases in the older age groups, the positive predictive value (PPV) also increases. Thus, if more women in a population have breast cancer, the probability that a positive test correctly identifies breast cancer increases. \n\nMathematically this can be explained by looking at the Bayes' Rule equation. As the prevalence increases, the term (prev x sensitivity) will increase in both the numerator and denominator. However, (1-prev) will decrease in the denominator. Therefore, overall, as long as the sensitivity and specificity are held constant, as the prevalence increases the number of true positives increases and the number of false positives decreases. PPV increases when the number of true positives increases. \n:::\n\n### b   {.unnumbered}\n\nSuppose that two new mammogram imaging technologies have been developed which can improve the PPV associated with mammograms; one improves sensitivity to 99% (but specificity remains at 95%), while the other improves specificity to 99% (while sensitivity remains at 85%). Which technology offers a higher increase in PPV? Explain why.   \n\n::: blue\nThe technology that raises the specificity to 99% offers a higher increase. Since prevalence of the disease only ranges between less than 1% to at most 4%, the sensitivity is being weighted (multiplied by) a small amount ($P(T^+|D)P(D)$) and thus changes in the sensitivity do not change the overall PPV very much.  \n\nIn contrast, the term involving the specificity is being weighted (multiplied by) a lot when the prevalence is low, and thus changes in the specificity have a greater effect on the PPV. Furthermore, as the specificity increases, the likelihood of false positive goes down. Thus, with the relatively large decrease in the denominator, the PPV will increase more than compared to when there is a very small increase in both numerator and denominator (increase in sensitivity).\n\nIntuitively, since prevalence of the disease is very small, there will be very few people with a true positive result, and comparatively many more people with a false positive true. While increasing the sensitivity of the test will increase the number of people with a true positive result, the number cannot increase much since so few women have breast cancer to begin with. In contrast, there are many more women without breast cancer, and so even a small increase in the specificity can lead to a relatively larger change (decrease) in the number of false positives. This decrease in the denominator will increase in the PPV.\n\nCalculations of new PPV with new imagaing technologies:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# improves sensitivity to 99% (but specificity remains at 95%)\n\npos.g.d <- 0.99 #prob of positive test given disease\nneg.g.dc <- 0.95 #prob of negative test given not having disease\n(pos.g.dc <- 1-neg.g.dc) #prob of positive test given not having disease.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n\n```{.r .cell-code}\n(neg.g.d <- 1-pos.g.d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01\n```\n:::\n\n```{.r .cell-code}\n(PPV_newSens99 <- round((pos.g.d*prevalence) / (prevalence*pos.g.d + (1-prevalence)*pos.g.dc), digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.080 0.228 0.326 0.422 0.440\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# improves specificity to 99% (while sensitivity remains at 85%)\n\npos.g.d <- 0.85 #prob of positive test given disease\nneg.g.dc <- 0.99 #prob of negative test given not having disease\n(pos.g.dc <- 1-neg.g.dc) #prob of positive test given not having disease.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.01\n```\n:::\n\n```{.r .cell-code}\n(neg.g.d <- 1-pos.g.d)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.15\n```\n:::\n\n```{.r .cell-code}\n(PPV_newSpec99 <- round((pos.g.d*prevalence) / (prevalence*pos.g.d + (1-prevalence)*pos.g.dc), digits = 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.273 0.559 0.675 0.758 0.771\n```\n:::\n:::\n\n\n\nThe table below compares the results, where we see that indeed the PPV increased more with the higher specificity vs. the higher sensitivity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(age_group, prevalence, PPV, PPV_newSens99, PPV_newSpec99) %>% \n  gt()\n```\n\n::: {.cell-output-display}\n\\begingroup\n\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{longtable}{rrrrr}\n\\toprule\nage\\_group & prevalence & PPV & PPV\\_newSens99 & PPV\\_newSpec99 \\\\ \n\\midrule\\addlinespace[2.5pt]\n30 - 40 & 0.0044 & 0.070 & 0.080 & 0.273 \\\\ \n40 - 50 & 0.0147 & 0.202 & 0.228 & 0.559 \\\\ \n50 - 60 & 0.0238 & 0.293 & 0.326 & 0.675 \\\\ \n60 - 70 & 0.0356 & 0.386 & 0.422 & 0.758 \\\\ \n70 - 80 & 0.0382 & 0.403 & 0.440 & 0.771 \\\\ \n\\bottomrule\n\\end{longtable}\n\\endgroup\n:::\n:::\n\n\n\n:::\n\n# Non-book exercise\n\n*Suppose a patient has abdominal pain and their clinician suspects that they either have disease 1, disease 2, or no disease, where the probability of having abdominal pain if they have disease 1 is 0.80, the probability of having abdominal pain if they have disease 2 is 0.90, and the probability of having abdominal pain if they have no disease is 0.01. Based on the patient’s medical history, the probability of having disease 1 is 0.009, having disease 2 is 0.001, and having no disease is 0.99. What is the probability the patient has disease 2 given that they have abdominal pain?*\n\n::: blue\nLet A = event of having abdominal pain, $D_1$ = event has disease 1, $D_2$ = event has disease 2, and $D_0$ = event has no disease. \nThe sample space is $S = \\{D_1,D_2,D_0\\}$.   \n\n\\begin{align}\nP(A|D_1) &= 0.80~ ~~~~~ ~P(D_1) = 0.009\\\\\nP(A|D_2) &= 0.90~ ~~~~~ ~P(D_2) = 0.001\\\\\nP(A|D_0) &= 0.01~ ~~~~~ ~P(D_0) = 0.99\n\\end{align}\n\nThus, applying Bayes' Rule, we have\n\n\\begin{align}\nP(D_2|A) &= \\frac{P(A|D_2)P(D_2)}{P(A|D_1)P(D_1) + P(A|D_2)P(D_2) + P(A|D_0)P(D_0)} \\\\\n&= \\frac{(0.90)(0.001)}{(0.80)(0.009) + (0.90)(0.001) + (0.01)(0.99)}\n\\end{align}\n\nUsing R to calculate the probability:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#name variables: \na.g.d1 <- 0.80 # a given d1\na.g.d2 <- 0.90 # a given d2\na.g.d0 <- 0.01 # a given d0\nd1 <- 0.009\nd2 <- 0.001\nd0 <- 0.99\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#find the probability the patient has disease 2 given the have abdominal pain: \n(PDA <- (a.g.d2*d2) / (a.g.d2*d2 + a.g.d1*d1 + a.g.d0*d0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.05\n```\n:::\n:::\n\n\n\nThe probability the patient has disease 2 given they have abdominal pain is 0.05. \n:::\n\n\n",
    "supporting": [
      "HW_02_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n\\usepackage{colortbl}\n\\usepackage{array}\n\\usepackage{anyfontsize}\n\\usepackage{multirow}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}