---
title: "Key Info and Announcements"
subtitle: "Lesson 1: Introduction to R"
date: "09/30/2024"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements

- The lovely EPI/BSTA tutors are visiting us!
  - Mickey and Sofia
  - And maybe our TAs another day!
      - Liv and Miyuki
      
- [R for the Rest of Us](https://rfortherestofus.com/courses/getting-started)
  - A fellow student reminded me of this great resource! 
  - If you want to get refreshers on R, please use this!
  - It's free, but I think you need to sign up
- **When we get to HW where we work with R will you indicate that we should use R for that question?**
  - Yes! Homework 1 should not need any R, but in later homeworks I will tell you!
- For homework 1, you will need to the textbook! 
  - There is a link in the Syllabus and a pdf in our [shared OneDrive folder](ohsuitg-my.sharepoint.com/:f:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_EPI_525/Student_files_EPI_525?csf=1&web=1&e=BorimB).
  - What's out shared OneDrive folder?? 
    - OHSU uses OneDrive as cloud storage. Everyone should be able to access OneDrive with their OHSU email, in addition to many other Microsoft apps.  
  - In our shared folder, I put files that I cannot share publicly
    - You'll see homework solutions, recordings, and textbooks in there. For the most part, I will place links on our website directly to the files. I don't always do the best job of this, so please take a look at those files as well. 
- **Due days**
  - I don't want anyone to feel anxious about when exactly HW 1 is due. Almost everyone has voted, and it looks like **Fridays will be the best day for homework assignments**. 
  - Consequently, I want to give you more than a week after assignments are due to turn in the solutions, **so solutions will be due two Sundays after the assignment is due (9 days after)**.
  - For example, the assignment for HW 1 is due 10/11 at 11pm and the solutions for HW 1 will be due 10/20 at 11pm.
- Homework solution groups!!
  - I added a link to a Microsoft form in Homework 1
  - Please specify who you would like to partner with
- **OFFICE HOURS!!**
  - Nicky: Monday 4-5pm in VPT 627
  - Miyuki: Wednesday 3-4pm in VPT 620M
  - Liv: Thursday 3:30-4:30pm virtual

## Key Dates